domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
            data:
                count: ENC[AES256_GCM,data:RA==,iv:eVnVrCiD1vB3XBtPyNLVPG8m8Qrfv6FYlfSyae1DkwM=,tag:lXS9L5Ql0/XUVuhcWISGUw==,type:int]
                persistence:
                    size: ENC[AES256_GCM,data:IXzE,iv:P62HSxUWceDfiZGg1NLxBK8VMYrNBRYzLI6lLYFAEZo=,tag:4Q5dgkZ5EYcGlgMRXx2A0Q==,type:str]
                resources:
                    limits: {}
                    requests:
                        cpu: ENC[AES256_GCM,data:QPpO,iv:NVy/CEBDb1aUSbnJAe0lpXBn0PPkfxSr2DYw+fG0o5k=,tag:9fzZ4UGERMc1J9aLdjCxgQ==,type:float]
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    gateways:
        public:
            tls:
                type: kubernetes.io/tls
                data:
                    key:
                        tls.key: ENC[AES256_GCM,data:3tUe/Lb2b80Uji9PnhU59nkbgH3FngeDpUxu8HeK7dMV9DD7fXlgEHQO7qbKFm5J2CgXN9qoM6vnKkBgEIOAGi0Wj5vdxvKk1MPs9LH/4NquNzeMetS9Tasf2/xFicerAeGrEZJgL/KwkWeNy/KYzOWfULn2kA2vUqxeLPhrZsj9EWS8Q+hwG5gQVaWhvic7WRfb22aYiHQdV/BtMAwwZxxn1Q4bKoG6zOchhb0inXDErZypjKkLLBZkrIiKT4zVhLdX0yA9dZPSCQNpbQNpicSoeVxJkM0k6HfcvKq2JOcKa4wNRSRPWvP746NwgHBnqftcI8fygOMNYp71fGybVYFNmFH+OoXpOy9rVr7dn68tTYao6XZoRXl3hGpVglzofOFiVmVHQUWAt/PV+ZTvaVz7itOLpDD3qdFnnFXoNc9fWfdphCXEh2K2yA9lCFt1z1hBshdPhcBQGg+PK4bkNa6L0nBZbnHLDSCttJRB34ipzpOasw1v/ayhcOpFjzPGftatShi7q0vYe9t5Y8KcDtBUswaxvZjTWj+eFCmFaRjijoanuyVEnTEFF4Kta1DFBidDqCWeuJAJhFlf376KdH8XsG3b4o0GmvhgHJ4Z79Lf7C0YIKoSnDhgaEtZ2QzizWsalcOa9dilHKheuDzMspdsHlnJYcTpa3i4YCqJpi0B4I2qxWKDf5z5Krr66ZQjTN2zXjgNTXYGHyvyuNsUxxF/DEqPrFIVfui3bv4i0G1TI3loKejSwQPqO67dADujyvVEWfDt5Z4UNj7+pDKJQeXLDScVbtJjjMim7Dsez/DR35jYr5nXR/fi+Bt7CfQOpbMEzd1lPlj14duxDzfxNI583YlRJPQwdWGc8z1A5FZsgaITWh9t9sSXGazseyzb5lfJ5D8L7FAbhYd8pevWclFTN+V0mrVpH/WL3QrtsiRzAKS9hIdnqB2G942smfi/b7uxDwqoLQnoMbvBgiPvxw4BhV0IxQrG2PP8wViYjaUWkcRDjmGmi3jX2HhJDoe481wdmigzttYvztgjT31XNvM97/cdg91aT2qrjL3FG902wdhAaxnbiFo6I+kUDc/gx8sBjEN7GvoL5oZEN2Vp6yjeUnqC75f/Uc5qrQTz25V3aoPaoCJL8rCPhF9gObMHHL8DiAhtGfEJ3RR/75HNO3Zo8gQny02WH6MUBYiYqm13kFTwrVzEXU+cE44amoK4M/l2CSdKYxrLP2pis2O/07TaOSzFhjAxi8534gkTHacytyo8ldxlk8TCoasyApefxT73Fzvk32o2r4tgEO8Ibje3IL+xZhS2s4kWtKowlV/FzDsAQCWu7avzuN7hIPsEv945qtj/hYIRSEGmiBLW+efVVrSsJLASUC64v1JpASq83NzKc6yk+REKh0zcZQljXNyUe4YExa/+nB8IyB6DqmNFfK0w1F/+C+DO1h1gN6b7qet48JaXlFp+hOWUOpwdsw71ONwm2TGZVA6mbCen9ipVBBS2vVzktMTTtDpEahLKmL+6NK/FflZLaEXie1nfvibRPYo8kaBvap4yeuZnd5cguGqqrjIIkyAQ3GJSRQ5ii0YeaGlh4qmZwDaCg63EwJ0PZ6RUAmTRVAJwuf0tyz+BZ3mHURbTcrUQiqW+HFhGSb5bEkiwFsXTwC8Bcednx3+fKLnG9azClwCxMlDLLW90O8eI09SUIN147qR0HGMZDFH5552jr8I7VHz2zuSPNyNKOAo0tuYliE+OWPScgFY311jZQdGJc+oc+o2lZrItD9sOxAAH8WiOlA+O928hjLQAOJgwyoh9kDmFbpXK4g2ApxXbVgeV899VeWVDQrv0iJVl0gtj8ZzTMKd07Q4NFfga9gZd5ngziOfEeRDFjy4Qd7qNHF80IGF1M4ud73r79rrVCg6tEij98NNvKMlUhXlQ8I7aewqxahR6eXVeqmxZlnfls1CVheLKMSRMTqN/wHc8CqIg+4AL6YDoxQUEcS5qlFHVKQ4rur/DDOnNitKErZM1vVDb9AYqNx/C+tnpfQy1WcgJOdsK8UBj3uyPPUi5//ZOnoypsJvunSQofALtPtNiwnW/lldCnWnH3ZJRPW5Z7mn8L+nCdBXBTllJi1fERjGAzaUVU+Gu/BXzMNyeAud8T/iiiFuAzKj5gnMI+AxaTdJOoCQyOAnzf2vRxYn/tel1jrJni8MupsvIeOfsDleX4ZAbApni/Xp0XjxhomyN4t3XKdnf//wfxmBxP342ydfhvZcCusLhAj0lukdGrVOWxJRrjn0OMlVJwQ37vus+zPClPg1iQpz/LdUwgH4E+ayZefco5R+iDpTemLBqH6MZLtpL3kEROau+dWHyAhXG3SeCOgkiNpK/BZRBXf2CfaFlIqRke8e4QkiKeND7j1mRz0apGZNNXxEXfHXsLMhfwcLV2vGmvwtW4LMoXrPhsZjKDBdiYo1M6grZDMxedfbn0nFAfdSTgo3QmcsnBG3GLsICEQSqKYLfmb5Mga2lkhLymAaxbUA/YF5Q3X0RU6FyeEUOGiL3VHJmAQ98YFcLcEqFSr6CWhmlyQS+jCOYK5xai55JFHHEc0WLyen6QPcoCJcKeBXEKImvLtMmWRMpJMiKNsXXtMQhGVu2tdSJVY1aZxFDADfUM3ZeVvFRDnptP5X7wYRU21ONF4Wz0figmus5Meil6p1oJAiA6cP7JWESFZwQxXn1P/zzlSv4R7VSyw/TWBg1C7anVYeQKUgjkkM+sy+8ji2unk7OsJOhgRGXnQfi9WCFduAiXkKraw1dUYVf9s7SKzs7Nz8XO/oEN/RXnsAPRTO9PiBJmNw/QsxlHPD2j4Ynnq46ZYLQC3BCO5o0FLZcZg0gnw5Wr5GRSwSpOx0/HG08hbihzqqcJ99KRyXgnMxN8D1FqIIQw4OV3lRuSPrLDmHMVGw/sSVAMbPTOPW6Me2GqWnvIJfI3oUFwqdI7k3I92F5DOFWRGqb9TpF+bzvt1gyTjo=,iv:MF+SBcqqJQSebmmLaEdnydgd01Z7cW6aC4pI9yLA8g0=,tag:zsJgxMKoCMADtydv8mCxYQ==,type:str]
                    cert:
                        tls.crt: ENC[AES256_GCM,data:JSkP7ZCSX64TE7VtmKvvqt6mXLSTW62GGlkEeURETea/4SzpxyVBqVaIY+q1Cfph7ovVKst9YK16K27kEWElRf5Pog4kDzFxQhTFQg3E7E8vhI5o+9IjlTP0922PfllPjgpn6eKmC62dvmdqQlZW6HjffdyZgp8onlYwIGCICRT7SyCYLwBqiGidQeyyzgdvCx2kYpBFDH3Yxck7QjOh2WsSdevlhXk6EdUUr2XF6bNQv+eKqLJamSVSjA20iK1XSF1k8RCIOYsVScw3/CJ7AOPRt2iO4pHxaja1bBV0Zy6PK+GlYpHqiSeZ+WiH4ewfejy4hGZOUinMt3e5F1RALbF/WNi52pxDBTNTcV1kYGadi5Lvu+gPHfMC6X0N1XSmsFDup6p32+3ea3ERQKAypuuD3qsuFrGYxPKb6X+aIfZsE/bM+u1RZbBkMY2rnb3VzHi1FW9RxOsNks984k25ZU0TI4DECw0Zkht09lkxJexPcK+bQUc5i/08Zs0N9jTKH3mGQeaXXDHaj+TE+USUB6c1eBgwZbQ+H8mEti7lkw5nqwqsWCulHjgJpuF3v17kO/l9jjbCwhMRxtzvH24sDT6s0SRq1mvsfxcWEy0ZJDa85JxfJC6PssT6VZz6Xoyj0b26c3cj6Lznwro0f+MSCrl4s6tjsJLuWFs/WMoaqba1i29CLeiIAPHYDjVzO85ZabqoRUL7e+QcE5sBSZhtHHzQcD9WpoiOkx6TCrvFPPXoudrByBqiDnIhBGrfejsM8N8TG/GxzogpOaaEzoewc4ai4uU7k0d2feqhQsges4sXxpRrY/wQPPuUyu5lFEn1kylpibAMsVQhtNdkh/2Pqb9MMjIwMKfOZae3KVitBNIcv4VqmIgsuDrVKuBLE8JFgt5+Lcy7S/Y+olUnKZQjfB36xh5pMiFevBbJx56ifNnqusMCBKKwCBoItk1WdzubJQhtOMueJttmUD+LVLO2I7eUqMK4S5cZZFbA6anI7x+9GPhNC/HgT5+C52jOYsfqx6DSIlxW9kjQhbrRwdYDW4ckq7ralL4BH+A9X+zWPwTBySyeDSKJsoOisZzKtLwsciFLNOPXqw0P6Ms2kTN674w4Oyx9zSvdzds9vfktZg+389NnwBN21u/fhyJU1HzJwPgA5poZoPSRrwdBzHhq5nImsM8CPK7naRFMuuXA+JkSQGZtSqK6reCoyo68FeVGXn1NVdSlfxP5p22hldgTjqfwZCP2i7AST5Pw3SgVpcv9CSqnsWA5YUIbSa6KBYTeyRC5CC5Uhv5YAfW4UkHPJogVJ+vB2y+saBPCW7ZeTfvckkSOlwa2dr5GJ5v21wS25bzcMpR5xJHEkILAhN7ALaf9r5fcSzRNjJNofl7e1Lq68wBNZWH1pox8nadSWRN3LMqbQp5hIfoOlsfm4xh21l84zFnsAvBzL2mIUQkaXTDHPoaJMOGgxohl1lUnTk+ZW0DiGBJOc3uI/a0YTzmlgoYKHtQTiFeR1wzpZWLQIaGPO/1xp4v1qxtewIhrFdO+7KlbvwE6ewtXBOMEDQdL2l14ZuHGIFobczFHhuZdKV5K8h/2KPS6y0a06gfod1D4ArOEkrlRzYGMck5/sD+SOY1iab6GGnau7DTTdYC73phCdS0+pTXFUCdKzeaqTurzyzdBP83UbIYd0soX9FAd4lqZegZljCYaxlLmIedG3m0GZYavfIpTTA1ev/D7J6hCEEpsN9Wv8Xl+4ChUonVGEQQM+BRozU+IpAY/M/6rqhwKHsgBI8bFtphKT5KC9z6pbHWapUiv2vCOKZ0qIuz3iAS8h1OxuJtCyqQNggwIffOXadHbEXHjqTpaHsuZglo5l5DUhvJoahuRRHBgHINXa7sIPu6Q9i4mYputamTxdX5xq1csmFFWhfM5tcc9JAVtEiKo2LhtL3L/SEPBY3zbQoLc3P2ZwwxzasJcH1YzDEoH+8gXO5KP0rfkZQtWXiRLVgEdTMOJoRG6NyedvK+iwRyGAY6amuVWGlInN2ddh3W4FfPVDWvKov8DZNtMDdAB5+jj9cxw7KWnz0qZkyCn46qWiN8SimycNtm6jBpil1X5PstEpm+f1a4w5eetxvrHOCvgM91GgwPLPFVcXHKzFvjkybcrdPvYUJu8OIfPYARzCox7kwhlGd5cKBtA8lSsULcl/T2sa/kBKJk/zN90Zp8YDZSIbcyf/n9HyEGz+9S58ro38wx+ZWqOjUch4vLrUKh3SsKGZNNtWCMV+16yAg4tmBXCbLt0pEKqqsmFB3AYbBUpWH64hsvNtOUCSHkKojJNd8fwOZsbPoogPtDOOUrxqs0=,iv:KQAdegQDAjpJc7cj6u595AqjUtJNhEJzRVqnYonme5A=,tag:waHwy16waGBDmurQmOwlyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T17:34:50Z"
    mac: ENC[AES256_GCM,data:bXjYU0hWpsD1VpBwnJWGpnT27RQmBWDbV4vat7J/S1ObsExmPzWgRjimfscJsNHYSeEa2LIVX/f6yi6+y8W444Keaf89wg0FRp1RzeA6M1LTAH9SoEikpZFQwPSQ3pO49ASHIcuf7Q9nCJruxopQHwWS0uSEUKv7ejK48HmpbhM=,iv:mUVx0yCYJ7UDdaenAD7/BWGyiNFU31wGgd/Y8JlB40c=,tag:kBx30ExmyLdePb/QAhIRWw==,type:str]
    pgp:
        - created_at: "2022-03-24T17:34:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ//Yofo2eEyF0s91jOs49fRTW5EPQtntXFaESeRbn7ZyfIe
            /sn7lYSsW2sv4uQx8v8s2sXDLo5oujA8NctV19G/wpN+rJShjAVOnE5ENp0rpeAd
            AguPbqjjzsd7iO6qQ1TlPLnWrMcK78N8mjBx7bJe6qcnhxvHcz1ltw5oQvIzPJRp
            AS2z3sXAV37aUecvSudZbaegsYWy4CMGpr05XaZwsRn4ye7TymhhEliG5xnSRyjL
            RRP808dxnwzVSyzBDzzK7g3QNCET6zDEB4qcLdgRDDyIaj1hN7LRypL3LKlEfWzt
            imFrwbss1O3eHpi8E26a4o4hVuhqY9wkoWksBKNBp7f5Sz4lG11j1OC/DXZRorg9
            fL6iq6pcjab7bOgxAU2ihWz5kOL36R424W2m8mk7TaemZAk+KV3MTXAFSPez5k+t
            Hj1FsH9ildnTWbly1k4mwcfX7fjhs6p2c7wLeq3h9FpN6qJ9ZrXRv+387m7Dcxz4
            q/kqPuQSmtBFBLM8ya5dZVd3GckIRzYGea0FlcMy81bVqO7Ex4NV2gIkFEK86K2e
            wRzenIwnCWNNnygaxAOVTQmbnfVNiWfuhQ68SHog9t2NNCtTaay6v0tNsbDm0/Pg
            BMQRBAXE4HBos5/mWwLMlcnU4oVIEAGZXyvPekyvX2NqZQHTj5DCdvZOhfTaXz3S
            XAHbLNq0LetCnUIudQ3E1yrCIzWTlS8wQaL+TuIiYD8NX3LkgyEDVE7MufLto6Z+
            KUr82R3pMp75Dbri1qPKzsUNwGh4r50z188uTRVDjvpcua3oy5TOnfFbb+4c
            =ckXL
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
