domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
            data:
                count: ENC[AES256_GCM,data:zg==,iv:Ubqe9RslhTDhT9fJN2fg4cSiEHxhXlavzISc4+gNXCE=,tag:b8rlHoG7GVB/9G6AVVRFFQ==,type:int]
                persistence:
                    size: ENC[AES256_GCM,data:aQz2,iv:zltweTB0Z8Hara3CLIDFFNwdB57gkELAsJ1yEVkutqY=,tag:fGrf7NEHq3u6F+juTWOUbw==,type:str]
                resources:
                    limits: {}
                    requests:
                        cpu: ENC[AES256_GCM,data:5lte,iv:43ld/qscnSf7Fx3kbH9VwXmvulOfkGg0gDX3PoN6M0g=,tag:d74PkFnwhCOb/xKPtva9Xw==,type:float]
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    gateways:
        public:
            tls: null
            type: kubernetes.io/tls
            data:
                key:
                    tls.key: ENC[AES256_GCM,data:IEXG4eA3rEnWsVyUYytM4SmYkNpPpRgifT+H0BQCUS9Xod23LKLcxcBkHn22QIsI5wXaPWJCWTLXZidTKzL8gnUx4jCghx/f85iWoG2QgOPC+S1MBiwS0PtjXpvBIZkmsBXiaOxqgUdmiTvTE6adAdnwLv4Cm8nU/G2F8DaMYF2qPnDT2by77UYbeAcFcsVJwXuwWi94PKBhqa1UozfGQzh0gt0RS1++QKXbdpg+NzOhAMmsAmUsldkkwPgy5Vw2mKIG1GCmPaSt0IBg3JfhppiRm3DWFej6QFBO23mDPt7ISzyEQgMwZ6+nE9SSVEfThdaEZn7hYFFmWMTOke44PLS3qqEKOiL5FeCMdnkroAmecgTSw2JjE/bf/pZFK5gACyMQQHgg9I15W7whWA/JORYokcW5XK5dLHWcYZ1Htxcl+YriCv/iccoEpw+ZHWEkVhit8s/u+DgxXywWyoObW5+2E7c/VYUHJemrIzxC9UCPHwWdj40SoLRIBUWtRgRp/HXQcpvV5bzyflXsXqLAbFrnnD9QfGZk44sbdUQ53UHZW1ZTZwMT4o8pJ/8ug9UFVpGLOQDuPjB2ydY/rXiloOZ0nultOJKc2y+qxSnmIafgQt4/fU+I89PdedjVXQ4cfvDYuXtGrugaXpvQ2fsuCQc5TJY+L57pcpLOqEcZwJEEiqptlBOTbNjncMxwwMBIHotOiR+5QH+ht8/YuDzX3AFwm4rIbDljm8OEJMsJFq8TziSoepflBSMXpWlQWG5pJOcCIzHGJqx5/1qDix53+xgqxICHePJBa23Ko2XtO2sryJzEE9ZmXmaaxb97kv7v3a5EvS+luf4Mi8Yd52QvlHv97bEYqvwIUtddAsL4g5uBxOflTl30esify1wV8cyaB43i0VoJEmESbtpWAgDEF/ICq8Cx+iIx2ZfqebwIGVfSIpEDXQW7cOmSlCiOzYd5QumL7sG1JR6KWhAu4ktPJAKEmQvTsFusKyLcMphe4UfmZ0tZF8/m/I4eFhdZCrtIFnvF0UUGZjZ7r0Pvt+qC5F4GW7ERNWyZvT7vppLuRn8CupZ1C0vHGMPdRs97Ksa0s5pKfddCaK+o1qTQL3RJZEIwvyqKz3HB7TU54ODBJlq0dyLVaAApX6XivEVMChXPqLKZPX/nt64IlNuqpXIQtspmQ7sBkFMvBIDTbSSijoh0YBVg1gBLm4KBm/+cfIeZpENCZd9o+tZwS8gHxgcvNFurBNTuE5eHRkRUyQkdHdZtwesgRxYMCFhT14ZCEUAf+I3WHohJu/1MDPTQVQeFoTCop3ZePlNH5I/blyGbHFLECtNN209vuOMzdQsRVVQLkV15Jg0dzuC0GH/tBOWKZ4vf4ujeHIgdKDTB8YUXTcyfX+GGZuEcCgEWzeVXOeqn3QMD+Gb51VCiYzGlyPC6TLwfcTkr4u68iS0oTDjEmfeCTgEXwLeS4Ra6kgBCiaS0Q9dW+tfCAFcI7JfbIhmxPecJGbuQ5e9EetErV32fsiTOb+2E2dutNdrxTAbUuhluOvxzi22y/Zt06U8oeDUqsnU4HXib4CVmKjgjkMFJ+c4V3+t2j/TpeMEn8Rx9uIWvPGPgJ8l41Yot5mLDh93DjOedse4Eh9SDqgnhJT1XMfXVGiQN8B1AqaRAhBAHES6weXRKfwCBsl7w/LMuXMkKQkQBkIKOwD6QxjitTDUOB4362yClENxofmWd5x0joi2LD+EOLGV1Vvn1tiECFStezm/GVk4b4VuapkpnijUIhwQMoMO0m2W2/FRPvTwJMKupV21WGsfh+n8poWa/9s+rmzJ01vMtVDEAcvosOiWzWwBhzj5GP4p4eKpngmHdChQq/kBrfNiYJLKXogWG8LpbXptaJwek0+tKGdKLMPEvZzbB4lCblCKyi1Xu7tZnb3cNFVxXSYwdJIJdQAbBaBU+0Xw6erjUfnVvD1YNRt0/NMxtsq0XfPQ10fyxEGTfj9dr+AbXJ2fqMeq4rRRWNa7khGHXwNE46dbh6g7F9E0PIvEyL5mG1/Y7KWi+SEo4vuvngYPoY39vsVsD0cmN6WK+qiUm7lMjAyhOwWBduRQzNI46kX9aJNzK+k2pAtsI16bj0ooIfYzOOAYXsPc/F8rmaWNNMC7WnT3/PwQLHrGBWLwYc4xnjGAXxqF1IthvykZZNLf+DArB/JkEeWXDEqvMWLmt6tKBPpRpDOqfDULHBeITjk6IFVngvII0lR+mWptVxG33WmpqFlXjpJ+Iq+ZUHjLx+gSdDbSu165O+dS9QHiHB9mGJd/cjpYQKn+94nzISdeQ5w815UFW8RwuMG9ZHQLIzbqDIof7HLhF5ipaHrGfaMcss7+dtKOj8GTGVZdIwbvx22TsPTr/UIU+VO5vw7EKkJgRK++CnTz27WRhVOs/DQ7I4UN3cCQHDt/cD3YM+dpIsJ/kH6/884DpZBqGEzntvJV3TWa+IM1JMKZN8p/umMbmhKVM+UVcV8JBG7BE2uouUESr56klPsN6b3ZcExHs/8i3FWcp/KMumqJAsny9XtzOlOu6t489LrDbeWmffKnqLQkbxkCBDv+p49EiXAUgZUbOxfuDtAdw+aKpyxO0QM7E5notJLIGD0og48PU23QUbRtYkJjxGHfC3VAsQ8g/xfP/jS/H+GEg+XYdxH0Pp1Z5SFTCzcCw6NPdPsGjy/qRi5lWDn3pO96cqHVfNNry/HUtzptfH0ClkivaOxNtDOuKHWRBHsHG3v3ao2SOCQv7yENN190YRko2YV/DGkgpBl9ZoIJHBiHcywGsrxDacObG1FQtW32aDA+exhQous0IBLOPgzOq6YFpTJAseBuczBseAX8EX6s7j1B2WPzslsTQXgJQZxVzFAJxhH/xFyaGMSPSGpSGE1UAOptfrC5Eo8sPSh8vpu4hPPfut0e5QWHj0+ppjDK7/ynRTp4amAEetWcJ3Mz/tB1Z0xlBv13o0Vsz1bIPJN0rs6jic2o=,iv:5KW8ZU3S2Y52ZOx9r8C70HklAe3TACPmiCYrddOH4xg=,tag:sAY1u80F5wfetYvSn8d+Ng==,type:str]
                cert:
                    tls.crt: ENC[AES256_GCM,data:8mLN3McIBqOL8SC0j0nu7QrS5cV77Ad5RnrAnQZxlrHejBi45ywNBlM1mKqU3woMl2+s5d7OTLcLTf9wg03CByAgGR1AjgO0H8evQL4HklTA/m/s1PAwOEZ90b1dMTf+nnWL+jaY/2bpsrrwqfHK/bau2glVKvy3aXYdGalf1sGZ698LRd8qG7TUVkBOgjSitoosc82iUHRiArKIFpari6YlL5a63y/YKqHtpAy5sjkH26MPX3CW8Q6dG9UswxDYvFFCHm80ZfSR5U3wjdqgWnvXPxd36zxuTNOj227JpIeP+1gY73QiZV8Kx8qeKYyg9frl2vGH6ZUf/YdC4LekJ3cUwqmXFSONAzcAW9xeztEoNHfaarnnXWdBYnX1NqwCYavZdb+XVcywc6rJtQ2e8YeR1bEFHYgh5iL5trkXzxp7bNjiEHZMLYipqv+xh93U09U6Dq1nvbtKBEhUamdeGkF+uR+rVvv1QM3b2S48XlHjHGHEkb6SUglaHT+loGQtY0JyZb3sZyVJqNquC+cns9ofzhCzyV7R7/ZamslijiP112Q4A/djp/dt0hj2EWFWSwjODstPdagiMaOSbT5NX8YwZpU/rkq2jBwnje0Q45pxEnGKby1OacvZFNzY0zD5B1gySjXKrNjgXPL2827DwEoh4kkDr3b3duKUAH1Cn0WK8SEoNVEQiAMrRCwomYcYNon814Ck02RvK2rQ1oxmTxWYC0z0bMn88LYPwxnQ5vMWfAybV1NAeynhqoNI/L34w5Um4OeyDqPhsaUqJeIWhcf+oSPQ4E6pPWZFTIsJ4KXC95j8rWU3rOf3PqoIQ7/qbOVwrRZPmFvL/qPD5+jRreQ4jYMTno+vyih1RvbJvwVrmN7j8JKXyc8JBVFRSbjrdYoLwKkliUeQFfSKgJUxQ14FwLs8dzAst7E2b5QXdZ9Gd0CLMItNPv8oGgQceOSlpZTVlUp3aKeftaEHg0/ILZYps6a6y90WixLPzSRvTHoX+TuxRRE0uU4pFcTF7/7+h4hSboKifLKHKBzeRwS5i/bKyWgNA/bhYqZhxuIe0AC6I+t39+p6ffrTUK4ZIAeShlp5mn0W9ZW0K63B3Yfm9VGDzoGlW7CNvYwaIVM8CCstP1G9zUe97MZd0XymAeANwvus3ZehIguEjU49HjKMzcCYPNlaXdlGQTG42lXkeX/rFJF9UyE1YktHD7+e5zRGYy5IqESaLgWNuz7rMcpwdqHnmrH5H29ilV9FeR5flFlEakykgbre825cY1G3HakKpsK0+9YhV5Q5gI3YqQH0aLUixm6idS06vBW3TCBKF6bcccLza/2ovVzZ6BJBMCU3Jk/7tWt2AkLcUbbvU6oMw+FEs4lmMNvE1Wvkpvyszt+JovWDAtFdbw443ADDe1M4WTlNOZfXwlHPSwK5Ptc4OIpQi4/P+2dmmtm7huMMmjphGeIMyQ1hSCthjaIhAfnMPg5v+AUjqCZIMoEsOBTQ0Vq4gTYtB3m5g1xjQ9jYzg5sBtaSbftuB5foQSM62QzZgofgH+a7uZCO7fvTlZ2KiQVl/GOtJ22RQvwBevIMkfCZw3gl3LqYyT9ddsNmEh4srvQoYnfFo/MQ7EMkGcBCr4xuu8n0VvE5LYmqjL3GSwENihFp9pwrrEwY//FmyxbdhcCpkag7+ZVd04PiKk+qs0/iwr9j96VVuDz/F8OoICOt0OHb5wRm9YKSqXVy440n9Vl1fG3Kdup+pBxSwyW16rOJYJEIa7xX8ea+s7kqCSBELtqdJm33UT9BlgFD2TqibDgm4ztopc6yAQLDjDE6g2p3hJSWkH2rQWBUOUM/V6EJ65pvu3XxKjmkQDYN9yoZ1OTNPRcwg6tktXXHJaMnLsIrZdBKzfBaME26ln9A7xujKe1VRgaKzGBD7xKg5EVqax7OAmg51q/ga9La+XjveyxlkQynGEHSiri3y/Y4vOrjyF7E7zlyYkO7yxmjXQHQL7zUZiQUu/8l2+ZtwnehvuRaoSW2Bf/okJbzqJyWgpkRxgjHlyRZ2wqGWcRULstIlmW6cVbjdVnu60RkNMGNISakZEm/gccvmdRTu7Wjmdp0Q9TsEB7i/gcIxH5SuYZvQA49X2iQC/6VcMRegRq/L4fAYJrKxeoq7lR5Unb5gstC5gKg4wvJyaVgQt/6lKqo8ju7qnr3PTQPlg1qtgLjv33v9np7zYC1F5QUqUXZyVbLG/9q+GOswIB+usGCO1/VjYDN5WiEezKOjJT6vwxgROvFmj1Hw2i9ku+6V6WXBd7Y6KF+lNJqakVaZ66NuBSzK9MLp2WI6OPAsjRrl2VPEgkO2/4=,iv:3YS6CDWqcdQejgD/xb2noihokUhun8qlpMNYfF2GOsQ=,tag:u1zd9iecjjlKBUlAI3d/BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T21:05:14Z"
    mac: ENC[AES256_GCM,data:/uzNVI5OiZe2khz/ZVL/e3wTXcPANZTLVv58h3/OdfPI6QoNE3IxmLijvUbjfULAltUaAcolK5JPDwxovZZ3IzRh4zQnEM4sfxtSCiNUPqzkYKKthRvvX9T2C+uRwBzhrc1PeTLKPrjdExaCta+kdi9L6D4MDGMfiN8UTdbdm3Y=,iv:zCd2smFkxKe5VJbxJ600eGSr0hmBjgn57dWCmM1avEs=,tag:sPPo8LeG1B+yxuY24ksS5Q==,type:str]
    pgp:
        - created_at: "2022-03-24T21:05:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ//V2cnUQZZc27OnOnzGeXgNKi0hjhA38TE3VipHSo1mSuG
            zdYUQKI0PG4FZHs9HooUeGHx9jqM3reNGqzvfOg3tTRZFBGpudhr2tBr1YTNKG5+
            f92EqSnZ39dCQOkBn/8sU8rZEF3nxWA05S92FjrZKbak91iMuPYT72stZOb7jHQV
            k1i89M5PaWJp6tUQ42esOqXsqgZ/VibLg9C//iy+5FzXvwZYin3iw0ouk4BFDyNz
            UQ2O9Diz7MGi5ZTrfBNKkkwNJ69e6vVSlN+tBiMSiABk+gvOohblf3te/AIa+RgG
            07x9NVHDyCgfp8Q6rFWvDCMi15DzBT+UockTHNh99WEx43Pk74yzrqF97IhVeGLa
            ZYwQ9tSuCY7cY6kXJCSUXG300b9y10OLQbETCR8ePwnqZxVWMNfTMDesTRjXyl9i
            6kyEh2xsp2JD9g7xa7UxykAC6Ho1LQCYM/kQjWpM6R2k02lEjyIRjZOQavJ1vtXv
            SBObmN1ADkzjE2nFNc8T8s34JYu8BEKG8lp/xhZ7gU3HfJcPobIr987Uh2bAvIla
            goaCfw1WDiglFI79+t/g4pyXo7gbEauJM61BAox1SrY9pD+h2Mq2RBWrC98AljZo
            YB3SvkixpEk2g5sTm+UejJJquUw6oeJyhRGuR5Cf+QLXdbiVwoq/kWvwnQghbmfS
            XAHqjs3uLcNrK2xTHkiFiFV/OJabdaUzZWzC70YaJAGzI3VWIKUjuZig1OGDdnk+
            VXN+FOOC9QzODigeh85OPJc1thC2UCJnmcYQ+eHgU3ZCU9n8ZIJZ7hivb22o
            =JheV
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
