domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
            data:
                count: ENC[AES256_GCM,data:xg==,iv:VwlTiT/ai0LQgoXv1cWK4m1bqXXjCTU0JN0LYF4x3Mg=,tag:Bk1prs1huS6KYNi62Eamjg==,type:int]
                persistence:
                    size: ENC[AES256_GCM,data:u5BB,iv:v2Ncj3T8A+V25mgiWSNz9tZMxfo8hb96pOlZY73OiE8=,tag:o7Xn1524wr/dD2fMcreUHQ==,type:str]
                resources:
                    limits: {}
                    requests:
                        cpu: ENC[AES256_GCM,data:vGev,iv:quhD24DK3C2WqoKtk7rs+3veLXFtj2V4wPcw7u9i2nk=,tag:ZfiLC/8cFkz08+6cNH5gtQ==,type:float]
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    gateways:
        public:
            tls: null
            type: kubernetes.io/tls
            data:
                tls.crt: ENC[AES256_GCM,data:8RYkD0YrwN4Aot8X+uiotKbIEA2gsvWVkmk3bpxyHgrcy5HlGqoevS2+oQEhj4iCSPKeZX6bC7br+cjgbqAmuSIqqysS8whXh/NjMKXTLTZuQkAbJCvPx/MtrJsDJ/oS1uUkcLfs/fxSDi7+Za+h2XG/qLoNPymwGG0yC/a7/j/reyWujIXp6JSktVD82wc4xTZg1okxADPwRiaan09I32ALEj0FbzDXQ5+MutwEuB2DKEX76FAPPiuZAVddZwBjLZH9LSRMyrg3e6ZmnpbwTDX4K5chfNqXv3QKU9lIkYBWOSP7QPdDqGr7m4UOR5hFufWzbwVhGbdeCoh7vEDMAh7ZqUrKbLe/+IbBlHJQ8CKE5PBhmbuH9BieOVLxAR4Nld78TZwo/OGvKaKh+wM0MsHKXYKir566u+TKGhkp7vNIdlO9fhC8Kc0WALRyl9dbFW1MYzkGIJaufptyd9pXqhXB2kaKoNf5e/elAcrxHQsaiAlBUBIP+CwEhPIeR8AFrKmOYZE8pIQlLp53nIdLeiiByKob1tMgXSJE667fZyxu0uJBsTjOp6X0n+SCgC74lSxCsUNur4WUoxJW/HXUa7fV7yEHx5odWwy4aO3wc3GEU0mYjSr9ISBY2hAXEQ4bAhjpxQlt6CrMMRzdYfWfXdZ1sL8KDPlqFbC5kT+0SH1dS7tw26DimNmcun/t9NL3M9lAT0bJwHt3+P2L12Embm6WFp4JVziiKeF1z6VAT9Sn7Dk0MUjwYsgxHUpIJFCkh0U5TciWgnTrjif47HMNUqsxjCvI7wGWTkEP/OMuROpaiZacLeNto9Ko+OBeHwSesIpHXa/zjMPg0E0jMBxZnrc/e9IZOGffMmlytVEJrbNerNGFVGspCsLPkXe72vBNF6/9BYHpTZ+UbBMBeYnGnrqLtz7b/ojap9lmCsNcv6RcYWzI0smKlsJug6bB7ljnL/i2fYg0c6U9Veemq8efaP8ME9Brkpa6oYG/zp+OD7Xo9vMODipOZ8C3KtN7TNiYG84tlH39srnaqpd9z9f5lPfU+D0I9/ieYj3VMwlospQcg05oKcmPpxYe9Px1r98iDxfXwae4FfJdQoAwJph1K4khP32Xfmc2M9UrWjVRHNd8aoWkMhzBfVOOM6bJIcteX0qlVGwtmgttwFJVkNclRjaktV8bgQaTyehH4kfsdISOPtDmpAfG1rKpBeZyeCV4Tou0g/qukTxAOp50xwW89IN1smrOn8eWk/cXu8V7wc1fz3tUCi3Q+3D7OfWP0Ym+41ASiz4uN15BUVXCrN7TsTueUjIiw1wH1J69H6xWsixrhHawzp8g3MxzHChxWoANToRKhJuaSP6Gh31sNR0mVTBUp4N+sfVkixHm3CG15Q9BJ+jlxfm81ZBrojxI9PiANIbyuPJZ7azlUXwgPOkgGXLHuWt+yYtdLSW6v1KFX92laN6YTnJC2oR31U7XEX03YpwN8RBXrK3cNUYoIYVCEzCgfVsjxSgVEVXSUmYrjIIlajqCw/+aL88TC10/PoHJ5XFx8umOYs77iMAd+lxp8RxVJdOHxZxZvjwgT7qG2m0ydRQeDnre5Ew73tY99JuXhW9Ex+jvwFQ2OBJmurDaKp1w0YdtAK+HfayjATDjaIvkxvCuiHLvVmA43TDQiFqhhmsKXCI4SE7yL7IUXW1f726DV3s4y1PFu5L3BD4XwGhNRO9J3hXYcDuIiCdBlrDhhQg5p8yhiLAS2MiwckNycRfz8PBIPPsXyqFXdlb0WIfPrxtexujifYwaGQ4w66usuzj8AEhcVHDp1P8yVuiVo76T/xgh7caQKKFOLyCgsGyXN0Jn3OfhIyDZXnI41CqsJMLv3Jz357YQkRkxjdW3RJz8b5sTpH7dEgEJBE2hQDtLBQiK4N7pwivn3fFqZ6i0DimYadWIUXjMQwcCktBmm/0EP27dCZBPQaBWPY+KhSNji2cremErdN9aplK9aNhd6bjUXsbs1n9ScwbbbMPOJWzJp1y2DxxxNx1IXsjeMKu8hTCH8Zh+2jroUfrR3cbWKVqntchwKyhfNLF99pRhE6CicugWo1NyaWcjAxjSdQ016cbS7e04W6/LHEs3oITKlrXIyg69dffaft/7rzlKfrxfmM66LA0q5CeiZwE8DNYgBWbynBgru7SGUvpyajlVo9WyJEwiPJviiDU1mt1v2K4FWVaSgZ1iG3Z737e1Eo5M5tYk2WiBioncXz4U63OvTl+x4rjMS2Xgg0kkgVPJYk3nHgzyXWPsQwG6rZgks9nwoZuAExxL81fM/vffEOFLEAHVZUgJozVW4XRrZPoAfbVTisI=,iv:pfFZIAQLx/bImBHmIM4tdwX7nFpT/JkWmuAwslBXE1g=,tag:yQinp4I+dbxzfDPR/W/t7w==,type:str]
                tls.key: ENC[AES256_GCM,data:SCThW9hoYEMEjDO/vwVzuKSNwL3ffitqzRcDjR72iJDaZ1PA0tgBeIDlSQn7KeuMPKmvKDn7XxeeGdSq2EZ2APN7+felxZMuFnxTFo4Bgj1deuWvY0cCu9Iifrvv72hLAZ/3m3y0MNYvGhnT6Y6lKe6RxPCDaD1EybQH0q85pRlW9cRlqlxjuSOOYrwqLvHou8S8QdFOrPo3EW19BRjF7R/NC2DyXFIjwXHErOQ33MxKr4nkQQc9vrbAAMQ+SGNp+M1IccMP2FVIHUFRbbepy0X7rf1dmB4XRKqZR+4iMQuvPYbVV9bJ810k3L+at6ldRIGdAANbWsyoLkkG0F9p9LFbGnmSJmFZN0kt631RMGUXW/Q6pAjsMFeTs8arBCHQ3292esFzeSnIaxjOPp91cTGmU9wloqoBJSargLxOVvljDi+vz2wWzUSjUAwVvvpQhzUStrxe0RxKCWCQAvImzGbhEGsuTbktA3OTp3aYWpwOzn44dvbR9zX3Dd1IS2C8QsheG6ei4dqpmnXbn+Ubyw0xZqkpy1wN2OYxmiy/ioqqBrvVvhxUZhnU/4flnsuGtMzEK1OwZ/cMlOM3aDPUQ5vcu/uWas9QO4J3pHtq/ezhB0+/xtRs9H1PLf7Oel3JP/wlxWjFmsnhF9zoP38qqhGKj1Um3T55g9nUxfHQVa2TaLJyDv9rebHEM6BsMDWHX/ZMy5mG96JkGSP71x2lQABhXqnU/gwo8FGNi8PFeUVEeo4H1GQTNDf4AXZdhmcYJiej1gd/F8iFFoUm10Iijg0TAkm+jjJ+s6uBRBqKTR4JoajHWLLw9gED/y3CXAVM489uagOt13ylJKPCc+ICfNGn03gJWd1Cj2/Gh83aPeBvs18RNILKPrNPIhKZHboTkgm967LVnh83HDGcM5Jmb7I2CwF+1PSXLqfZzqsyeFuvPCz3G8FmjkGh3hPcjAJ2JpE+RWnSm/o99V7O6bZEy2ehrUudBWx/VdiQ9qJNGQUn5KfKdZ6h8Rk6JGTc+gtkCG9GPnRSyvOuGI/lq7y/22tTbF8QsmvveWYj0RJsFwEYwi0LZ/oo4vAjJ0ImrqsQJUh+gsIYW1ZAkOs16JDOViAjx6dO5OcgdSVPzQW1+H6tNNI62EWkA67FcnsKdVydekHOYapBIPWLWrgSNXUgV5HbUXYrK4BfAftcabG4/4OVmJM6pWIaFStPOHNpWOH16lCBB6UAIZbR5U5ZLeQKl1eFXHSw4md2hN+2BoyFUk9ruYUsSfprKDzsPvacygGTuB2pdVVP/EXE1M2eZ65lsGTnq/GPbOTWbr9FOVehjQfe16Vf20EvcdRanZcbl9b2aBjhbjTNb4xSfYBDGiy+Bi9D4SI5MlbvIyugnWxRgS2oBI2CmvzjDaTBKy+gDmho11KnB7uS82SwbXABzdJaiU6AkTB3YJ7AxwT+wio7/d+vrOyvKpVsqye6f+aqBLB8m6jFmz9p8DJt/FD+OSVFhSrGdKuj1m7NF7+9wxabk+qy2b0MsCbccNBuYjnVuYbQOGrn5ouYtkUzrWZYiR1M0qGxqGu5+jFMYCm1XIV2ebBWn3n7nSJIZnkvd5lInB+b6rZvWu1sbFiE3HleG8pmtWi5niSSotDn/exQ7LRjoVewZm5/9fFAG5ERMjpTBTXaA4G2jFcWrQ3jwi/5SYRRVK/J4s72fiilxTjVwI38UqTDuExq2Qg5BfiED1vvGrdcvy1AjEpcLYf2vbSksnG06lluBClVmdloBGhAafmn9nGlKTcYTK46RG1KCJYw1CHWfRewowIEDnh+yAWoMh8XR0KLzAp3L9X5aI3/g/A95euyvOM6aUdxHfp8flMHWDMxayTNOAudwLtoBO2yg98C6U90heYJ08+ZCFLep0asBS6p+FStk48pTFh9/n/D6PHCq+o5GgmgDJKps3fAHSlKrcYUj8j/rXAfqLAoayGTW25mmRVJXaQQvesXuisZPobtxnpH38PfP/gdrHtasl3ICm4q6lCh01pQZvBz46QJ5KRHuiR7Hy9wWWgABhFlTDCeE3WMdD0gquvmjfcJdwRfA/9Qo1e9MEazMIqmLytDYcqhE4Y4BFDrdna3mPlUrDDnZUMu/cWGtmwSXWTLCmQyjowPQmRsSm3mD/31/OeOFi1tqc432cwABawsQEKXwXK8vdDC+7bS3MOTc0bk41LPquBfs2Ue9zpKPUszDSMwuXVd5AmTzpob7//t+tu0rKkN/zUBkNEwUOgHqr41sB+y/DPWCGkTiQ7SglmP3AMlOxYb33KEWtR3x1xb+9HzKLBNf2G9zwLOQ9Q6pejFUniZqSYPF4462wMqbzoVx74FCv3zvjo8CqPszMd2Q6FBp3xg50GN7c26aPemW1eJqRp+G1aF22DBKjsBTjiA+80zXw5S6HG89EcF1qksUEEP9QBmAH39PkDGWQJPi1L0a0YjzsI3iR0NCgqqesV0JLdxFODlJRue9bIuB5s/6XbT1yYlUMYIo+axI0XZdK/5lW/xacNOQxKN7meFj0T3kr9IVbP2SFD0Av2BYnWD4ZL6u5N2oLBJl1gSc/VuWJWxGskwoL544Cro2IsA/hbe5DjRQ+Jo4WM7wlw2BUjfdXA+XM1LmF7KV1GgZPjQKErm2XMoqncQZIrcwpSWnMcIzSCQfIhztSBn8+GpL004MQZ/1nDooNhxpKtfXKLcR/+niHOribNr49DwL+MUT3VlXC5+8iIKvB7cm3b7QTLCMZBozVN53UrJVqG+7qNCWKO1PR6Rt1Qx9X354T8M6+H/WZ5PWjHFSqniLy2eC8i0dD+JtcqI1Ox0LhsWiLkx8Ypo8H5O6IkKIWda2mgRT+aVUr3Fq1af/E9iFz3aLBTEbnrcOG3AG4kE71n6F4+QnHbkreTMtstJJ9VwfJRZdV8ql8fEIXJb+49vq3SfA17l6/uwe4g2FYKqx/vsfNLs3/AcPWhVRLhPehkLBaiNxK8atP65W5M=,iv:5W31k6YkAUBGXE6rSR4ryMHJRklHhNRpWAlZ5KO8OD8=,tag:GH0XeYJilE/Pqq1RETAKHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T18:59:46Z"
    mac: ENC[AES256_GCM,data:AFnveuCuwapuDZx3eFDrNcBIC6P7K49AeNyfA+0G79is+xfHUY9JhKLzILHdsjsaDj1hH0gZ9afo1wcqjFYL6aser7/ODQhemcZtXaji4XLcMlSs7MePLv9K1d9wArvb5uEemZaRbnKQLU1m03zKD84lDkEzCjWcGH/5mZjooTs=,iv:loZbAd+/G7p+ZjtGUxfOX7Tl2RJQSvcqH6wZbdl94Kw=,tag:pwq3PnhM6oAI0Ss2BSDgXA==,type:str]
    pgp:
        - created_at: "2022-03-24T18:59:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ/+OC8C+ikhR/mg+83+eVPFPrWM+ELSrBZalS1kfhnNave2
            bopkWKfnmhEG27UNmWtd4/DtxnxI2GD05CwsqGop1s5MHdlnSS7MkinLzDppS6QQ
            YZld5+E3iq4OLuzl+jIpMRFDxxJDhI1ks2bKRIR1G1u2yP2uurJD0k9Hl+jkPDZU
            QLl2TSTnG11ImHNHx2szeF15403EeFCDI4vO7rlkv3MDk2amzmbzouFQ58O9I51e
            /qxiyfxbLb2BIJweZCrpY2ErhpzgabVO0dVh6UTSyXcXPffY+k7mUsG4TTKp40vk
            c+1nvnASyLHpq3McnkX8Nhk1OB1OgTMf4ngAtInqrASXcecdOV2dPmC+tdBt5g3i
            pAUs9QbIPBMU7lblid0e9L2x95dylJ15ibwpm/9BB8KXQzPakhsRbL7xM8ffFBkv
            //HgiewThgl0687StxQU2MI9XbTJlndvXbduFCh0aZN/8fuHlg5EKMpSKvEfcben
            3lUdMv2CiAccWDhUAYU+ZapkjBD4/h+o7zpr/BScBZZT3rFEtuQ07iRXzHNHrkQc
            oGy5obTbTOCYBu08lILCJiVOFzwwogvCKHQ6KcXZ8vMReWd4zmYkt+nifTgDYLtl
            T+JtzdKllL2aWxzUjBtXKgE+yZSf6V+Yis4qHlGaX3iwfLKbAYXZREupLTj9y/bS
            XgFlzx5ruL/h55OBNEM/mYB8C7cFH1Nf/+easKfzUkq0O38fyT+Ngr2eGcA2OJvR
            O5a6z1h+i2iwl9puYH1mDTM+vlEJkFrZvI5iUqc9+zjTZbMh4lxVV82kIbz46E0=
            =PAP4
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
