domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
            data:
                count: ENC[AES256_GCM,data:DA==,iv:UmBNOPezTPzBLpzQBNgINN9a9ktVBTQgExYBHRm3K+Q=,tag:LnAMDi+xLJFgvEiVObiklg==,type:int]
                persistence:
                    size: ENC[AES256_GCM,data:EMHa,iv:ZuvxabJl9EZA8Tbq2Jf3h1m07tasvADTbMs1we4xnyM=,tag:I6kZDCwV8Uf8yeD+7BS7uA==,type:str]
                resources:
                    limits: {}
                    requests:
                        cpu: ENC[AES256_GCM,data:Ad2m,iv:DZM4u2vpCYlvwL4jilxi4QL5SOdiT2UEGPCRgVVWLmg=,tag:OHkP/vuZo0FWzU4GlIdVJA==,type:float]
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    gateways:
        public:
            tls: null
            stringData:
                key: ENC[AES256_GCM,data:6NXRhDDdcC+W/nFstrcilCRPlYPJjhgjsZ529ouEZYd8lQXeXF3p85R9Lmrb/4Gaji8FL8dUNeIJnIxT28u5+6O3qDXxnJet4za2BOPTZTXV1cj1NA+sVQ7tqOxOKb4xFsY7SwpsqtE/Sdq5KLbbc7jnyzvq/OrTsJwMOu57dqEueRefyxnXjqp/K3GeGydf3s7wf5962DIVrW0MsSA/4Q9zeoxZuVSTiDMKgodMNxi7oSr1LrrOkyyoZoEk8YwHjDPdUhIJEDGB8g2dgz6btI3KrupsSZZY+RF5kcXchRNTmHc7iB/odhhxxiEar010npyN3d5bauO9e+BJ+Sen5HHhZVf51mTLRXNzgu6vXUMFWB6MgNHgtR03E9ypM6iRfY+zpb4Owj0g4nwnOVYNlQmPRK429RjVhhi6HZ9wEtAct0i+jZaPzXLswcbRzlUtCPCkKLpAAsNg17nCwKpQ/ShhENp46HZPpq2HBw6WWyK0Ytp2lhxx+MKI6flU95cMqKHiFbyOp3gkjg1AN6K65JkR6/Nw2/rcwP0E6D22DU7D2sVbGZ0gKM/JvkbpWI1gmuUpGmfbBnp9tQ7HCZDCesiTNias+ZoGaXiD+ztgi+e0xmNmGu+VULLuhzhxmZSR6OQVR5Cugt9JTM80NrdLccUYLvmnKyJrvG8H8g7tg9ZHq5YGYhBCOlJ1XwmpN+LTSVAr16ewH/zGKXyaTzIOsYWU3Vt56f/WewsLG+Jd/7A8NhltYGRw/qRYxmHDFMB/nwxgUjnS5tsLqBishbrjmLZU/06QfuWDjtEkQG/GlzFfdsiBh/7RBggyBI0oEAjWZEoENmDJHbVjtK78ZWF+kKJshXelf961GcSpe3NJ3zDnSmo0hgy6vBtbTA9AKmLoWTIf3lQ2CBx+Dlut4iu41rxAkFLTzoGgKkw4QWeL6jd8TWYmFr3iAvs/2cuSObXe1vhKOGYK0EB/sBcuXAu/fbjtV6ta6f/Y64IxfNy37xBE/6fuYYaiCt34L0yrrortBX1Xt930cX9QFSazDqlfauF2Gj+p3gd4xyZNK6u7keqZ4xqQKOa5BHR85h0SVs4zWx3aa3Q3vmzwxs7XIx7yMtX05aVuhF42zw471GH7J9UED2pN77QuDngmlZXvPFiU3KzHe+lJl2AqIUhAdtQsIrUH796sBhBnetivZrr11SxbRWGZ+TmL1/PesqgtNnNIjYwN2j+wiencJUKbZjLDQiKT0nMarhF1mf0S/R/gxOZLKaFIffaBWiPUoVgzoI7X3CeZwvGurBoTQ9oO/Q51k6tHp6dZStn8OXMaQTzGiwoKKpOBHIxFPlZWpCnbK+KdpXgdAOE5ll7J0z9f3unh28SZ0UivjoRFunZtHOmGryGEA0kK0srier3Hnaz0quKT0nICof6XEo+ZKk32ScliTRN8PhMBr1H15DFo/dYLHBEowDSWmpLKYCYid50Wu7685POpS9lEMOQr1uRNs1XSr4Tztbuhou+pzLldKZ29n47mUrVZCaSealEYyE+UnJOOp5njqwyeFn9StxzkTIdL/7gmgRrL8bGbeyXEvMsQIziSluLE2rN7pt//lDCdQ21EguLKV9yUzHLPx14MckUaYMSY3l0eyZ8mUkdP3nGEHHxXjs6ynSrjV9HlLMKYQclFV0Jmc19n/Htf3AtQO6jHLswFvpGF5iZRIlzyN4E12J281cMT30k6US0ju1G+3AftAxTiUOJ8b0ZpyzSO2BfWr6nH2RvOX3m9yoxgx3O9cXVHfjSJHILrNLGVPvKnB0btdc00CS4NcB6zMWWmhwhcoDybFa3TTfTfzJ2c6bn/XRW+Kp4rHKcR6hq2W9eHb+es1K6tL1eheIBB/Q4IbWmEu5BOzRPmbnXVHWA5SWzCUYZ26rmd8oJvLrdJcKPFvxzdXGKxOQI7qNhk1PfyoqXQD+ONdoSvgUMW76DzEav0PYu40bqUG/aDY3CR62IMpNlge/jC+2g08y/p4DFAv3yP/zVHR6VwxNzPnFMObzghbF4y/sRLvxCts5+3exWxaZtZf42hFMbdClV0NXRKvlsow/18r9VDYlu9csqqPokiPvyyhDe1lAdeVOBhD3LgUmOW7HatxRHvpZKmrIIOwa9ZYUlKFiF+kBGblnDAP2ssfao+7s24IplK3llsrvJdsy1AyIf/KeG+d7IL3jTD767Zad4YSpdBo9BcvmIWMwRERfjvEA9t2kKHbA17Q43J+pagtIrprfXuZkn+kHXJBZ3XbXvFrAr4weZwdVJt6gmIdTAXiQda/9pJcaUuXg4poMtQKX+iszJzQK7UabbojwBbaRGt3+CQCxrHPm+m/eOHB4Ar2wkRjdG6gbmthz75IB8E26o/4+sS/8kZapFyIVunaafxgpTI726az4AzTSNXGN6tUemde7FJi8KhF0oOp5S0FEdWlSPPuoCkDXspDM/VCMjb/udE4eJnjiIf6ijPRTeWxAouHhGNtH3UnESnlRBAtsTdB1kPvankOWZKFlkx2AlKRkdCMSfstC0sy5xVhzDZl/WEGr7L4Nu/vVyDlsxjszBFGRF7FnF88Hk5Tt1d1a0Xq4YCXRmblw38q19lJEG5+ggR6vmJ7OGVJVxYP5UqGGBR1KK2ru9yfupeBxiL00nDAaoQjLUjB2tVDqPZcyV+ujR0aMovFh1aSslOV8gcuj8h7gQjOTltIGD0WFblciYkD60BmxxnLwSSwCslAeOA4i6f0P1CWX34gLXoDTof9NrxEI4T1HQB12vU0CPmNm6bWTzi0zqA2yfbZ2r4NGReKOF2QlDz+G/SWXv1lNR38ikBrU5lhPh9RYTOFX3Gx3m3hN0x5NfM1MCRZ3VKOzmv7RtWZYfp1cOxC7x3nDYvGyZLU9PG0av/b2NBBUPn1H2sWZNFMd/+HJeMcd2fEf07YSYQNNfwW67R9KUcPivEIn29EdMjt+yTTxp7SjQpXH5Z/K7wd+2cB9TnPLOSshA=,iv:8/NNkMK6Tf6+J/o//psFy4NoHF9IaB/qDnFlDMuuhcY=,tag:qmsOz+AniQi9vgwHYy59og==,type:str]
                cert: ENC[AES256_GCM,data:yubWinsmr+YM/8tA91kieyj16R0jm3ubFQAoHRUPC/ORug4VCb0h6RbJKF9YUaA8gCX7XRXmYbK64oZc+o36h4FYjHTsOYpPlKa+fpXdBt3bnqEVqVJiw90YicvMJMZs7d6aGhAfAg9gSHRTwzebp8+Gp+yUe1pisLQTzLRZIWyTGJAhXt6qvx4AHMNJRxaXBW2srRZnjzoQKF7OqjyhTKGGrAoy4xpcuqpYFa8QphMZtLwDla8xATHOQuuRYixu/zvfqwr+VcRbcC29YVwkLplTB+6pFGOFt9Vrb54iEb6UkljP2uDT5BDb7SrymMod19/UR9AF+FNgcGFYdlFnbJtqtRd1zOK8zq2J729V4donhhgWfcpfMKRvLtfjIN4j7hZRQacKFhRVRDaTo1oiazRcWuHXJUNa/Ggzkz1wIXXovRBjXLhbuwNZfWIEj4iztGAHs15ubC502VR4rFKd611oo35gJ4CXQkxib+0Y4Smhjf+XLp2eGHJ8L/vbTwmi1apWMUC/0PyzMMrmcFamnv+UKmEz87D5XT/+iH7AffOuKQLd+qMXNdMY9Q/PZvel0kH7y6HEr20AjWbL6j2w3B/Cvz7TbozSr7Eu5fLJvUg4sY8YGCjfm+erlLGO5sehPDSBAuDKSGEYlKhwg+kKxU0csKhOHvpqJ5Pt49jefIdIn/Ce9nCDf7UI/N6xS8ASRo5Qnq86hGh4P2KZkvB3gPKjfMVJm+CnRLPrBq7Dv/1S6rJ2TI2uNv+IcDvmenyHrnjTA1mRE64HYMsTsPOQ2pPlufGi33Zcj63YfOsU+8UVBRfz1puTxg2Z6N2apUSq+9xSUfPIJOeYw1qCvJTHFyz+VTA1pchVIgavcNPz42RSJC3x9/t909zwMh6xgvOlRUBgxSbCKTITJpVV9nm+e4BXmS6AnFoBvim0GyL33V6I97OWFvIOhl00fXhYm5AXnZMnq0nNNXtYsbWcGB135+TM7/QHJUOQbA5XOKSMWObnCzOeTHX22PHJXBNulbjrUQY7ipt6MrtcdhqVWE1YKhgxQBRO5yiUOqYgS1T/1NYi50HmNtNwwfilQOAfPikyF0fPKO1S9e1cai/TjWJYoxEnfbazqj4lKvMDSlnHdEG9+fAmni+Zx8bRAljEzoaMdXUQzxOh4wmru2smhabnD3SQoksS7skhdh27dvbWz31/g/d+/Xx3oDWkup5T0mKWx0Q2x8xQBUhv6SAxnb3Ts1JWe4hjeYjz5p9F8HVuaoY47nuW0hoYiMe8DoXcwdgFZRJKFP5evqd8vruFJ8t4z4DYsXRwmETgPAvsLsR57lUNaoGBE2LQQoRvW6wCwEosGUH3NPCPBlgeKqtbKAcWl/sLNZkHfhhyYnBYhu8XR5UDofV2nPssrtgaaxV68Ohlc2HZGCwoPn50f1MllSfAxZiH3BRzMby1RLqpw6EIg7LIa90zmM3HhuonS7juezU8vaNCyUOeTtgZZo7h0Q/8jIz5jq9MCWjJT0S5diJL1Thf+53dZv7/neh+htMVDZOpE/W7solJklzg0p+kc2Wjpjab60d4CptlwxzXq7Fl2BDg2M7YrNKuIh4thckHRd5NNbea9emtGbMz7HWDznoiTGFDdToMUZdtUwICEMMekDv0IekhWyvQt1s4fJhM3jvLqkSmTUcsIEHGjSv1RqRQLCZKKUCovgIPVlu9snY+HDsL2I5+QNggKTUAmztoUu1R2z1rvAv+52olx4dtyZT7lK0dvuf9QqY/yqr0u4G+tfhAuXfZuWNg8sUZjDGiyEoT8fxAy7FvpV0h/+f08ZoFGbpGrCgQUpC+JP5rVWKld58/zSkgi9VzMq9wmms2+BTvD8nIoGg1wcQZ4OaX+RH4CBV77Z3dZaH4/NnSA5ckkx4aACbm+tzNkeEFxy8aJnCTtOgdjjmyJxmskhJKqJbAHO1XMFCWD6953dyX56oLeubzsF8a+ACdgybx56kRxkuAs6hrHgLYATYFnHYB3uWWjenTP0XEc5XCggP+dduNn9ZlrZwXVZi0CiUNffqe4W1NGmd7ON1oDPBz/U1bMoCR2f4Y/67TlTHwXhL7vzQ4yUBNkNUFXDztxWimXZwyMQPDJaDqtRaOBQ+rthE246sjGINZ5sWAWT7XCtP5u2k3ofOTbo9Ub5BNGWErnnFg/m2ZGK+XVbJ+ehjfs3P47saVJzX4vJlm17Svc73xz9kyv0Fl8SSda8gRAGEuonm4HZQP/Vya15Nj6qkDQfCqk12+WTZs0vw6Rpge2Kk7SvN+zQ+d9+79g4V/QGqnLO6AU0YRtt0oI5DI3cCY0sTktjzl0XfDlaI=,iv:xb9X0kLRFtDeqSwhSTXvvwH0eVExXwLXW+JJd2wPVWA=,tag:mtCoBPA8Ir6hpv4u8CqJlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T20:50:04Z"
    mac: ENC[AES256_GCM,data:VEhCBct1w6UEu61YqskaL06Olph7ljCKo9sSs5jXAKB3HzzJ9fHr0jwe1GtmAr2ktKz7gVud9jyWZuhC6TL8Q7G0QjYID5DsMALnGpyzOYNm5/nX4tPt7nO3k+Nm1kJbEp1Olv9FoohR8WEH+UlH99bn6uTH38ynjaQPE1uBtmg=,iv:jngVai/UkEPi6bAB9mMupIzOgj7oIacme9RtJzZ8Tao=,tag:5VkpexJcOTeyUcrd2ajv8g==,type:str]
    pgp:
        - created_at: "2022-03-24T20:50:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ/+IC4YYPUzj5V4VK0QtF6gA5oy7krAi7t1Q0N8brT+DTHg
            abCJSr82RFWcyCj+R/O6LiJC33tyLsuvaYv51SSKB0LtUomNVkN61XPWTr2j63cO
            c5kDf/CbcQhAM3pyx+zGmcbQG4c4RpPG3kKD2wC4fw2inmSCeiYUFzDUNlpX8ZDP
            AUW4ydvE4LWObFQrZChRZpbM9BbsTk47GaAZcOy7TTFD1dfsIpnRXGV9WhSDQJ8U
            c6H5v1menuWrdQbAvI8nDEKZRgI4obhe7xR3DQ3XhLnLiRJ81oJjDRxBvmfcoFrC
            bGdCgoYF8siJnFggMr6K/T7VwubxAyZHtOqSJQ+ykMG/N66b/RxHcjBBYxS6w5ew
            uX754hfQqe1dgF4ffl6G3A4ZW4pbCERdrngvEBYhvUW3NphvZRzn3m5YJLg98u77
            aCVOMQ5hYl+p6nWzF6dVnbJI3b4OulAHoUzSZSDmKFF1cCD5B8pcyZuEMiazn/Bm
            Etcp3Y1j3UbY3VQnChtrgp+jcHU7aYyyYFjAH/jE3oBDaDgMqBbuhntJX/x0hkiY
            411zmy0hg509onHINTBK9E5LsHmYWZSNuE9ermoJcklU/EOem5isO24yEkPijTTd
            JpR279AbJ2IebhVJKNBH2LZzGEhh8eX2/O4IX5ydX4LDnmPClxTiO7/Kx/5CL07S
            XAG/KxM/hj5HD05//RaDoD5B/7jCGNj8ADUbg06UdNs1ZHZy13yyoR4g/pQ9m8an
            D9StpN4gYX8sHlhnZ9bemh0KQtzXRNnZjxLLhFZpSZoN2XOP+Ht6U/HloF6m
            =tXmx
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
