domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
            data:
                count: ENC[AES256_GCM,data:NA==,iv:qDAf4F8Aloct4m3skOaaWwlbfjPxNuNIBBRuaK+Pr48=,tag:vccaeprnQv6VD2pOeMW+pQ==,type:int]
                persistence:
                    size: ENC[AES256_GCM,data:37lO,iv:1n+r09pQVf3M/m948wLH0VmsPsfCXDbZDB8kDNCsRrA=,tag:YZxlYz5J9yH0RFETvqutaA==,type:str]
                resources:
                    limits: {}
                    requests:
                        cpu: ENC[AES256_GCM,data:TcBe,iv:qIm0Gt2UaSZ/IB/ZXYghzPruH7XEqFr5aOkgx2FY9ys=,tag:7PpFM3jHRx3m9hnoZmbsOQ==,type:float]
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    gateways:
        public:
            tls: null
            type: kubernetes.io/tls
            data:
                key:
                    tls.key: ENC[AES256_GCM,data:g8tmmZKRWMg2Q3xPlZrIscWUvAJMgPAzfvRENl03QP4Zeo49IFuwPwasj+EwfRkVMAijVV0gdEzobP4VcE+7eNr8rvs1ZdmtHlKurOTyKofGPb4UZaZtNgOdOnynXdQCusm3fJcsDXfvU2ATrE4lZ9oZ5V9DpUDD39jLy/N2jbGZjt/X8ONZbefvU7JAtd2rzKRY0SIYNa/RfBpuSrbTK4hg96VAsZtnuco75btPPV4EvDzuR05uGQ5bQPGNLGn1q+Wx3s1syeuq5xQAkF2asd1v13l8PHU9FVzTWElSQKPz5RJ3h0oR3/zfW8YI3wNvTpwZlirZHv/i4D/wBskoZP5gojEwqtYTsoL55MCS7wqYVLaVKpou9Ds5eFDwcbQQo+wyiSj0eqeCtU/Y3kYhHd3AWMcjkMVPWyU6PY6amYMiqfh0rKXs5CnP8pMTWbQe8DAx4HmHDsap2LjXlxEkPCmDYHTEXT3L0fAe0xkA12Qc52l7iObEp3G72dFGIIfgYro6IMbwfBRq9ibEQRM6dnmN9uBUxdLR8F8M2YQDLfFLMiFidMTKypXsHO/SnqFqaDjHImX8fS+ZmLgsA9pnCJwKYx9pJz2Nuy3OJVKL80a8OZKNmRguwEDTxmFLIYlP4PFcJIQC3bhV0D7lTfTk1Bt2Ydy0hipuNzJdHo+zDKIxT4P22pXlF1i19dilwQSUGVNdczU+Hge2CuTaHrSgZ99La2inCUPxTM9KISAosKnF7LRrQeEuZ+lJpeP5Md3YvPa7okKeIJjRPwQc32qAQvvISneMRKsxAEII4a4tOTmPr8yVLhYWTv8duts8HaGIFibD/K4rf2MDGAjBdg4kXiRZP0ifVrkaBmHJoLlKj8PDwfxN7iccEgTNMkNzVBwfaI92IP8aced6tUEt7+MVsbj9VSQqSS6m8ks+pFZB28DXwfZCcDRU1KcuHTPnLSZ5u8YuyxrZiqtOTd96eisCSkh+D5rsmdBUFVGRkvLIWcjJzgZnJy6hjVdNgUfiRIerI2HgrQnyXOevzexiKpMPW14MQQjuv2PVtnvV1EOaCZ5GsNBhaIAKAg7Apq9oj3NlxGo7IINVp1Y9TEr8G0M/4AVkIaEQYTJPSGAMJp7PHtbBJemAq/BgWSA/0qffp7U1tA6WCtkiYjPXWgnAAFYRwNA2U/T21wAmy03XJRg/8KMbvse4GYGCNBEtCPmqbPwjnTMDIZaAbKNfJKlFEmWoJ7Ypm0/EDce2jtGA+utU/M4AFJNfbcxQ4oZoyuUIS6OZUunX4X5PYwlmvFkmy4hvHCBvqbOhVqH0P7XwP55ZxpPOpttFYP8C2T7ZeAEnXloU2d3xGXrQ0bdsbsBNbEi7NwirGaDYwJkHTgibuZfVTefd83Lp2e6Tl+yCc3ehQXDgg/GqBodwSGlrVYQzNqGZR5cPChzL9nOqvCS8byCy3tUhU8tyE56bm6iUaQQdUVOZMmmbGE+N9tA8/fib3FhnvekTWEPIcknGH/3iNXzi2YszWBymA/o1V9FgLbZcidHdJLQANnGDKHS5O4wCv47e2t8BZNr5tM4cDfjJs4KkmeRDZU3tlIJq1RFnGMZRpoWVrnKDMUrvFhNHh7j8VlmJupoaWXsqJ1QAxoGHp7ok3cRONrRLp4jpdtNanEXWozYZOkTHOKT8ZL7Tn9FTAZnIqAllNYyIrxptRchcWVfeFbFQlkB8saa5rNN0CksBGdoVvwtUimZzJW+IA0rOIAnYNk2fIBi03rpEm0sSRl0P1kd3NImd3/wm8B01qMQGMvUunkQWtGlCnFMDBWJ2fMByLEAL/YzwVf20NAVZeC+Jx8/ix8tK/4qBuknxVJINrVVJcXzyJVsYYCecZ+Z6pw9DpvW4c6ROV2K++eJHIAMSKp8UBAFMPOWTqMwX31EmWdSS38G+LeFerSklyiRwx+ysHq7Gs0IEcuGc9azfyalLZgsmJ8RnzBBl3MVO4lqDU7GMipPIgRnTNruEL6ng8OQSQRXKQqizK5FKgz9tIAmm2LvQZ47zNCbPz1w4f2eb2NADfoP3t3q0ItWN6oeNm4AIBDqbuSk1QuMecZJWr6GLk5MnHeOYkyuHbgP/aiFjAkrXzA+vAKVcnV0NQIKtQAYahGJCEvzK/oS6N8O4Dsb0zx2iz20KjMg1+wsJ1x7HN1e8oR007EPdLFkxOY60Sy1uXfHHj24tbWHUI4bkdJdPJXzfgcwvUqAyLjWz/Ei3wDh8n4LLaxberGhRvRiiYMw93RUdDJsG1e1Ay2DNAPSq9/hJQp1qz4LGlllnZG6oBouTFi54KdMYUi1EG078sB2/BkjW1roNR15GylnQkdSsZmykmn7dETv3tMczgScT4EyxGHT3Qz/sHp6yvfCwsz3umJJix/IgxuOfSxavcV82BF30cWTBa2nob4DK0t86QaokJcl+frfnGL1BawYVY2MSSnotV/jl81z7oe49ex+o6Kiwr1nJfefzJcDeWq0Q4phlR8h7rpZ9gkjJ5TY613YVW5F9cKIgGys3Dr7IJG9BhMPxjHDF/H8NAMKHK9pKCrD39kLNnQwYP7eqjjqDCSRGm5EuGNojT7dtLE6x1DX9euLYa0tCu88BzfmixObcBOtWw1BOx6HCbK3hDoBgolLxuGuXNwpbhFiXWWSSwF+PhSIiphdhYS/8cfI1CA/M/lc9LCB3SvtW0dQwGckJBDktD0OmfIgP3q44rkIh5fLKMjzlCRjdN2fBd61dpqyP1hwCkVdiI9unbsFSSCYkmrhC1TnIzkNvJJE65GxoROk2yA7Zu1wVhBU2tRdbEfXZau+xvkBs+Jdp1lDRdLwfwqms0F6gRHoaOZb3wTeDmeQlMqvHKNjrlrfVhjeKB8k8bynri4+rpg26JkjPYp3rIG8xyDP2p3eLNcnwsqn4xhJTc56aJOsn8gI7pbOIZx9PArayl2JZmE2SX2hHmUv2Rrovd6keyOROhGM28a4OlMdKDOo=,iv:HjUWhcClQPA41tafLA7mQalf5R3uQodpqhkKcmDSOBY=,tag:3FGGkECQI5iZI9W555/Dlw==,type:str]
                cert:
                    tls.crt: ENC[AES256_GCM,data:5jw37t7XG++eAlvSwHF+zaXcaAJ8DcaYsZeeMpoNt63D59nl2TbljWtqGwSo4Fi+kSCqqMpI+l3nZsDYYR94ZYMQqWV2tEbZYTUJYoiHC+mE3Np2qIkx2DkvNx5xxQ8hS/d9irc/gRuUcTRbD4WbY93DcgnCqzcvM1R7lotMnsWDYZQ4U7FGRqjnj4BqUgdlpYj/U2RDngBaBy83jgx5tTSXqN/vzy24vwmlLs7ILdlZN5kIQzfq4/hvCvpy62ZRWPLShjO/dvdbM8kkoHnuklqulae6zVx8PBi46CjW1t9/pXkMCR3vVuEgYV7hU38DupFEYePnEOI77yN4hEcI4HPVDclYRHIVc98n9QKX34CP1Fr3QM2OkytLkQNZG/I/8SckM66C8JUHhWilF4JD5E2ei3Y5LxxvmSYXUCHx1zQi388UOCSJH79t8k26DIgjqdsTtcB1v6r++xwUmLKXvghxdCqm7MwnihPKNfaphpxpQ5Elt9uoHUJjLxfz+5ejS4+CFRTfXKF2SGcDwiW9+yQ3bJEyyu4QF4eOw3BNIAqeA5mob9A5TX3XSFaKhgSnEMw3ayQah3OectIMUMl4iIit3clVoZiunoV+juqNF/U2kDZJFRRJL7mxVTv6EjGHK0PG5Rl6tk8Z3rLUnDnq4CY7w9KStI8SxJauqbU+G7tcX3fsJL7nwxTMQy6CKPEpxNChbhgIxkViC1jl19V4SBMYHlRTNob5+CcwBfgjfIqFwJ5n74lIn2ZfHKZOGgKnD7eby/6wdBxI+359grv+7nUw8udsnEbqWwTbL9GkzzIpnRR/KtlVhRMUA9rXOyPiuI/D8+rTXzscUyjOrMgM54OpAPWrjKsyKMV8DC+YjI26RIip3B+LS1mDIovolkzNCsnqRK/AdoYwLY2UV5l3C6L6Tpd5lPHqim1bRf2ngGFO7VCmhZF/olzIi3EbJd8Q6VMO74xsLKDZSMR1n6Zip8K0nC/ITEENU3q4ile/Ey7RzgQdSulgQIHvrADy+Fn4lP+zNhNACmV5nmpzTOhUcc/nJhW38AYQ3OilluR5a98W1YTdBbq8CayffnmrovPlAr+wSJ7TC274G/9TgjZpTIKEZiML9ZI7cxx0UPFQzzcCHlHGZKzjCg7DzRerA54c3EHMs3OxbOl+jnebfZQlESl52lnXLj9ZYDCboLMqqtr7HRU0mpNY95sLJIM4JslNNEyZOrWweZNSvmNxHLrBT3SoMhzwjVPSpy2rh0DV1kZpTYBcQWtzGPHigmgcatqIHeixRksZxWAPyvtWI72oHBEY1l4R01nnzxPqOR3wdvbR5j3t8ZkOWibYMFYZ1BpSq2MJdVWyH+ZV0wam4K/O70E6DsXhn6L+6hsiVJzcto92TCRQvKZyg/Q6QBRAfwVaJkFAx8047xFszdWiJIXsT1oPQQ8XmtK1bFjJb7OA9RbjCmeDzCrDGUGdbPI0czc9xAUrO1vbeuoGbtU5cK+8uw7kd4TRCdPfGpE6xr7UDCpc1riJ/XnkW5aQuAI/QEcmcWKhUsmE4j9j5EhfQRU0nQaoh1BLmDaEanefLWj9UicIurTmPmm13YlGcugjqgwYaG25Sqil4UgjBiKdP/5v9tiwDkJVs2sOm6oeuRUNW3BVpgctyRAtlQ7OWtih/WKBMCfdRnneeI/09BfcXhBpppjUnw2wkpD4E0DCsIKFe7n92luRp1feJdHLiqotKhJd22WB44Bl8Nf2Lz25dp8ENp8OTbrp0RW3H915GMPQMaLibk/HxKFVyLtrOtS4WVbiS3kTMHmnEbqcb1GmQK9/zDU3PIOXcqgxJXj/9PadFF7u9lh55jYRFrNpfAbF+6kCUKtuox9yowS/wcaazsTr74I0gihd0rQDowJjETjYondNFOW1hQeuneGrQJ2/8h688ocQS6qtfFvsX3VqQgpYBomwXSwVzrxMyeVb7Gd/MiLK9vCjhEbAKEkpC2yfW1NK7qOk/SxxEPcSrnHeRkUZ4nDT0YhiEtoO2aBSZy9Nzo8cuAZ4j7MDaOjRYEI5H+3xEjX2iyGUVKhfZLWPjpMfpB/64Xt4d9kXuVu6CUkOT1vQRCFRsshOPWqjR1iKd6TVb92pBzg6G1DfLnPTwfAa4qlrltZUaFVkxngw0x4jEBX1NOC/po5ggTdeIfmXsiiPEaOXkiPGn+ttPxzSB4Q5FjGbveTTFBHLIfScRYBfiKGm8POoIkWKx03xZGyH4LpkiL48iIrJbDzDusJcCd40be/gDT5zJaQUre2NfewmLeeQmRAKUHYdebZwOyLzUTHl1NPjQt++UOSCaO9fSRrV/98EiM8=,iv:ag2VLnr8Nv+hBO67kEq1lnm92eGPdP2i0omJ/EWCZgo=,tag:7hPuRym8C9ulXvcAzgPsAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T21:48:00Z"
    mac: ENC[AES256_GCM,data:dJgSdAIAqRXCfb8vddsDebu8Ugu3fURGQvfRPBpWkAQoW6KGLSI6BLMpDVCCdO89dXbsy5ygp+eudi5cgjMcIbxgVN8KPnLUGdf1WrrH/RjQWPUsYG70H/cay6sIKyRjkLnSJwGvcGs0wePlw3K2hBREv1jWx/kxi/jsnoIIPcg=,iv:cUi8xmswF+g/4DfIkIgzh0kdw2JvoTCVmd+WAg/H5Ag=,tag:SHPErAkw7yM1MakcRIYqYA==,type:str]
    pgp:
        - created_at: "2022-03-24T21:47:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ/+O1FLHc5zAW4d50uL30hbGIN3VdLmwYEF7vX3qIJzWiQ+
            W3G4N2OCruow6MwZh4K8FLO7FFpwaghR/LtlE9UInBQUE9qJE9HB2PshRroERxvr
            0rFtv8igYXF04to8FWE0EPlcKSef8hQgSKEv1StE+oY4KPuGtZmC867zVeJDjXAk
            CI3HxwGagr8VxVZhhrjkVEU61ijMgXAf0rpbrN2aZR8MlzMBWGEgJksmngZDHZa6
            84Nf9VUwnwyHm4HoE+G2CuvcXOwtIbEGyoI/AN1E5KLkTspRFc2tTpnsdXi2M/Qc
            XEE/HrdDK0QrtrbCtfb0cWARQlzMT+dqCPwkW7QL7khFpKspZOYPeRwTZNCC5+Hd
            9r31Fo8voHtRYnnWuOs5ch7xJsY/7SYuh6pcy9SG4FY+lmlrklfasLfUwUzE9wFZ
            M2La2CDrQxO+xG6BOu9lUKdHowh5URxTbKRTe9c7jYePHWbPfU10HbYo+tC9jIWs
            CrpFwxJK3MhLh5HhWCQr6WadKqOhxa/137PLkYhq8oBnECFB7eaN4Vgeen0l5LRq
            rURK0P//jAAQcDKhypQkAARtihrid40gd16mQcibv7c73hgWN5FieytJd1uQ8pDu
            OvO7jAAj9lOH6iIQFCdtQWgotxlUa/ZWUSclQ1rUTz5WE56c2fh2Hw+OqX1z5hvS
            XgHEsM223gIYwphhOHIV4iNTdSL91iW3KB0ze5aznftrABWrYLv2G7Ai3FbqZxqe
            MXxKXltQd9rPVt7zLWc12X1mjkaqYOhvhCh6ewe/OxrvtJuvNZDI8l9szi/57HU=
            =UNIc
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
