domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
            data:
                count: ENC[AES256_GCM,data:Hg==,iv:8oRXs/7DUwOvHVd30jAN3nmSbIfQUzpuzfHq/OMcji0=,tag:8vp9o51wnMMi+reCaS4QkQ==,type:int]
                persistence:
                    size: ENC[AES256_GCM,data:G6ap,iv:vQpYrgP3quTpdnmGNYNWC2geQUCyB7auTelDRe0eguQ=,tag:i0+oFnAG9bM43oRHySDRhA==,type:str]
                resources:
                    limits: {}
                    requests:
                        cpu: ENC[AES256_GCM,data:VbJj,iv:PJ50eLUus3QVHCjQNf89fEjMYNsqCQS1bcdv8DSQcsQ=,tag:igOaHztwjdCeScPl1FZ+6A==,type:float]
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    gateways:
        public:
            tls: null
            stringData:
                key:
                    tls.key: ENC[AES256_GCM,data:LU05hFrNAMKcavEQefFQNELBtYCt8TNQJsRq546Qd0ovjWGuwZQXtlDj9BEt8B+HJQ/G2w0iqjWW/N9zT+JqkcUNDV85oXE82i+bxPdVQsyrc4o/VBnFqOUaQTwxOdxLEFZZDfMeE2sEXKfwnSIf3aVLlVh6SMDrOcgJzu2Y9f3PM/4HXblCIkA/Ze72NBxg0MWKih6eiqNlLEO4DoFOWuGlV0r9owum1oJ2AV+UkqXz120vk7qB2Y/qRDWSQt0Z0MZzk352W3sd63d0qkA/S9MD8USZInaGuXdeFYwMhnXuDoXktaBXVDyla+nzKAF31ntO2Ammdo3ONmgvSE9GXJm4gEYdekRtl5y4jbyEDLfGiztZLQwY9KlDAPgBGheJEtAA0lkmSqINQZyaEK+oqp0uiTGaR8nRrN0X+Mfkee6zDbOMWrol8U/FSrjMFWqNGCQ9R2YrMsktVAD70aA2CvzOoxTNLdMWVmCYYjZJM0hohyJfXQrKi/4b8iPdrFcaaCB2YhiK6l4VHJK6j64zBMeTLK65d20U+0wYCkJEYOecMPQ7weLP9ChAb0iAkbxriL7JtslNNwwPegd94IwdutomEnsxVSB9CRa1kiiBXqbnWq3azuU8SOl4EJP2yv73UXGG2yIhd7+Jv3RCzelrVyfRYLaApF6SfeQCMzVJEgFBwbwc+2ZczPrrpURBcGyPfNqQKf2TsW8tc8dfGjvyNGJZrZTRMK2CJrifDvRHdtDVN+zwzCnt5E3+Q2DvuTzVKd6ZBm26Hhif/AxW00E5oJpgB/WsAD1AlY/mLGlkuKpQirv51034OGKEcLf6Zg47vSpVVhgfKZjwz6ZUYxRW43kZXdEC6EPfTgggrUv7BTAavpteGBSzhsesiWSSm5nB4gac0qZKUTkrt97hbqu/zcca/YFbKhZemTL7SVJvgBclGMpnGA9lG3q8mZ7C30TJViczLo0+lHYxVXRoz1Dc5lZqEEFu635J2LAn5NxjrlTnMBhRlZHFxhePj8xxpTlKpvz8QnL5U1Q/mVV6LD6jxSr5U02LyMIN5Es5Ff3bl7SabhP4YK6f0aAjz06O3TH3M3Ok85yVkxsN5q0zNiN1sdC/oK/KxO2v6JVNlwMldzc9QhhDluKWqBbPQhNq4aji3UgiPvVGQ+b2cJDkVwAdyM1zih1HC7n/Y6OR+p4ou05abHAOXzqa7w2OpP3rJXIlcgWlN5F7XBXyfLYH0Edojd1azDJ3r37nHj/h5tk/CI7zlu3ZmtJ/IgH6ea/qydOTeiqwH4CBzb4zrJzZPuCjsgdJKrP8m7V+gml6wu0dIPDss/l+2uYAYt3lmGzpvwUb800WLnP0X0PdISxK26jI9Nk9vEy+zM3oYCVptO8g/X3xugL9qfK1fZJ/onV7y8Cw7sxx9bRhmmxCB+J8FUdqON9WNXmaUne5nlsv24/ZUKThjIuxEAZshMgRcsd0lKwgoVF3wdYUIudLxSCOqT/fYzcoJMswL0qEX30EtVv7iQ/jgLyJsww5VDXOaMHnMuMzYHQQ32QMF/m7r3OYL5JmnB1xkTWIBQMFrXfS9xMIc+3njKOl7/HjX1of4vf8v54W5f2vIFmQgjK8zLlEGgfeF7k9bLLkWJt3/jUvBtt0nIL0PhaFfn97kYYMrL3MLE7c3EyNod8MBIkd9//6hcAIk333wIQ7feYJPBCLivLRJHiTmzGSzD7oO7GofRIOZdWpA39UAdKA06wYLvQ7sAmhMTqZKte6Wj3CuBIuGeMVX+nRGeHQ49Ob/Ybe4D3caxVQ+jwtJxZRdFdkuFnZ3XTPHUXvjyIZKwikDLGuGNVLLoBoRtE+Soo9bJ+G4yMSbhnpnwEfYxwvA24K1VgceQT/We7/bqZlyQnKfEhpFkrW3A+L0zcumrfOKcr0nL8665rwWXlRyELuBAmucIaL8pv3p1840t0xZYsDHMAsfzFZc/eC0j+ARRpa2zC86YjACQy/AJYL0t48qVWLFj8YtDrxV4+bPWjoJqOxvrf5Tzl4RO9kgQC/R/LaQZ4tVAeY6WLxF9/78gYct//LE5V3RF2MDPs9W5r0+mt0llrR4VtxdtxDZ87hbgC1HuE2lsP33GUnANX/rIccgiLOh8lr/Hq2XCRgcCajKxL5cV03KbbPF7SO/A6iHXle5YTlxf0YoykYxHCWkKYv8xXNIvkiBMY7VwxYZbxZgN+RUZEU2rlB43cqnBVFQ9W0dV/twUWaCjMT68+M4f3XXLSZjU8TkfsEUq8ay7/dYXl5apgZZ0YD5R47pyMB1SNFtffNlED2V8I/Qsz5KT58ENr5sNO1RVrlN5UjSwfyGBcp9SS0vRuJHhISoUs2n43txqcJqB6OOj/2EDxj4PCXF/P9NSKF+t4GBEOrMJAuCYJmy0yEIDI22G+J9L1fRBC1QuHeK4OFXYgWCqo2V/FzEz6KnslSPqSWzCNSzDQf/82Zl89khl30G99z4eOww6Tx4sxXnQrYd4Urhpkvt6HKcGxeSp2bv+eRb7Y9z8OzfJg42rbGsWEJ6fl6uUfk2hCnTCSJZBRuvg7u2M3ljBzROmCN+eXmivWJsCQhYA5fuFEG7ZmAtUO9yLbCMPdgY2M8vJpnS2Zx6VrdDx6bZK+n8j2KjdA2xhVQ3xyLmhPiK3FZAv9GrxYXNIImOhbBBrCv9G60fV/cgZ7NLN4KOQFmjnKRz72T2KfsKIcGwbbOQruXIA69gCVIfm/a/ATU8pLHAbWz35jJr0Qd0+HAchws4EbHYwc79vIibrEhlSQxt25XVLy7/X20eqTG5yytfhcviRlDL7851iatsoz+hOa8asNAw+3yrvQuoOH63iwnKd4XvHFHWUgpciaqCkfENp3MAQO7W0KOXz6h9qkr/2VW5MABzqCmbu2pRMxZnY/a8S5iu12NQDj2pUhBRhfpxpup5/BSbs2WIn4xN6u+9UQi26foWJsBLmNMsMLk5NuoKOYAwZQQhpZyCm4=,iv:oFt7ODs85qWkWud/78dLOVjW6kqHwQ287vWMHoPd2MI=,tag:GJIQS0S63gTIuUnwg6sO+A==,type:str]
                cert:
                    tls.crt: ENC[AES256_GCM,data:VP1vOqbDfCxaF8hhxXJEmXbHiBPSuujy4Du7xxvg/ck5IEEXGScqBmE8yD8e8VOz4BLcVjAUqmsc3JPjb8WlyMyA42qePWRTSz9Q+xqUnF7U9L05KNchVBlny273F6dOm1aTg0hSgqhX6oUhUm84Zud4TADUaQQHKbSeYalpmU8BkBxsxdJujDsEYq/n06LGz1cKmpIQG0kNIKpcLJFL8G5ZRJ5zK4OBBTrdXhrlEdiTIoT0/i3OeaurIwgZsRfp2Y8KJg5b8WKK2UWWPUc24CZ1XZAOIU5WHQTNR8AXZRn2sCv3c5Wlxcr038GNbdzg/K6vry1ouX/V3RO4TG4Q0oxxyEHA7gHbJ7+/MIfBRsysbYa3mquKwawiRksPUTw/UNEsK650Mw+BZH35pVxgWd6TQbsQgIy52U1PsVJvF5EK/5Lnl2+s9TyVltyL/VeSDHeFPsN1PwV+jw1BtA5Ns5SqbKUSp3yCAiwjiL1AenTDd2cokvoFMHMHIDASAG0E12VfwCYvaUna4OkEW7Bbfuh20fndaQezr4Sy1E+3gI1pkibJnCAQYK35PnsvGKOD8fHmK0O0R2a2RqCABpkWSMHSEXDKkIe3+Tu9sBgoc1ILaoF1s3zvwZp8Evo0kFCTzV42+M4V0QGNhuYpD0GBnuYmZk8g0aqZYhl04RBv8krFxllFszxNTbIkp/aqsj6l9VTczVI6g24HBQGZ//X2La7TKSO+q6LIJ2Vesanir6tlfzMYJekP6oG3KJJkDSA3l0aBLbWr9OyTWxSmcTOmzck+bWvEOnNJObOQp2EksXzeaiXnuThmX0WWIeHLkjRozmaWrA1QqKWxmcJR+u8pcIs67lPh5/OTYhgVh6LzP35RqHXaU5zAk+Pf/1bFUzB2xBmSn7gMIZ52yTdwbyl5qYR8KTw7RXK/bDrFLbTFOHUSnzpWHa/Km+VEFCf2D8X0W1gzVc5S9DROeIiGC5UuAl/WV2pMLpTU02UgXw5mC5CEWZdqbaJH2uMPgMBsrsFF/Yxlv01fByotjNLeSo96RY4fNk3ixxbcnq0L0CfxT17RfsRocubXSd6s6409FM/4i6Xg1lHDG88B3ddcTqJlG6HyTGI1/PZ3Mx4cArW7+Tm59cSWMITlgxoH8b1+D6mwtoKIERv711JHaXz/lnPEJ0v1/fAvy5ayiFrCrwyiWhYCRtPoYjb1fx813y9bVURTpQ1MJisuslEqqQmmaUoZq56oGfJ12qE1aBVakZhMzMY8lnI3v+3/zNIPjtbXggw9zek3mKeSCsKVBYmM5p4dyb4JgMOKOfWP5WiPeAJol0F/OYr3BQkimzE95ivyacJmL49+yNRbAHe/aWoxJqHOIX25OC9uqbLw+oojfixJrxAuFlnl2fumUdwUNNAEWKIEMLTcNu8Xq4LyjU8tN2I/C5EK2seNXFXZKpkw8vlh4D5uJ4ZJYRGwXs7kxdRUNrMmbNkZiXVx66MDFWzSfbfaGrvVPc620c7QVKMTepdvfFAS7wI8JaBFgbZf9IT7DsyAnIE2ILVJoAZyl8TnFDBf1VNC8Atsx1p5uqV6UjpF4c62BzWDnz73wYC4p4mT1ide/JumAx4X45/9LS/MsQM7NnpcpjzCAxNyl+/+JGYmBiL9IhHgPUWeD7iBj+bSy840P395I5/kHiiNbE4e++h5Hg0Y9Ku/JJxa+RlWqT366dN7A2xkONIbD8eIQb8tVIYyAtDl3W7SN7LeZ+LjOULGl8hgrKxgeblF41gkTAjqdnmpXeasAveOhoyKuax/rE33cVRoJpM7lHyEPl+4K/v4HKmfKU4aoARNdsuzIoz24RN7wBUkV2vpTp/g9tV0/73p0E70/bobsVPVk8RXInx75CXJbYzI6amIHh7P3MrmUPQ6O/Yq6G2qP9R+qhWnjfYiFtYadMoTLhZ0uB1g7VGeTtV7DfPFjaj5Xe0L1ToVRxzfXbufsgLO87lVy7YecY/euq3gUJ4S3mbS8WciKDg5iOidYcHQKvWn26cDWnXFGODtDjjitdXqlWLglzttgUQldtmbEYhy89ythi5PWosOzYmUdIU7n0GIT31u5iLnr8/sWGsg4Fghb5dwSDg2BXMpQGqlcNQX91xnP8emK4tT91nupXqVxD/XTPMtE6pwNXio+9vM2YjCDH8+TjLMJGC+QIObq2t1HpozXLz5PVcj+sqDktM7mntMY2XzHEo6DWCy2OcpNQ97AP66Yvfn859mBhHqfTDaVcDjwnN0WAx0S85xXnEsi/0p43eqK9IP3+wjCu3V9iMLwd/MfXYGnwBQ1Y0ccIAPxQ/KYMw0KiRjtA4eWU0=,iv:9DTzjSF8lVc+Hj6JcvFx4NLhbv5rMpo051C2rP77+dc=,tag:5q1W71WGtKjRY/gtpkm/Gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T20:47:08Z"
    mac: ENC[AES256_GCM,data:Xl20paKf+PuoKbducwes7Q2A9ouAj+QqX/RKWErT2AhOpplJ1RBuKZ4WIqSMbkreSIxBHA8iA8vu3utzjFBqUPP3jm4aT6x7LuDOZWOdFuYmFM6FbpCjilX4yARAB10870erz3xJXuoZPlxNVvDUY5EG4Hmp+lLlzah7OhD9JkA=,iv:wCRhRrO+OsOuxa/IrLcnp+tyTPIKa7StqKdNBT4f5X0=,tag:OEV5KPOvx6FYPoG5q2cZkw==,type:str]
    pgp:
        - created_at: "2022-03-24T20:47:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pARAAhKITB1ESvJ6aOwMl4C5vfJQfqJ1EfiX397+wYVy2YJWg
            m8YuiFdrf5cHaW3t5eAZj+cF0UXCD1c9vZCBnKnznFeFd6vCwIyFkhcIGJV//U8i
            J63YlK4GMyucwQTdgwHLOOXJz2CBqCYXyYW8gYhgDB0cdAGYkUD3rK25J3Oca25m
            7zputRDIr02faEt4hYP/yytJjYw7iCy2KG7CRg61k28KLDbG17wtoy0ZtYMUCzBZ
            WywT1MMj0OipXcDEhNU4/N0VrLgY5Y+aR0dcou75AzindxPiyPwPZSzRpAsWSMAH
            ldUBNIbEPowHqL6tCB6Be0k1hgBpLOFwop2I92dgKJwykz/btJpFXyMee/nP6DfQ
            CPbXlovnQNl4joPq5LIYfLvhK3tP6lJPQRRJrR86NJIXmIIjXBhL9fbv1PIKl4yw
            Wlui+Lm/m1X9iaBw9DlL2sgHXsbzjJiFAuhyVZpeoJL0qQ41G4i6k8LOYigqIdGb
            omR4imloFIQXSWo8UzDF9d5Kv3O9arshzZZ/u2NyWsTZmdezY005QaymlpVLgzih
            VRzWlEYaxhUISjhCPIQ9eCy2qGH5po6ZO21GfnUFyBbYjv4MwrnzEKYM5dg1rhON
            ApXXNxoCA2CElIy6XHMIBWVt5SeY4MQfKjloKRc3Z0r2a3jKav8zMbAwYOC+aLrS
            XgHT6FWmWwm05SWgx/+Cix9DwwOXx9QXxE2g0Kv123UHvAwl/qtgt0X60Iei3wdG
            E3P01UatBhCWM6gTvRmwlzSIDEjx7bSXKonFC6xB5rOGFiXWemgAjpvLrEoXV0w=
            =YYVB
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
