domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
            data:
                count: ENC[AES256_GCM,data:DQ==,iv:7yoMBVpV9QgcoLRdIorhH/wGISdItuyzSINXk+4X2aM=,tag:dLN1Xk/NMtG0MS0ULD5ehw==,type:int]
                persistence:
                    size: ENC[AES256_GCM,data:Xe3F,iv:kqK6PIwZnLFhM/vpRw4r96Ft1Zk3jfIrBZoSnw0WdRk=,tag:F2VsWWCa6UoW/HZHp69YSg==,type:str]
                resources:
                    limits: {}
                    requests:
                        cpu: ENC[AES256_GCM,data:ZJ8M,iv:jKfJz12l2cYwIJpbwf9m0StM/jVdASpJkHF1I8+STdc=,tag:xBNLoCXncR8UQSWH+Bk5Yw==,type:float]
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    gateways:
        public:
            tls:
                key: "-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAsiskQnYThabF/TyahcWzCdZnO/a5c2QyRuPeA8wQFH23XN3k\nFIqZIwbTA+GI/+PFnuWZElhgdQUZ0U4TAYWGuF+xtAp2mv4JaOjpAEFJtAnzQy5Y\nqA7qvWQcKQE5KmcNHNka0iJ/oH7X3OCz42wJepbm7x0MXXGSMfvkTw1bNTz2ogB3\n3GjqEwgueoPoY9r189OS6zRlSlCsdM8GI8x1rj9j+Nv2jXVpF86GrWQ+rDnE5iev\nv4lohWl+nmxFahsD62LzgEa+NDnGOuHymfnCeIrSDBTzt+uIjdhbfvS52XFFPt1L\naI3ckhJmzPcXy+T0Vl9g1lkPMCoXvmA8rJKD+QIDAQABAoIBAG570kBkeDao9J3U\ntv29Wwj+q4XDubyUpZjQNRylrlMGom40KvuR9uSBltkRQqNr22BtgD6gDzCBuUDR\n6XdIFgK/VLMQyfvTDILB67r8wXejs/Y1B0Uv+uD28396ArkIrlj1SGyGeB5Oig2u\nSd79X+NlME+W89P+WWolia572dNosSgDIvciAEY1HBkRUSsdCR1qDfW2GIR4AtpC\n6o6FGPp8o4AVlY8ITbzFozArPzhK2o5Oxf98CwFZJXMW0AHBntyZ2kMxE7+ssAZ9\ngD1/fsn4dLSd2Az6r3djRz3I3ysg/9X6m8S1Yo0Xoc918G6MXK4/dcDjONn90XSV\nrzP8wwECgYEA4yDNRnorEZIUiA+tLfXkVyBQoduZXiBZf5yEeDWqNn0l2MWntV+b\nHzXINskBU6FmvAhUxS1n2r52D0HO55xcQMj8pAcSdwOzi5NG6faXaWL9oOx8IyKM\nMl6opFW4/Pw9QaFLaxfocJ28d/uO422L0EhWCtYIFkjnZpNoutMCG+sCgYEAyNEY\n60WWMIpKg6g8Dk6hOhLjBWvmuwC9eomkBfV+Ub1CeeKeJYjGwZYcSLMceLohh7M7\nm3a0O/RHcum9mVCoYjAnEtFsK98V2mH6Inim6CSF8YuGMKqfDoLsZetzMKTC3JEb\ncKWaShMC/eQ0miKzx11HmOwAYb1kSG9Bdhj8GqsCgYEAkfWOdXAlJVF/KEEKxbJz\nXxpBNwLseHTJjxyCdM3n6MRcAgZjVEdwZIondC2QULI0VznzYBNh3kzvibZ8xJLT\nJj8DPFXfI+SZCWVH+Sqi+vLGkxfmXp3hAq2aKqF8E/f1VavVz6i5k0WKzIA4vyay\n5tLVmHkbEVcgfebVMtpPTKkCgYAEf4qLWpeupqpcoJwXxfMeleW37V7RuYaFBChE\naedWdWLT0Buyw4mQNIiVqE1u9txhacZgCRyoayRekpXIpWHgMSvu4/oEUY7vwVoV\nA5bZhFfrvTBYTroZXR1mewutf0NOJYHz2AHIvvxGK6JyAWz9fj1oU4D+r3tblAJn\nXs/m2QKBgQCh1lTy5Xxq2SpD8YMq+uBwPIe7tWEAH8gyCgPnsz1SCLaaUDFjGvsv\naohn60Ja82ftBpdGnoO7k33XK0Y9uKFfiotvOw9jZ17g5yxmhhFp+Kk1MYdaKznI\nI194DCff93Fd+ecfdRnM0t0XIByuNw8KJpcxDugcU7RkvigQwdWRNQ==\n-----END RSA PRIVATE KEY-----          "
                cert: "-----BEGIN CERTIFICATE-----\nMIIDmTCCAoGgAwIBAgIUfZKhLp/Z7uG9+1C2lcJ6UADy284wDQYJKoZIhvcNAQEL\nBQAwSjELMAkGA1UEBhMCVVMxGDAWBgNVBAoMD19EZXZlbG9wbWVudCBDQTEhMB8G\nA1UEAwwYRGV2ZWxvcG1lbnQgY2VydGlmaWNhdGVzMB4XDTIyMDMyNDE2NTgzOFoX\nDTIzMDMyNDE2NTgzOFowPzELMAkGA1UEBhMCVVMxGjAYBgNVBAoMEUxvY2FsIERl\ndmVsb3BtZW50MRQwEgYDVQQDDAtiaWdiYW5nLmRldjCCASIwDQYJKoZIhvcNAQEB\nBQADggEPADCCAQoCggEBALIrJEJ2E4Wmxf08moXFswnWZzv2uXNkMkbj3gPMEBR9\nt1zd5BSKmSMG0wPhiP/jxZ7lmRJYYHUFGdFOEwGFhrhfsbQKdpr+CWjo6QBBSbQJ\n80MuWKgO6r1kHCkBOSpnDRzZGtIif6B+19zgs+NsCXqW5u8dDF1xkjH75E8NWzU8\n9qIAd9xo6hMILnqD6GPa9fPTkus0ZUpQrHTPBiPMda4/Y/jb9o11aRfOhq1kPqw5\nxOYnr7+JaIVpfp5sRWobA+ti84BGvjQ5xjrh8pn5wniK0gwU87friI3YW370udlx\nRT7dS2iN3JISZsz3F8vk9FZfYNZZDzAqF75gPKySg/kCAwEAAaOBgTB/MB8GA1Ud\nIwQYMBaAFMLIewiE7nKrckiWn8s5PUXFQ0ViMAkGA1UdEwQCMAAwCwYDVR0PBAQD\nAgTwMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAlBgNVHREEHjAcggti\naWdiYW5nLmRldoINKi5iaWdiYW5nLmRldjANBgkqhkiG9w0BAQsFAAOCAQEAvdqV\nM9qmyi25O2n+V7i9gl/zx8BkTFI65an1FIuJerbWXe2p38z/Nwju9MlC5iJTJQqL\nHKSgoS+IhKXsj9mYqEx3Ojh6VYd8129qf4dB5Hwhnvgr/DBjELJFE2Q1quWw/N49\njYnpIeR6sOLI7/9TyoZglnKGFeR/sG500fIskMzLbdaPl0N6Po3NKQpQLSYISrsL\nuY54LnEFRkV6GxyP+BdqjO9zWOhw2iyHYkqWB0rrBL9jI2fD8Z48ud/UyeQUv5Kh\nymhSJo3wg1WKLacdmYmTdUqsddVgOTp/y9Rf5jR6Ec5qxwm46z3d8kuuNYX++Ttp\nBDLaeLKh6bmdRfSozw==\n-----END CERTIFICATE-----\n "
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T21:43:33Z"
    mac: ENC[AES256_GCM,data:vqqPnXlsyPr7vCALUvR+vbDmi3liSCxEk7NX8YhK1QWlIQypuV51XANdDyw/Csj+YDy+lGH8LIAXsEeL0/ohLgvHLi3yE9iP1xjQuLSCuWOclpC1c/IfFSy44FOorMqrrTa9ehTwJph+xVQB88B/rNyzlx+GpNLnVEvJxtH7yro=,iv:PknxQ+hfOnZZ+k874URWFDiXmm+ZYUhmCfUTxuCsbG8=,tag:9f0yCudeKW/dEUF+COI6Qw==,type:str]
    pgp:
        - created_at: "2022-03-24T21:43:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ/9EpRtwyF81dDpXYG9Qg7EbM170WmRwPrFaaAZ05Z1Ravg
            wsxT8Kh7+Fyt6mk/2nLO2X6fuH0/kLvHmOqsiWQaCtlPZF4R8U0nrvLCJ2cp6vsp
            1cfkGnAWdMAPtgpD5sPhLTZf+i1RCW5Y7rpS2xUJzSBCz2QPHoxJ/oAOm3ogVvtv
            Njas6ipeMFHYYTor4qoELYPqM3uy1Ub8S9oRZ4rbVwBQEdKhcyMhUH82+aA93UYE
            jmelj+2CynyKwNWRZOO2C3JTqLXAevt0SWRZ9YhUUbpDhhk/nqSb2AmiB17bxMFG
            owTEUkTCdu+cxsDJhorN4s9N2cg8nIWWOomSr1Jc+9AJ9MVI6UQPHSsOc1OeNKJU
            Pl2pOrBoJ1pcbf0nlai9joCN1bv8slR8isnl+eO4L2srtSoqNoRVupMBN+PVluC4
            NtIuBOQUeo4Kk56tTEVDpCXHfE0kd4s9Tp0CDMzXwHkToreObeNfJRIPktgmEijT
            Le3UfQT4m86UgVj+7KJ6+3oNlUyCiZ4RWqYfRatwQa73H1or6r9dzDpFHdJvo5UO
            NsVF1IkFpRNSotcY7y3/MidG8ojYOT+zRPGza94nKujbmBw0z2CXZQrxkLtzAIUv
            QqLhdBlI7hXUH6SgYy2Uqrk075vhfq+Tz3rvwwFB7Hhxkx+YNS9aHSPvuM9KrDHS
            XgFGxSI7Q4vQG9BeQGR7tE39EgboeviRIlEZVLbJ2Vg0JMg10tMrv3vN+fFtbw9e
            v90nIxbVOD60ONg9fjbNt4yyvsLPI4OqvEqrUazLz+c8u61PPbXIWRGjahsKj20=
            =3AJk
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
