domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
            data:
                count: ENC[AES256_GCM,data:ag==,iv:x6znYcZR1DJ/1qyTU6DjX/V5gg08OsO+IIA5ZDhqWCM=,tag:fURgZ1cwgjIduMI1e3icng==,type:int]
                persistence:
                    size: ENC[AES256_GCM,data:dpKn,iv:sZBmDjuxoAxrdeGBrS26WOVRnIj2xiJzZQW90SUw8EA=,tag:pUIDK1rH2/JecbJYnc0YHA==,type:str]
                resources:
                    limits: {}
                    requests:
                        cpu: ENC[AES256_GCM,data:TM+g,iv:k8eetfVINgCts3j5INYCz2YudHhb6zvgKkGDVzKV/rg=,tag:b728S4dTRFgA3TkJK/PtOg==,type:float]
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    gateways:
        public:
            tls:
                type: kubernetes.io/tls
                data:
                    tls.key: ENC[AES256_GCM,data:QHpl9kbTLBAwwR/3EqDeBxzZc2rFGNPHuFYHYcnL5lBuC+e8khg4TAWaRjp+HcXb7UqWNyZ/fjjPME1MD4c8NTXnPJOw2NRoujueDTgrC1BFK6uFJZ8gu8SqYHtYuKFX92rYnbqq45EvVXjh6rLSlA/wYF8SdH//fcc29ATeLqROUU/ZaxGI+7OclPis0p1oGaGakxVGGLxYJ0lF5HX2KAhMVzFfl8rwTGKnp+EFe6OsXC2XZNnYOizb9D58FaCtUN9SRkSG4tELN6fLJbocWf06BSIuFbn1umWXnfin7u49IxwkZ3tFXxVmm2lITpzefRQ48UNxegCGv8Veq/fj+oTZnX697NSNJhfmWNfa727XZvn0uMghOZ3YhtCs0X+bOJgzm4ymokqlxfMoX43bkNPw9qiVxIjjsOkBY90PgnSr01e7YhbRDqvT36HNxZVJkhxWTuj8wMNIGN05JjTn6zZ0vRDE97eSbVImbRCN+Fv70jj9jz6e81aaknR1SQUOLNX7vKh62Cl81Iavm2ICzsS4iVcux08btLO57zuhNo3PQRz5ATV52Fn+gN+Wj1P05epNySAhyJrslru7UQlGk4RbcmYBO6Ae635UeM8k9HAsZh6X0sJySzlkxm/3muAeCT1rMtWKvW5HDy05A2X39k7XGoWmIyYVrgdxxU3YFsUKWf9uJT2RCz0BGuIWVOwCO09eXrK2zbrAtYLa7rrCYMo/W8fHSCHX/maDTfCAq31r14goBuM4qMZyaqlFN4qFFXAoAsDRzWFMpWubh/D/u7cxaM2fkwy9Abmb9eGw0Ar6FBhSJ2p2N5vs4hsZ3/wGcjKA4itStg0IIRVMbWcRV19o5gZ0ifPQtumZ8jAqSptG3pdguUArwz/1GyJsF38qmnljkbAn5WLO7Oa7SZDjJ9XcHpWIV8VA67lgeZvQzMtJEm5pb9JIVT2rZDF7Ek4Y0utU6mpgphzs/OozdPOLnuw7iGW+Pollci+iPyhI2fqWz3VuwY2e/nlI1Dm3SuhNEnhPQuNhz42hmIPNBO9GYXKepJqX0PDL4djoJ6F9HBeIjmUA0vutlTfmsUw/xyz75iYsLnOaiEBqzpJdd9dUkF7cz2PDQaIsBaV8GYSP4whbSVMnW0XDycp6l1LtnLENGEFc284uEN2f+hq+8tVMuy3aoJ+1DRtJYw6icK6oBbEFScRrzKpwD4w+pxPcNphMR4kGW5JRwDn6rsdKRtBpLdwYFrU7Rth4qPUH9DBZBxls+GkSxm686ZfR0yTIR6h3bYZVQHDyIWlLopYIyZxrhGH1+F+aHXuwie6/3NPhBMfG8EmTDGP0/D3E6DY7ayB0baj0BytsjplaZq2KUwUbWlLL2kY7p14U6okVxkSb+YPVYCzGWKuYcyNXE95YCvMcobiOHGSy84LfJDTxR4GYIFer9RuiWrNKEL252koo3pK924vV+Xp2zVa831tTgWgESUAQXUX6+MQOs0aFZ225y+x64hE6V4P9paUsUvblQY2p84RtotmYrLdNOXZBTAj/68AQhJPhvOujDw+L1uqMEe4Fu8fCmCES3Qd0iLIoV0a4gePM4K2ebRtNOafd4dRPZ1bz1QPo/VdlFHm/JmP5reGgcU+DcycoFtsJs52u1T/c/TZCHbnE6UfeWdGY9Y2QMK+VPuC4C3KDAmVeyiA8IegnPM7fPgLJvc/dFP9XfhDNF4gnnF2BM9M6At7VJMZGIjUMVBx0w+dn6skRjuht/8jj+5hVeaQ392owEk44cRF+QkiQZzeDey08BLc1RDsUwYsUtLd/zbK+nTUeIsLMdZ3cA703ZeGvBpQVSVK3kBkh0ZXQCatiD5MY1EEwzPrvWYrEvGwS0WtIbzLagxk2JBSp/lzES//RKBY9Im9nbcXkpaHe1CMzlR1jp2o7c8D2Wl4q3+pxz1d8Ngjc8h/O425bCLHN32b7ipE7E0f6OMi516DiuxzzG1BUTzNa4Wnb8RkX2AfieUQE0xSLh4kOuQNuLWvf+1vvuovVl9UuxGwtjoSjm93QlAZMtF4XuAqEuGhXrilKG7iN3bfAs4Wp9JBhj1Uu1I585jR1DEkIYfk9uJY53Ny1Pe0/BBYVcNvouE0VLrOmYaI9AbGOqAN+YwuAW3uMkF8qQmWzCdAnHrD8nfmT/ymMrhOevJNKwta5Ijn5Qv8/0C17BngXac702XvdfDxSDcvK0Ms8CxboCBomxXhqFyK7oHDTWiAORJMCTVF1crqpo9U3bXWFuKo7CYsgf4OCstcxC2plZ1HChme9mqQz6Xhc6zrnydnZq54Rs0PRFNpAtmOE15tF5BvaJh25WKDJkxgz/eEZUM1xi3nCw3oFKnUY3oywm6xkysD7hDIzv+CEqa3kjHe/KYE8rUvNok8dfPcK+DS5lFrDizxgCqqPDhLJG8PAtCBY7/JyuFH2zrGa/PS2s7Vn1hPbHvNL3Kk+ezQmVUDbKsU8RzMZCp6Dia5aaGPwDM4j1pYAzo9txrBZ88IvB6t4Mm3XnYlTGpC1yK6jbzPzTSRqRaX6ISOA/MfPC79bgmuo0zPgHC9jLA+MBxacqTLPAWHch/E2IE3ZptCl0a3kzb6ihFi/ZiM4sBneEW6zKmh+5SEvrEy9/wsXDycBm6Lvg9Ku4HvQR99o6mL9ciZ5F45DgH9cWjhCcbnAk7wqIXoIU9yQ/wfRoWpgBNgJHnw0VDvNyGU1vdUSvp1+dpdg1AN3GR2y+VnmRnD4K378T7Ae3XOtrt8XhSFKgngKEgKz1Vo++WD6hbYHGClcXO0Qe7GcNv9ArVmrWZJf6BJI71Ucl29MInw2mHLvSao+LfDatQjGtBXOHVMJuOMp3o9QCJjG0RmzzWxNFwUCaqU70bmzTeAeXRtT738kFSQ+ndd1Bb6/vJEs00TyPjrvTnCxAWWYVlJSjJUr2gN/N5VkKi63LWvUQmpf6FGuGHy+tDRmM65hM1ScQalTRVqGgKdOyGF/dXA=,iv:CY59BLJ/hsIVuMJ+dUwpUFVBap5AqkzjwfzEEG8ZCn4=,tag:xHYJFpXtJVTdSBDmReEeBA==,type:str]
                    tls.crt: ENC[AES256_GCM,data:0/QN8Uf7RFiA7qDtvZZGwf6PMRF4+uv+yrtTFzL6qTP6HUR51c0bXhpVTiZGIJp+7fPfw/GLRmzNx9y5l2epgltkhFy2J02LKIcvZ/sZuEIhDTZGLueysINhglgmaiZ3OvdDdFApERt/cGFvzEV/HLLFQCCyvfP2d1VawgeDTjZt6zc2zizgtpKwScXB43dae6q9GMQkNJX+2JTxeHh9qW/uH0fB48br8/3UT/WqJNzlmZyBZds7BXXcSWI7+7U/q+CwE2ctaUawpm+4KMBYfO89gmOcWiwxOkSlK8cYeNlq9s2c1fZpwBE20MCN/hgLVzfjiyTpvnqpIfsdPKb4L9c8P+AYoeGneyTri1AGhHjr7Z2FGZhTc5Rwnho8V8cxOcJVIgpY7fiANuQUmXXDaCUxfcsdiWVJDzFXonkzdskAjGuKyCA/mrRov/hrTZ0e8kr3qanUtKrglM5loh7cFtxOTzzAOfHGPsjd1tjRM+1siO31bnlh334Jo/uP9a5YMur6zyI4SRtRX1Pb09zMmdmKcXOLMFsXZwclcYCvx6nJKzk6IlaY0ZfjFWfSAn14fZDC4b/QbnWVVprdyqfGOETsfrPFLsa7wAqD4tpQ1bthKlC50Tctc8VefIfKHSbS+0ykxNtmRhd0H0zxKXkOLN4z309x3cxsBzFJmmrN0/Si23t1C/xwcgAc0wGP03YFUbGgrNvFfmS1/Sm2z9scSgwlGncSeItMoZE5Iq6YgwoZnotOELnGTd5Rl4+DYZ6Lqr2x4izFNlNMXDKTY2CxbGQdXMnaiC2ySB7CB7gges3PMW4iC6gfSWShAXSfPVSYNHWM9L3bTS8spuc1UTDEeB12rmUFY9Owhtunt+rjbtiPBZKXvmaW8L0QmdasdAQfwvbWgBwYcKu4aJpbphSzSHTc2IWmy02Mr6PrcTwGfTsZNcECc96Q4knCKDBc+1F1XAWIO0D59Zqo4DzsTvOG0b91x1PzER8mkmkDWszd594SmygPyWI9o3w3/CoNcp9bU0VhtxdfFDAk8vfKUt3yhP4JBNuoNiB1Z+QxCq7PqCpM24Za4pTAo2yaY1fSGtwqqLSirGrtiftWlHoRm6fp0URipgSjg7QXrtfDL/uQYOd8DFr5Ya6/7SBEDstCUy5kbSbjTREDX9kOZYKpeWG11FIva3qJEu+I+OIE+O8FgkC5e09jg9/iwncy1Mzshknelw4n4mRVUPd/k2Ugx2JSlO23H5A1l+TVvTBw4Pz5dgIjsYHu6vymRkeGTPBVzba6a+WoppGdHdXlE2jl8sSR+lwr0E7RgEBSJZj9OtDUHab18TGX9B+LaCxsUk2UHoQP/raOGjZlYrvogxzKr7SNAwcqdqLogV7Kz1OZ3IJ8GUjbjdl8YjQSKB53H68Zwbk714c4MdKjwYF+9kASofTWlaa03fcbgnY49hKXbv6hGYVXBWe4hhvLQ+olhIGyo8gM73QsW58/m/XE5gwkh+YsKIWyi10+HQ9JenaG+UhlyLvUGFwChQVGz/8ACzIoY7olc74o+cn5rugmCkO5D6tCybcW22h9xD4MzXiy9B36ulqiO/X0iEGGgXsHgtzpu7pdeZB9kwYac1FOJqo7xp9a5fK7jLDbsVnSphBhKUMVlA73QN/Z2fAQH442SIQAKT1M4h/mKyjCdjr3YmHkuU/hzNcyz9WC+l8bZMFFnqTjNH1r4xJS30MDaonreUFEEqn4jjUZ2mibtN19igMDqF+yc6YK2uUaDQfo68cZG3oKCpM20kVqDKFchXrfEzPLoJjD4bKvX9Ys5Ok6Ppz8MeYNeGd/2jo8UQsLqJwVi3aRLCQRHTV/ru8pDHNJSXxEBiP/PyU/a9KlaY5RC+LRPAmYjpemjIE6Oyz0Li0q3m0CHN16knHUOzcm5MTYf2Ckq6LI5ZLnfkVxhbhOfwAnuHo37SECRnCiuoU45DSO8zCVD7C23VRTAx8CVcaOQfep+IguzwgWgBS07pYI4EbfmFQENAIDjRz24Nz3ZziTEeXNGFqbxud/bN32qytOHcTa+PhdH+uNsL04eLZ2lsXC4sbvUcvdPIpcy4K8h7HWu0EnxgvvXGBxuo8IFM9gSvTFw+mE43Kgmm7pgsDoxcAOAzSR50ii+FkS+e3KR/dTzrkWR8om+uAiwuHVEcI245mwkPAcZeYvoTFhGgbacfb2zB4raKMO+htHNltFq+zMCmuNGmyI0rkIWVYVOejQ4stX/6ti25pjLGVDDLs4huMBipFnPsaGTkZp1G8OAMnBSy5UAaPhwdW15QnM4SL15bk5SS7X4BKyLbj+6DuJno/qcWADUA==,iv:h+RSJRxBQWd+o8GoLrbDudAP91Nw4ef5kGyTjbhOo1g=,tag:Di/zVFMloCQI6DT24bPElg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T16:20:48Z"
    mac: ENC[AES256_GCM,data:JRk+spn23fZPJiM8dc5+Ae7RHUwjZ3wn/4/yxF9m06Oyi4h7eLx2VbZXaKPhXemG++kLRGMavsNSmCNvtaLhSOoQ83OepJLhbCjEGJUtZlkyqW8EZwqnPPja1VRamcdtSMyC+CPPu8qUzhnPdYW38UQunmSuvceU5B/ymMVwJpA=,iv:Jfl9aTPtxXks8b41QUgbezhUYioqajAGXzjXckpaAoQ=,tag:sIcqMoFDwE/Ym32OJml6jg==,type:str]
    pgp:
        - created_at: "2022-03-24T16:20:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ//QJ7ZmrkLTjXhHCiB2fRIbzpUY2ZWPoumCH0rYqKUezvm
            R0NZvGgYl9cR1clyyGWGg/lVFH6otsoO2h9I9LEMuG2A/EZ8q8OEuK5jdCl4nz5M
            6jWcEZZIYfXmPz42elq1lW0amNOGg1b58mdjOxk+BebNCyEso0EbbYWbql3f+2/G
            Sp1WSv4AvujKMO6Bv14WS5YCB4ZckgYwTZ2zBH0USvDxlt9ZjuKk9gx0M27EUd6m
            XPBIJkH/IIC2F0V/SJ6SjFiJ6Bozk1cKKFJ+l3yj0cfewCyk5yz/RPrzOW0QJOIJ
            1KPPvsLQ05FDhEI0T1BUUGfLqsziRzx3Jz/PL1dk4SeA1NwsVe7wcg/gMUQEJqjv
            kHrgleTyhN1FwO6bWb+nuSnvUDV6uJactmfch8CDOEwneYoCB89UHMGmr5wEPzaG
            JSjQdcOcQqjiIncOcB1RDUUGMY+QZTr2UFY0B9XZsEMSY/OK0F0qGBSCzfBDxH37
            XYopZFPk7kbVqsoq7WVc1Dk+P9HPDbErSED1uyk4hevs6AjpoLDD4SacB4/JzsBt
            bS0TmxUBooxd5O8iVweSGfjaD9ZHe7KishFvaRBeKXpHLIeFpjVGBsRMf67thWcA
            sBXr/uMpAfuwgEOeaC79M6Jr1qgK1pVX6ewg3uzKI5wuR/VN36e6zrVAhS1Pg3jS
            XgGQ/AYnyJSbbgAxEEc0aP+sRmmdgFljtcLbMMDM0TBi7ibzDMd39UTKvYQC+duv
            Y7J/3OvfGWeQLb0V28ObSH4QNaNBMfQ+4aRYumjiAeZAbIv3wgX3C3aLLmktKxA=
            =7jnq
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
