domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
            data:
                count: ENC[AES256_GCM,data:2g==,iv:9M788x56AwGBaAARjWI0aek8IFcB5IfVmqyU0eN52JU=,tag:6TKBm9QqHiVzFfW6K/nnaw==,type:int]
                persistence:
                    size: ENC[AES256_GCM,data:cigi,iv:LO5eA5oOl05pJuR975m6l9yII72WcWl2JoXrcR7ffJo=,tag:uYf9YaYX/y5BF5w7vp2zLQ==,type:str]
                resources:
                    limits: {}
                    requests:
                        cpu: ENC[AES256_GCM,data:BeyG,iv:uPLCF9wHDUOIMgXIFFlwx05qPSb9DffpH8JaOQXr6e4=,tag:z2bc1O8/JfSsWE2CQ7cz1g==,type:float]
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    gateways:
        public:
            tls: null
            type: kubernetes.io/tls
            data:
                key:
                    tls.key: ENC[AES256_GCM,data:6z33ob2frojDZqbPEZdYq8jlzHdlny4gS7I3wr1Oaw6rhQrF9Zw2Si9VQW+cYRub9ngOpVHZFku0VIlI+8OhgNiis9PMUjN5tTl7Mq6nXoYeMM1VtAklkK7QeJYbXf8FEq+NvZdg8VHPEiS8DxGz98or+lOF8BLIBlWW3p87qmPKOz63fgR8BuXnm/0GFjSa7Oo2iDt6iE5nylM6aiCcSz9uIiJw7wdZvmm/GNq7IxJtmDXV5INMLTPBbM5lCqZHhsOEi/uq4OH8yMvnU3io5/oDK0tSAk94m3HDhpYwJNp/G4WJHi6DGqJ0EgwYSkpCx6gvUJUay1bzMCEws+sMh+92HkvwRZQH2PcdPJ/0O0u22xSTIMmuaoF9R+ec3ylJ8XvRmFiZhv0+fVmystSCwl/lPJprDPakYZ/R8UL2Nk/oIO35CajqCW6IDZWt2BYo98tYT1BZAisuHYIzNqELVqPEJGghlL3Rzddh06DmefDvBUJHxCWNS+3rDDXVdNvowyXX47t8Aq+gkUCuH5y8a9LhHDQjcchMF1zOYDxsz/J1yXloOGxT7UjkVfVXbs0ztxENe6R3G4zdz553IaKHbTDVZtcS8F9Hw014aIoIve4nGrUcrqAusZXS7EAIEKc4tJBxeiCvrtAUQcWj3pb3/AsR0G8gGoxcKtoj5lfVoyzk9xH9WhEA+V+iQg+LUBBssl9QJZ9iH+nYL8WZ6Pgh+si+x2WU4wr28076LAeVAkUwiKUpbebnMRQvIjKb1Ux8CLdQzTCDL5SC8lHvWOF0XAvbAhjLiGFi5yUpbdM5+EhMKjiIeHnSCNj5sXYJAbWeik0APm9uIdO0+Q7DxMNQQ7p7j3yLnlVhyvrH9vF+7YqKmF9QLxWialqFppCUuWt38XMEgbFgwaBixcl7eK07H/+gLvDpMmtcRSQuui6aooZGtoHtf+yrmKJzkNTeB9iAtONXVt6xDUVj3YBhV7ZsmEzpxygtyYljtF6JRavvm3ibmnuuehwUvJXXauBEgp+T+hSzRO5UuYDlSt7KMzqDyX2kyj4Twkn7q35GrVYyxo9rcWBf2JhM60eMB0mjWt8IDgUQJ/RXlSHgcUc9yVwtyntlI60ai6s3PAEr9e6uiGH/vmfwxxh8vNKOZajKAxa8QpcLw5WyPIvh7y/BUodMa5Brd+u/VoxTZ58Kg7jD/4GyA/q2OQ+0sQyg686NqYl0QXX3jX8HvmuGSKDbtuX0hsEeI8ezGmAWaqDjbPkuu7xB3cMNs+vQQ+CxMQSt2p+mY5euWl8Luzk4cHe+Wz7tXODEEAPiuW1GMxCoVuGc+ZdCDHmXoWymJ2FRoAw7VXxNXUKvswq+ouwQ1ksQs1VGnwpTRdvFZ8WdmiGJUXhq3MId4CTxaBxYqwnLkDX4xQH1+jfqGM9WKzmJUd5ss1wOCU/N5+eqzvuT/FYje6mzIe0s9CqN5qtpqMozVS6FM4IOo9dnBEyOzSqxu9nJjLuMOKF0ek8n3neYzppeYOUkvhUXiCtMS29VCq3VLs8HaLyOXFg/GsNifINMpV1DSAnA4nh/bW49ZbYWai5y8Hem9q0YaXMx3RQj3znIknY6x8npqvZdUuDWtTfMt2FZppAK1DbP3Tu9g9ruI9zEiTG9J33UAEaWT9GWFpT8MWSRBxya4TN+OKhUcL9KJABJeb7ByIrzNJNC/F0wUQr8+mqdRrX3Eke2qQzATPUV63QCeBVkWhBn7UAJ7AAIFQ7RVs/q8/WCd46ZaueXs9bTrnhyl+RKbK0SeWhki+yqE6C9aOD4lfyuETqUNbhKBKnBieuHvPOmNFXowgiiV/oiRvtsgc3K47zugnZNTc2We6OeDosFYRbPbcNWTD9aJw4CaxSSOuPR+Q/yu0W8y0N00JQkR9OhmUUO8/EXWV2oB5ugQ0Q/akgw+w/Y9WhjxgoPLqYHpDafpUNerZxNMShD5ozlGJZQCv6sUbM0bZlhWVoqlUf8qFA7iSUST8EBOAGiL3CIQVt7Tj+fYtSaslbcRz22jv6Z4lC3YOVQWkW84ItJPkbBZH6hvIE8SKjKxhZWxFpiL8Pl850b442oIecHQmcnpkEdH4FF+a2K6C1bx++ij0LHUes73c7WhBT0ufWmReSwzPtXQdY738HuaQtgwdSid8KZRJQ3zogxbWjeQYqLXKhcxZwV+Zy8ZBy7SP9d4DR5dJ0DoXwCo3VpvaLC6HTYfiyjEGV9P//7CkCKLby7CIyjIKzStW1rFTzzNyXBdBZSQtxjhuOBWh00qMz5kJUzv3AvsslTDn5EEGA9fvq+d18wSAxlnKyaoTkFCX/uSQrW8x3gcw68IxgfUynGEX0pZ64veUsSEpA14GtvdpftP/KXQgGVojJkVQVFWSD/KJE6ITFoBgObpbxyfsvSLnw8wKPx5jRnGke6da/UBWy6lAMRibpucGZ901V/OWBIHuS+bgvHii2TjEjXV4RBFPtr63wWOXCJ7dIt3CIJGb9+hrLmupBcP46EcKENxhhgzPDVzXkXT44Tq7+7kyjXV8uEFSfqAPadOXW/IBNmhB2UFWsfNMZaXM09VLtqMYkwrB7ltqD3YV/6uYKrVeTlWe22wV91WKc1orV7m/wRTYAj01HybVnb3K+rt0hQfTJKY4oJOl01QhtXzzINqRar5c36VNd9Pn4IESbfF83fljk/hhVs/0ByPUlxtCGi53BgrxWxyMIOxpUAqk40bketvYSHZMlb4whf2fM6nbfMzqn/hOZYVRgk+zGuF0ej/OeDt5HjUnxm5C2erJd6r6YEwtIamTy287SXM8SJye5dP41Jda8HsWFpNFv1JKNeZRh1zHNKJxDh5e3VQ/CzgRh18jfvwAPQ4lK8CA20hflpKclm0nZHns9pe0bvnWWBSLrznCtd+sUoIfLWwLKR4U8Ce3U6GH/TYx6pcEPDGh9RVn6cbw0d3TmVOrotscBHPjtYiJp6vh8WR0DyJ4hHzu/LwU5Lwwk=,iv:sfkRoLXQqi7MIH0vd3doM0VEXWz6WNmvYDGInVgC66c=,tag:SzdMjY3QI2zDJsvzq8zyZQ==,type:str]
                cert:
                    tls.crt: ENC[AES256_GCM,data:N/jPJyW/+AsN6Zl+z7EML5Q3lBeUtVYn1QkZUDfL+LzdkMUlGxO8gxK6xy+OC83yITG1WqjyYWofIfB/roYt3o/p7N3LaJvMrp6rabuU6uQHzWQlfDAl5mBE7IMqBchLZ4/Wibs6vhc67VwK2NF7NWN3IPN/HLWVjnqda2J1eH3fXbUmTkxvCmK8RUzyOVuarIRXEXhMa8Nhc28zn/BX2CWwpIPhEv09BvNnOlQwmK5ISOi04gSti+uBgJPJpdRY3n76FUIzMAxDeoDjZQd+nKZMt3wrPn1/IIZQPvagkDVWPU6ebV/nQVgNMGgWJkftvFgWpYE0RBgZApOdT6I8VvhQDJunawqSHVVEV7cfqKZ546rxxMK+oEC3nutnIEsZUJqaiS0RrcZGASk3Sag2179Zd/nWH3E5VVJo27FGWy5A6Opo7CIVpYvxFaXWqCIkioefL+Wgu3ATVPOQ8d2YFNI/WBfoqMf1qoxaDyfDnqx2CwOiB2ot6E7Axmyxe5JbzTCLvh3OnvC/eIFaaGK+4qswDLzaG8Ix7QwS0zcZPJsz4J+WR0v7SPpY4WHDDfvmMsETZ+M8Jj6j1h/w2BIFUJlShhnNmF5SgZUvrdEDWQgsVcTeZMV5PVnHB70eqgTmb+CCQqWFiMTRF3SJILsF95/upCUK7pGLCauFO1vZV0jjRMIGAU0jqpgueHkCDT7UBdM/1yOYvfyTt2AmCYdPdo8oTHisRfV3UrCCz6hTW3/+sHghL2Xdbo6uXGhKonvtDplAmGNdaBd/dRA7TsquWZLnXmS8EJtDFkWxMmm3m+7OcSVNULrgMxQgd79SO1mxq/SahnEVHgOn0L2wiQ2I5fHwf8jDzkIBvkhkqRzUueimlDPAq5wzT4bVs3MJajzbI7lCiJgfDy9mGlgQZ/clB0+UOclqRQWECk0JbXOOKHmJkgdQiWiGRpz1N3itULqq92iyACmtu2Lfav/87FhyMG8UaIS8Z0orTnMhzhEu2uWaX4qrxYj2Yw+CROuoSggQxNjsEpYrpTcLzN0xx4rBU+9fhauSnElUlLP7dP+9BcM0XDtPuCqCLgSC3u7Io8Bnp6aQnkUzHX+akCCRtXS43nuNhEbHbxL4WK0jNVS6zv7xwjHGQfnIP6AajqXc36OIms3Knb5Qdcy6a8MUl83Np8v7NqJzIotfFLDz+RDPZnDU/qy0biZQf/fAHegUwvD8o4hKNsJIITrulLelAYXE8U+ebTVxxMa658UjWhTUYWa9iaGC8q3t60SmLpC7osixRHqzoRzY+2vUnAhPDMgmI4gaiS0N/5a4oGH1SspVh+YkchJW2SNVWItfPMD86t7Nj381CuqUdlVXqdquNSEQ16Kc2L3hRlCD6CcWQkBxs3Z2hy6cv+R+1YUujgldSksfqHEn3dCwhJhDYeXSmjjF87nULbVv3ebFHeD34ngBt13Q/19evdQvEeJ7Bo5v59J/FUOvqlaSu5JqmJlUJHySCdXXTPh6Q5BDyEAJikx0xawWKRPuLfT8sfFYrhm7EtCNfO7X1QLKNfFzzEts+CgI7pqTevvMMECKd4JdnbzLMzpuDaw8i+IQiHZaXSlwPh4TbD/jyYCzSGxiEgUZmFC8Vg9ZELs3rYFGryDmLL1PTda+k6dR3NN6GKn5YQMApTnWDL1MMe/C4G5GmYzrr42Yxr6iLEouOJtHAhl84eTQaXQUuSyPHk1AWr36Hv368ODFzD+b2CrbRjCRuHpMF6jC0BkfNNGB8I2PSJI4yy8RoQaHYoejK3jopfNUqG5A+7uVCGqHRscLFRLIfRTkJ8I2n/2t9hVn+YQtkCT2roIUsZI+awcye7BgBCS4OaQimD/9EGLhvKjJ9Dx+AoD2+m2lCLqS46fpvEKJcZd33xOXp0fj5hXIo78yZ8wLlEeji9Z/PYtdBngDGuNT5lCthkQNgfH+/ybccbLRlfmUpgHPCKHjimipbaPWdsFhAUk/RO8LK0MP11/XzfnJHy06UkAbCn7PaobBoSkBe6naIk76A5CLZwJCt61hKGLSyi1fDyk/S/NByFvqbdQPLhUak6EY3Um8284vA03CHf9D+KXjURu7VX9kK90K+b6u41jBQoiY7vkmTDFYlQy3A6CepM0HOZ/yIaCl/STmIZzapTQu14Pi1KK8UAaiL8/gJwpv3nTq6HU0/71aXELGhqLcAMHccQDIbu9KBWd7lkDe6VyGOIi5XZAQC+WfOEJFcSi+tH6kAmKx1enDh9aVZLsFNpI0p93issiUn8xhCJd9XQASrnOg/O/88u9L/DOaeqiQiCAo49Q1l3o3Hhq7eaONTCZdD8JRsqM=,iv:qBEUvD/FzK6oxOb/lhFJBigxw7VmCpAWZtrDdfnfRy0=,tag:Qtm5zZ3cyCknWn3fZUbE1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T19:15:01Z"
    mac: ENC[AES256_GCM,data:pEIqFytGbFpC8coPwQX2ZS89Y9iHLcqQR8ED87kgc34kM5smMYWaw4YdC89xZ3Aty85SeDa9CMnmrQO8n5rRfKZpPYDZd9pPSNoRd9oh2t8cyGmWgnvM5vsY+n018eNu0SibPNTGjcGJwUJyFLifP1nXfy6Iikz3AGk/nFcblqQ=,iv:+3a9NZBf6EG/Snl8ozHOwybG+v2cf6XHr2i3WDyh0A0=,tag:tx4mPFpaNwdwKC7H8+r3dw==,type:str]
    pgp:
        - created_at: "2022-03-24T19:15:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pARAAjVaJG7Ws5F7pRzXd/jbY89Rup7wcGE2HC9GcjfC+hac6
            ntr6MjR0G3MKolQ0RxvJkr4udR139psUkbPRTgb/p+bk9PUMRrvtmVNQ9GFaqPMM
            knXcEufR5pozNGCt5edXUrzMc6eLyRVyNYGGUuuaUc0Ui752vlIrUIgoWiBERB6v
            On4Ct2/wHz3AYDeSQdY3D/XXejDsEyM6QgmMcWJ7Bc/HxzwFxTiz2JFFwmuxOV1z
            D/Bhju8bTUcQO+4KTtixxcoZhkyMquuimnQKEcUOxAn2LRBlUvJNxbyNkqZAWjZz
            BeO2k1RtzGGkoStMXXpJM5SpX3xwwSsyCq9/TDRzZvY/1EkrMu85/EEk170ndxuc
            Ga+N7m8QPc2zMoswsbIahN3jruDjIclBFEoM1q2zrF5eOoekOMHnTVEbvYpcLR5B
            HIBxs3U7pa2YyCMCPlwOT1wPzlNUSYKhUdQSkMN7Tqr8bQt1Zmvcb6kmMrx4UERI
            neT65eu+MGjTSbSVsbvyvvVwVs5OQv+RxwvJrB2+QA1opKVpEQ6yv9LVMfVrDekd
            yAZAqQztEm+uoy2T4tXiGGuN/yS/MRQ96QtREi4blDfQUiHPRwBVnqnZ7fzbBGo+
            wjmixmLqzjusWjFTxIjZRT6PhIVF/8KSD3Fmeb5LEqKrUPiVkFMiKTO4uOz0kHDS
            XgFpzAIJqSvRNFia6QTW8zLcE688IE9awMSV/pCTh2pX/kYx+9kYAfiOhJhPxGQ6
            AyRGwYEn7mqDqVYfq5I+EIbVrofbI7+7cU8Y8NnMSJhXbSzCfdLoX1TteOE8qIE=
            =UJRd
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
