domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    gateways:
        public:
            tls: null
            type: kubernetes.io/tls
            data:
                key:
                    tls.key: ENC[AES256_GCM,data:1wu0PV0TZgYd0QtjA3hh6yvIjprFJim9JHeSmq5zut6EqMq6jLGRzEs6Osc9JOaueD4zxXklxzPGZMYEi8fmX61Zlk3A/Xt82gq3vKOXAURzyVllKHz4SiJFcSz5wgxx7pB4sg10pGXBkZ3Fi+QQLb3f6jixfXikegs6hgeoyuWgRyi8QvzACvdsQ8+NmwkSyY/gEAxqEk9kEZn2TwuXVFqrGopEry7ckEDDoiO6BPfR51e14Z1V+HnWYQD2tEtVnFOWJS4wiqWiuLnT/QRCs9vvmScCvfADtaWrtUVquefiBY7YZ59m8IDAyFnJ0qqD6099HjbfaXqL+KWrImc2WHRfY1VGPLu+3IwQT9Kgu64aBpm78ukPOFSUiJPynaE8fcUV3vRqpH/e2KgY7y4NEkyxJEhhijjObiJpSDIeVTYkw5bPFg+vdBj2TCGx5becVg5poRfWD5riFHZ59PRsmttaEzDIxbd7Oro+ENzxpKbP727Aa1+0Rm5202wYPKsBuF6zyuPnpgQ6/eTtEqH5iVeRcWozfJcGw8cmgkDAPvyterTLm5ZJWDLZt9topKTfiy6I2e19oPfjWQ2EAgSYFQs6CIO1OaBLkAPOdOcUS7WCaHL1Mfz9yWBxY2vtUM0BuYDcOc5T9Jm0kesizgrX5jRK3P0aT+wLnpRjMNXhcDgmBbsarBCqJnF9V2bs/K65IE9PXJhcov9zmPynIkKVh+qTTGGPlZlmfQXd8WeKEhs8hbSMSVu1BgbMyk9sVVrQ72G8WSwdP/v6F1F6YoTwQB3tbW1yAwlAs/yVHWTXDnlnoBoD78Oi6vEVskLfl2gTaQMTWhA2zORty4ARMUCzEI/5/+N+DQGlBSqULqlYwFcHyINmFzFSp3MaYOZlQL9qnPWHfJeMch8kqNAEUSrF7N5WQpwPlyvLvMfUN0xrzvySVGwjmV9aFJG1d4M6dTGgUYArodJTRu5S0byBPXbQHVHGH0WNrYa2RpfmqRs2+b+pfN5QO0zjNkxnvAf8fEtkp0ThCerPeH85DuX8yBQv+m+iGqOv8vVV1BYPpwGAp6Psh0g++Zs/+3spFMSFWU37c5lJ7g5LxS5UFmLatZ0K8p6YCEeAQN68At7YhJDjp64AR3M/aJtq0g3MmNWd/fSdnsnY6hZm4+SH8mCswjAw/ygQu/pzwYk/T5lKUf3P1dXMPlXOkxatfyPI8q9R2syosRpI0G0EUiYkLEKg/9X0tA+SQ0adnZmCrsigFf4rlcuZF3lhHHYEXUpqN7ewrWNsBcbAjttcwFOOiqQ2O2qp5rNTm+oTG5EP7feso5CAxfmn++70mD0LtT0uji5h2FTLKaJqnvuEmTnGTtlQUg4VeCvNh7E3l/yHPdfuQ1zK6Zq6sQZ8OKjHr3/3PtP6c+MT7/jqvR5ssm7o4I6EBQFURfqWaqGYiqcpaYDw1htP3UVIo6sLwYdA4FUgGjej6QFnOtdBRfT30Gvp1+saqGiAQV58FrpKa8k+IAXjZQ6qoQ4qSDWH9UGh+ulNahmRE30Sn3O/Eyv9dlGG39/GrE0iABV74lwd3y8F7KCkoLiV6xALXKd4TJQsnD5JNjH9+621IdEaB2zGTTQcYA1BQ4cqrXRKhrTzpdPTQCw/RyzYuAif40GW1v4nITvWrqFlrjiqvpedKn6QLIwwH2IHVZMUYUBpQag8VzXZ/JuhHn218oatfv5yL9PIPfPzzT+T78YWR6mJu0/axooncIBvwJfcVbaRrQQNGmUJ+8rlDejH6JF2rHV8TQCO5TVWHNIrZwbz0Ft2yE4sfK3jqruFXSuA7ADkxoVYNfTJxLun8xz8RWbmmDyN6d7z8Igwe+Cbo307O2SrGQRUoHBNqsyfxZE47Jijr72t92NYNfB7GNuh8SZnMHHs9RjP/M/XgtM5+6Vz4T5kCvNI++PTPvlEL/ATFbCviXV5KDyxxS5EeotOlXeNft9Qum/YYMb0PhLMIShK6LcbXHEo4DMG5CREmTXVt5wChhMGNR2OP4Fx8WzdPBQBznNYTj957Wc7wL0uIMIK9iv1VJXCzigXt8DzX89VOg2sCDKi6Ay1zeNS+RBsOmC4+89LpQbAnZLQIYOkSSLE1+EtD6tRISEXyz5sG4vOGxjv8MtvLSr0bLKBq0cj/bqomPFVdnRucx+86FQqE6E27I8otNH0IhE1iLxSGL5u3wPfxFh0wmtgb6H2A607ZMkAMgs792zAimVmrFbJ+KvCgStkwTt4aAh7qNri6icSZV5M9tdeHeomI6O5T5lh4rQH60kxnOi9SmccRtL7JGPHaSUipAHDkRJKhG6Fr0/DA6a663MzBMdMu5R8KleymYfv54vdhz4qNnTRwkdtPlM2yeXd78ZmP000l91wa8gNhvb16qerJ18XAUXL4q+qcRJbLgE6U+NemeFjRvIpHl5wWpsw7IgQQ/oAErLMCmMZ90HSoYYnMfo+JJjqy98T75NRdPgqpEy0ynZojIuqJYKed7G/vZ2UcmEcguiphvzLq8BLApihP/ChSDvadCNtAAu2geZjrHkfjtfwJCYpWVjGwIf7EJv5eNrOH2utD+RTprj7Mcr4J0TnJjiYG2rv61XWDE/05s26PkngSq28Y5E5+Yi7ulMBMdVm23j7y+i9+noQWlK1+ZBGj1q7BOCDYZGKjN5HwZ7Qs20996RtlKB2dMuYjqM3jVPrGVMXwh4qOXXvw1msCXq7RR7Nl2On+8zsSczGGsEqud0J0UlpQ6UeKtd1/qLVzQRPtVZAw3rBDZ+n9HbjuMQkl1LkHMnb5ua0EWJKbNnPMwZg5gskuPMJBc+sIB7OIel638UOosRiCKYq+FDzs4CBoARBaQSyod412mYj4yt0JAnUf//eu6IOgoxHAta42FACfjNvoPUGCB/v83SuZU0xpLpn0XWYXe1zNmUkWNkxZyoXOMDP+Jyr8tTt16FTqQmC/dfurEllgR7vRrqrweF5xcBAze+kmJ0=,iv:Akxi0s1DqJRj/ape3O0dWOHBu7A9w/GUanxPsFuhe4I=,tag:F5lnAneX4bXn98xfcsa0Zg==,type:str]
                cert:
                    tls.crt: ENC[AES256_GCM,data:1iNP6xbj/5FeTFHVDa1692Q4tP4y0AfAQwiEpbKECXEO2KiA1UsM0c86flK5v4bdzAiBwkbcEmh8C9W64nA79yE9AYQC/zIed/7XSufjwcZq9VUuNtTtrKm1USKLdCJdZEzjDjrr4LKIsa/7TAs5/QxKFOvujf7wP+u7sd13LEOY/HNcuiC2tT0BPCXDvEsXtIooHU0m/D3IIj2g/k2eUonsmz49NfOYEuhkWaCydWL1hF5DueGrUUej+NXXbaRa+BrKPcSkOG7F+m2MYBoUdEKS8E+7iWE6O9x9ZnQj2rCXJNN2mg1aNH19MygwS0RAnlNFzErgZ8Rqj1pAEAtrkQb8/0CnCPwZHsODf7eQ2auW/lhDpxFrMbSGYF53uKX8pkRH2zykuVg0MnwfE1krpiessnGAQkzyYw/Ez/V8G1WfWLUIsorAZfdvnSJJOEfAQN9Wf/OB2HQS10u1XI/GL3XMfJtkKUDdMzDN7IQc8bnoYBJ901FBuLMPSjwQsDHKFtyRn7k2MVLt/GS4CnhqsymvDvai5aDVeY7MDTA5vs6ZfRKJjAgxWWDRvIKRnpMw5ufsOU8/1s+qMyIddhsFBic9OpaBVX2DwjkZo+udwHdHNzQdUc96CVSoTLmm5WHlbLbHOM+n4FLEyr/2l0HnGwfrsU5QywO3LkMy4HvbFmKNnTvA4Fm3rXmM0LBc+wuw082hosqnePOxjwYxK3Jt5rse5fz81IhrqbGoc9gtDG6/g14C1KPe+3fsce/oQPxF5CqgAWh0sMmNBTt1xL5kAP907oMUd8pp8PXXQ53FR9bPWEeprmU03lHaAQOOqp5+hbM6ZG3BipSUYejW6FNiyhWnfKroj92OXajuDlp4WR3n1uwwvx42nbUDgru94gUVT8881WjwMv0PeuRL8+Xpvxpc5eNnX7llir0nBSkM21RbAqs7XjFQqhI+jyxF3lVeuW4RZYeDbZBxQJPI0oeIcQolQ+cp/KbO0cQYGWUuFN5TwxIGfOj03ccf6ypVfjjumsCr9ySeTQLHq/IuIb7U/jT6tEm0nkxYUVQiMoEvpM19nEv6D9j+WRSiruxkx2aBqCUbhUwjlVBw6DrkFENPlgXfi3qoL4mPyIalZbBMh1yYRmZWDCR1kz4B0sGneifwzqMz799aybTqJBtRi8Fz3fOquTx+cHojz54BBDpNFPw+DgF7a025hhC0IbGa2AUAXyD1JCdrHMRJqanDEHW1hq6Jd4tvRXZFLwHiHMNbTMCFnI9qpsLmMNxHPNIrF8di6WW/7VGiN6jeaT07PkihGV3ZAYJIfHpmgM21jqaC/NKFxUlgHDRmpSdoSUw/B2e9kYRfMY12N9i2GANq7y4Dj+qoa3VuXdLHuCk4lps561e2KuAVbb9ZNGX3WZvaabq/Rgt1O+gPQB1Gbs4ZCKkPfGVa57fe1taMub8Swl/RUZt5mJdkoeaFNZewJUQFXZvbIdTe9wZ2yz7W01WOpTbQ73tH6KxlEmozxnkuCPePLEvMVI6GF48Acq9RWxNafRWhfxs771dehY0HzS+6iGzx/wiuVFmASYH9JK13+IAtDXRChoBhrOnI5DUJYQXv2Afaqj3eGCvVT5MvlLWU+ebFDbWtBfbRCGzznDc1LalLkf1B2jnAvpffSBLgzKt8m9YJstYoJvNv8veAMAUgscvjN/lMrHIQaSxekXWYIV50hR//1vkz0HDhhQ/Nckh3vGPG20qkRTJuaR4pRyYidcyqrpfoWHet3r8fqcsZ3agj1865fwb26qs/WhNHyodaLy1Ihw3zUGW93Nr+W5otnx8afbsGPY0afM8A+tSfiyNQtleMd0oL83ERln9kepQ7cQ4OahJaSf//ie83T2wVctu+zqPXVBn8eglZxzXjl4xuKjSgRMp+LqM29QHRC7vn3TVp6iyN1RCb8Po86fn0ywDieCaJ+TSftY/5LRGxEUvRlVMGDAtggcQNnwgnCSDJJxpKwob3fdli6OFaPycddWxP2/CS5LYzb8mq8BetgGX7+YP2ywuRcsHOkpTv5tuoGMmTFyMfBXzOMxse7ckAgnsb9Ve1w6Y/l28j+q7cHdhTSj6/RHxLZlj0arMat7mjuQvuX+q3Ju8yDuTivTT2yPkKek7MeumaEQJNE8JbQaydTBc+znm3MwhzkOMnO9xyUgwPjHA4fx+PWBRFw6f+i9PhF1rq33SpIbrCqyFUhfzM2tIHmQgs+Fb3wk2oJtIsgofwmuphiynQutU1dur800kRD7OQgFPGEd9N21GpZTj5PHuATJIV0TYbT79qJ07LWXj0qnzosrM7wEjutCo/+2GV0JwSd34=,iv:r1dK4Hc+MoFQQ8U02v5lLUyhY3loN6/dWwa5+tRW4Gc=,tag:eiJZ+kDrZnCpKhj0iHa4Sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-25T15:54:29Z"
    mac: ENC[AES256_GCM,data:E1bHNT6/cRZ0awXv257BtTTpMyKSFzw+CRILVt/Ie2L9kJVit7lQAJamw26ZRFVrfoNhBJULxDGasso4Ss1cpyL9k8O9Jk+q4gRh8ECua4/hOly1bVNDsbBQiYn1WyIO25l130rUp4f39XyaMF7Mcr6nKdd+kr8Dbk5mBFSkvGA=,iv:DsSGC5m5Z9TXZ8He2QSOfZ0kPNM/LgMY1h1rYVh4fGw=,tag:dlLBkIysuvwEZRJ6HbZ3ew==,type:str]
    pgp:
        - created_at: "2022-03-25T15:54:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ//YGEcsHhzi68LoWESZICygM2AsxS3R2oEY9fszKJax+XL
            iwFasEm4cT2ugAllrCDcMzAFXu8Vnx8S8h0ZYMKmA+EtMmylmTThyW/eDtZbXNrz
            qQm7zYK9H2IzlvE42953/Crchj4Lt0bg3wJjsM+SWPyQw/9PzpYlYNCYU1usU/0D
            vRGM1oI9+2WsNVFJWzYf2FZ4/RVy/ZI2PpzQXwD0Mo4b4o0mgvsakQSKUumhp22h
            LMuPHUAJGJKruEs1Wk0CkAwiM7KUP9+d3yA5G40uwC/RMg6xExIAGJjvK8fZijuo
            KcTKguxj2dKqgF8nzfiM2WpQXYF8kCO08rMqZPGJmf+ODzXuuz55mGnfiiJaBarw
            OlJUIUgB4npXlx3tZ00UBt2dLLSC5hSGuMUtulmEckb4WMnE9ZraiGadvrKLwFip
            wst9bv2E3BCb/f8+baTs2NgukPQvFZIZ1aoCjvhhUN1EerJoulhYo1YynRiPzKyU
            PWYwNEpCpD3McJjGvoiOR7fseYmW7VnnVf3LANFQxGKA3sHhyXazk1QppRzHrtQp
            mPtsUFuMkBtejUYfT24C0hz9ZRAPpFvVQAoifXo6pFX0dlmAmMrjDC+vraFTAg3e
            SuBMVu6Mt3Rgqb+siidfQluh6NDivDjrPCD3TLWtnD2ps4XJLKgyIGsbnQ4sjp3S
            XgFSiPgbPUZCBgNwK3Pe3acVybnfEPBEHcTnUB9B2q9gwCk4mzPyc4wJWAv0nevR
            RLeaCjisGM2a6vdpzwuogdwCfJIiPi//hPz3fMFz1Q6S6bfopWOma3/ZFzS7L/w=
            =BViK
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
