domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
            data:
                count: ENC[AES256_GCM,data:5g==,iv:6hsPm2RzIOjYUKcawEZAw5+AUGMyU3eQn50WZ71HuPM=,tag:awzjyCRE4+5vgW0yT0Rkcw==,type:int]
                persistence:
                    size: ENC[AES256_GCM,data:ugSJ,iv:G6/x34qHaeqOk05u0tUX2Semux3vA8Q3st7uDPhdDtU=,tag:Y3IvHFgDX08kB7u+zdzswQ==,type:str]
                resources:
                    limits: {}
                    requests:
                        cpu: ENC[AES256_GCM,data:o/qQ,iv:hqXIxU2l2DFpf3tWqLm7FYxjeasKq56f9X+icPABVlk=,tag:eWKp0Ka56Y5UDnGxc1So/A==,type:float]
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    values: null
    gateways:
        public:
            tls:
                type: kubernetes.io/tls
                data:
                    key:
                        tls.key: ENC[AES256_GCM,data:vRPJtPZzAewRLI95uvqAndVprhX2Fhi07XtMGlsGsc1zMlHGQ4FGMRIiKxDuhFHMIZ0PRjQTRrLB0EzXmhTGzwXHr5AE9E31fCD4nXNjxH6VXcZ7f9mlJEVnGSYffegDvlCGmwuM8T+2zy11AmbwLrgHjWkbo8iIRKRElC1V/nnJHI1kC+RwdyW6/KdRk+fKQCu8jxexAVdOLZ/UW/uEtPGV0MxEnT5pPxfeqhLVxZgnIM0k5JT8ZvuBvEY6Cn31X0awhVFw/t1uRZIypagptHA7/Qinj2OVs6fkZ1IQGuEVAjR0Uk86HP5h6YS0S5cayeJoaavh3J8Lt90BqjYqLqTC6BuxfOXlUw+n46n4Li0kBgGFm3y8s3MMakmTSJCUA6ioLu6DVCmPUQMItPBKjcZpGpHpFSHpG3Tq5TeB381I+s7C4M/lfuerFgMMgLzTnu4719SHf2DVPxl7ElJviwl+aH5YmYvAN48/u5iWIbvM7shQpnYehqjmu6sQ/c6w/q2PIJ8R5Z/ZNw/UcNP7O5f7P2FIwbXlTuZB7CzpEI4s6J5bz8ufnyicGaeiH0Jt7D3SnTIhtUhCNqpou8fndE22sQ/6XtH3/VjARMauMqWrA6aYPtbbsGWxmr8RSziWXbAGiKMOZkZdi1+Ee76dgxS6UqKhadUS/WNqRUbNXdhoB+2xnJ/kSEpyHbpccPj38wmLRXSlF5cZjYjl+BJJEFTIXwtL7vQiyQUzRbbhPVpnEsZfqre3c5AulW+XaxHygOpb4FwMiXu219Xwvcw63xEat5Ri3fUWQxEV9BS87eIIOuDfLs3jvv7CB/Fgh44q82wLDQMmHsvr1OlFUowBOm41li2jSW6KC+q7QWWwKhwPN8wB1uVHhivvM3pUMClMhYEhkYp+Oi2xtufKchJP5ZcAOcJ1lm86Ko/dOzyb0TSohJSRpa8d60zHRo2UajTfWbQOOv4P9NrgAQ7XwLlN2lYmnqIR4lVo2B2yjkYoOaY4ye8e5PGQQehRmShIonFuZJtkSpeCnpKKd3ubEv28U7WEqNqXdlTJEY9YUu+6QxTcNLsEAbwPl+3HSWD6VOcMgMyeqNS054YdbaBJ8YJ1+bUqzQ/ku75Fpdu/v52x2OGA56UqvnrHjSR06KiD+eyKEGe/y3sAQHcekRC9LfdtR/tgL3eUMNASnh9ZofagRJALERU81DJyh4CLdDN8jGTpxRPhVNWvlnhxkLllUB5w/wvv1/y0rIvU8W1PxbGZBEWj5SikKQorTvg/VIQK5ZDF5rM3JhOlChoHYwghVEXyTz3TmeDRT0TNa7Cb3rYWXa5f8vbBk8ZEmCdW2h2rhdsYMDCy/qjY7ZGUA3VMNTG5MfKGhWamXfn+SfsWfEhP5XE7l6r4xNY/CUFn2tA27lXDRiyh7TVLleLW8oMEZxX7vjP5Is6sPFwwEFeM8hlv0xOtq/9xMEzAmVMC2jRne2gXXAAQjQ3U4Xo4n/ImCQ3grb0lHIgqkwrCdNanrC4wu1OKHqgjanv4YxabfMc+9IzYt+nkHshWnN3xl9dqixpNSF8KkXyPRdBuKyg0c0yMU8fGdlyBtdI9I2Co0Xo/RqzcSNR+a8F0TKruusWrN+01/WpoE7pEUO4CQXR7vlgMHl2W7Lkglw+8Hybla+3vtEEww7Bnmj8l0RMfAjfdrOGka3gkB/P+hFTERzFtn5vbgMJvK4Z/l9/yqOJ//UaHKlUaFwAFu3jyl9+YkJlz041RWvVcB7y5CqgaBNa6D1ASkq3HXzncexKhz0BDZwyO0uDQuj4uFk8rUiSB/voPT9JylA/YuntrlgZZ2cZUinEFS30DtIgJtNLLZyztTF40hkykR2cq5DNNjiBxagIHEMhyo+c1QasVh5ZUEolDven3IFYgVITgQPhLkAUbrfTVx1dfi8BaZbHOM6MHxL1RyVDyGXjH5CIdv+4TSjWWvgYcvu/xKCmrs4KK9i0WwnfuWRWXy5BaNLjhwmK8zE7+ONwcJpqtyUO7xekUC9aBicJ6wpQ/+kuAv2myIXHqJn2dVfCeTFhaVYSFQbcyygwP3biw15Z1YT5Ws3CCaviwgNKYIoDjQFfSA3cq317In3FymnA+LrvYz1w78wg+yag3ioeNi6zzKu+JTyslr24ZxxN22qHlrzBahXfgNMBOzpco3IlqhPw8uTEWga/oyOHkxAfsWlOM52Nw/mOQrZ5xuulquHB8kJeF7GR1gCCqhy6srE0OlkysctVVwfMP0L1Jo/W+yanWHzsqXiIQUWe+0OCuwPtpikHt7g1xv3wQUy9Yh6sThFqXLSawFh9cXn/zPzruRMnLE1X3j4KbvQeuoi8VOZB0o+qpoTd1LKMsoeeSr/87xfRPRmrNz1uEdubn9gjmPsDnjK/pqz7S0vN2Covd9YwlPrpY1gLe1yM+5+GrCEU4wU4Uvmq74IKuh9Z/dz1MS5q9u/97Q54U/9OCKCYj86R3b8PH3WUqRSllaXC3P4egMjTXo+CxyWqyF2VtbMMaIdFoNNxhEVRAXkV2V5xKEMKiftcG2sRRMCIl5Ws8PggBJ9vYvV2c1DD8H+W5z4TZjWheO2T4H8LhOE0rt/QRhnZXbfQTmG9si8aEVhPqDAXXJVmcDrS6zxjSpR+D2US1fKNZhTYknBG9n5HtmX2Aj82hv11i8HfOn6SFwZRLsOzNHgSFlT/DFhKAM4I1nhXE1A9b0zsAU9QZeofG7iibAhPxaW2Jjal35EWIzzSf1w7q8MbnL8iQB+jaaXnhfU/qCqroBO9fuNJzwpMnTFiGKJaQuPLHnKaFQLQAmIItTByDGGfjfnNz1GJYyiYdVZB1nJmnktY6VgF9Q7iA4Pj5jrb1Y1A5ROXMGZ04ukI6vJU3zueIQ6tqQc1M9Hm3go6Kq0UHjPj8x8qVc0lRQT/nprHq8rDI6ZhaFdiSQJSRc9SqaCZSw1K3H2FlA5ud1dHAaXDdpSsatcg5ik/r4H/u3kU=,iv:CoeO9UuC5coCGKfE5/B4u4gDVwM25xzAQoQT0xW/JUY=,tag:WqBuqmH1Q2rL2JZ3OiG5Tg==,type:str]
                    cert:
                        tls.crt: ENC[AES256_GCM,data:1yzlzsncQv+RuQgm5jcLjC0u29J5SNYpyU9gDIBiNf8/PhrBmu2DF41hg5FUfajRqWO6f9P//pp/vhH4oGj2ooQLh8Pc0yG8VMBpCRHkvmUl+CAhtRDvOQ5XzeBLIHMCB3K3qahmTfk5VuAnnEMYif5DrpNoETj+AJuxUyMBxQdIWsFx2WEU9Wh+U5SmyNZbgWlNp9y7Mo2ra4i7klTr8iMxF4TJHo5jwhbiO2/TRyGvK7+0KHtjpB0xNxcmFpjMLDEjoWXtBmc5299IcZcAdwPjJHx6Y6YXFtpYQflUQObr6bLthYdVECf5K4BcKjbJILo0oNH7AJc9hefIcdQK/7ivpHyrDXHVTV6eN9Q8li6/ChYUrm1obRzeGm5+yvsTuOVWHvokXgCmA7M2jMxiBKZqeo+Sr0CredbMwLMz/rgPYM8HW99VDmO8SiuxWw3WnGIdRoz0/4PTvTDVgjUqQNJHLmhINmsBZx+GFJwguG76O8VL+Jp4y0TajvMUoOtNrwsavDTAgz4j7Qhd/RcWUPyVN09r8jCq0y/JP4uDqEV+tZ6E8qi9rrH1bFxpLsCzwSxKJhnXWu+cS2XvgdaJ6ViIH71GLyx42jPRpsDEFcBGeEn1zluRxEtZtSFV437Wu3qp6LOuIEqK1tSxZrLYFo7MSAalp2iK8NliGNXC9kflM2dH1AZ5/UTfiB/ux4e52QaM2zZycMMRk/VU80RNGFzEoup7vBjn8hx7HwPauSsA1BYebq0IrqvIeX2RPf893D0rZrKjsdRioXA4xYkXd1B0GhyunsRwkf55Co0BJ4RjNXOvnLpxxltrXQFCqT0btK7xqzqR0PMblbbF5Cp8rVAjtqxqRAPFfhvldT4DxdVBPy0dCW3V3ihAgOR4tG0OUE4AInNGRIzVMPO3Gd0JQh+Yoc8q3Kh0MrbEqAFT9JKV6JYDjSdBSLBQf/HNDCpLxAnDNW/3Bu/uw4jBDylNj0T4QHm8NWiVPoTomjB+dTkRoyDhdWJPx07t0B5OOB5/LzdvTL3hrNEBifAhKLkk9btsCFJTyc118E0rA2J2wb7MS4ezPECo+aeSP7UsIAxqNmDF5TFTxR0ByaAEeRryhT6DYFkYCA5UryDjLlzD3mwFTTE/QB9m9J6RZ+LRGVYbyG8OQ0l34aYIgua+xWJge0Sb7W4F+j2DRvl+pQT1S6FiXgwoNalAG4BOqNEi8c0AUL4YiP2/BfWSVF6A6nQmYHWTZZ2y1v37iDxy9r5dll3kG+DCMcpHYnZulQ1zaaFTF2G0PhbJQ/yBzaPBk/5cxK5GTwl4WGhwGi3T680PxOtCd8I9OxblDrQWJWSjCyifsuWjonxBq6XGqZwjVxJ7qqgzvXSan+pLRgHvemzWMHmH6e0rsNaXaPrKYZLQxGxyO6W6JsTYgpcd6wSpLFm8fVeTZAGiH2TH3AOXSEJ8LlSpG797K8gQbGrCs/jLKcYIXMdFefCW9h+zM2HlSJn6HUI8I4kO102UmFYtNSVbX9Bf1n3EVRM5N4fzHC5BH1P6hHj5SuVgt/MrT2h9LwKQQqhofPB7Samfjb++A4/+iOPjSWO8IsNcjMQjRqy84OMHOc/BQ9zSfBEir1j8KMMqubBrTf+qQc4RcNolaDuWXFcP1xMA6Swy1r09rhSpy5WbFmxQVp7vG8wbBAmmmbM+/yTeZTv6hyk3Og4JjglE4b/liWu3e/OxqODdEFy8yc+k+shbtnN/kyzvbLYQob5IouVuoHviPBpAgxo9OxTt+dsh2NfPyXyiPJXT+A2B0TyP8mzcZIEnl9C4tb/+ZXl2cMcy0DfABvQvH/PIm0wIeNUVCkHl3tJ+PBEq+FpIZ/WIrehIot+uG6rC9FqKr/FjHCLGswA9D8KTr2tqUbiXRfwU1QHmWCUvb+VU0NL2ZFxwtn85T4Oc3i9WhcTysNrkJHYCQ+Nr1A+sVmOvR2O9xsGcj0IH0RNt3cUv192kQZCjrVjBdKDkY/75MsCq8DYUXtdcH6TPNBMJrPhrG4SWMf2rYmn7GJcaTM3UtjIpDb9xQhOiiQWFUSdumgnRObMUv/EmAOjSRjsRn9pBm6DwwYYP3bjlIBhaa1r5OWtD4uq8+DV1+wCwTyHmFvw9nBniL3fo4wd/Tt1YM2cQeDEzChlf5CjXIgMrVS4yq3vx+QOfKo7TDncMkhOoY0wcqfFbVnsWrDtUYoiaRqh6HXB4bdYONfsGbl01QXo2R8XnTEMHK5ueEVT+2w08xjiVWXkyg7dDD6ZSSM4r/aEegQl4Et7iSncDm7Y/jz9RUF8j785HDal0jCnCePguCSxfzZSaZAJXeho=,iv:k2Xc2Zatd5AZmhkgbTUdRug6dgbjZlW6hoLetBCEMZA=,tag:buv3M2yKGS/v6BRQS+L1CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T17:55:12Z"
    mac: ENC[AES256_GCM,data:8UwNKDNArBIaHXhOW6rRBzWScQZ6Y6A0xh744TifZr54y7hzOD/1Ij7Cris8xYWkyEZELvBb6swr/vw7KraUNS4rVdE7qLFBdJRr9e9DrJzMPg96nY7BEZFTeJsDx98mP3+9Gc3fJCLqcBA9GOOchDXUk3NA2l+GoJxC8ZWIlFo=,iv:xAoOPxokJxwW3xltnQ6Lwop4RJy8dHKFPrO8htB5dLg=,tag:eZzE1WZN55T31NToVJlGEg==,type:str]
    pgp:
        - created_at: "2022-03-24T17:55:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQILA0/UHow+A74pAQ/4+FKaaBSt8g/FGdMd5O9GjZbPgEnO1Z0hrv7dWXSEAWuF
            GNSeSmqBUKF5LaDMHc8klUnBzIH/7LWWGH+GpOu+qYN9FXACdY9bia5fag8hs7yt
            3YyqxpUWPLGSqw4WGSo3A1J4ipTJXo73nxCAq0MC+FBo8U/5VQxtI5KkOuuliJ9g
            OHAi/X5K/d/2SeAG5FBjY8W8aAfNQDnqDKnP7+lPvjoQV3AF+cEoCSjypR9dG+VF
            F3GigMK6bml96H3QkbbHURbyMntN79sZ/bbPNGYtsLj+1N0qBuKud7P6wGL5Zkz7
            h7ix/kfZngYHtz1f2tni7RV1r1SfGPdaEuXvMIJPfr+4upwXSC0Gt9Cdc53vbmg/
            TIDFp2147aQ3gaGC8KtF9+vvfbmrs7K6MqGzjbTZG5BH6pDJrvHODz72qq4EsAzO
            i9VWfUNjfGcaaH2uNpmq+C1saA3xzrB7mu2l5cF8QMo3Zm19KAbkyYvw61i2gTIH
            LPA0q0pJuT2+Hpe1M8KZrOc1O8zOwm/qZDuUfshxSxTEySHQ4b6gRbyyFxQ/Hzk9
            FiRKQnggI/PkjvmclowPHlAHTCT1ccbd3JJ7KNp+pvOCnklbk0vE4ic0+LDX0eHU
            vRVZ83f+TmaAjo7b1iHkiM25SyMXpm75BcF6hv54VQORzYb6PcyHv5PQ9gR5VNJe
            AbAo3fJ53DOG+fJNxyG/fjdMrzDjcxKZQ6H8fxPU5rylMh3kGnuZoFvrDE2oOV5H
            LAtu6o2ymRgG183eQKCbD5uoDOP/ohgZ0CLHz0U9N9RUsiZ+VuXMVOOa5Dz9fg==
            =lCM8
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
