domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
            data:
                count: ENC[AES256_GCM,data:xA==,iv:1+kEg3TwymAbecC/mhhBhNb19jET5SgO16jyUnWz0Ds=,tag:za4JijL2AQf9+2dINJJwdA==,type:int]
                persistence:
                    size: ENC[AES256_GCM,data:vY42,iv:YksV2qCS3mfbadE9Mlujf9J1nzwCx3/VPDpXqjYbZrQ=,tag:0p0vKeUZaoBDIckx294sSQ==,type:str]
                resources:
                    limits: {}
                    requests:
                        cpu: ENC[AES256_GCM,data:hBV8,iv:F8zKZ9+TFNdid4+tjyWd92crKndQUoGgARznX16dxnc=,tag:xy/XV1HH7dOYXbS5BrZqQQ==,type:float]
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    gateways:
        public:
            tls: null
            stringData:
                values.yaml: ENC[AES256_GCM,data:4V/tN+9lS4UBkw9RwkLXcsvy/ninWSl1G5zTuf7zzkOiiSUpziU7P4X298JQdJ7gk6zkc4pbJsXt8VD69XEi6rqb63Kot5U6gpufwMz+3UG08n8tYjOpyflIz5p/iEUWEWOkGZ+VTPE+c4u8MMG29U0FloWgBzOrIp8ZVlF6hB/MEuq1kcxLY5A/0ewZtexmvy8YRjq8bB9aRtZzK8b/36xcPyvQHW1NS06C/Ezxya5mapzqLkruJykK6zTZj8lf4kBz1qFlCaNk6K1VLHk0ZdDDi5gj8zSMkhKXzFtMOJKC/jCI2gDKeemVT2Y2pkTYIMsPTvbDvbhg8d/slpOP2Nld518Ik8NojhLanrNTiNF+04azAk3itq8aDOUM36FM/A6Z3pPacoiOaIX68zCy0TSIi+0LgZmE8gUuNHuFb2mE1EVIWwefACI7wqS4vNBYb274WAjvPVeNRxkEU8xLmh+/iYIoqpJ19ZF2EkAcCjhdd2TeI8HnTfBC6sgYFprsSTGZQlIccnolmZhL5tBbr96t1bn9NqsWr1UlpvdNS+gaDrdAZ3xmLO8GwW15GrofNPtRzU0PxkPH/hI1+i0YMdcDiRguw3IWoHxSDyAHoxNXsErAHk/XVIWPIGTMCnSJmFRAAUMj9/2dJ+4M6zxdmpFULdFpKOAOsuUXXG/5hoS+dV/mYTE2j+qeke5DIc2hmRLyUTogEHxFL+rGNkrLvUwTuizZRI7CtYue6f5zSSClD6A0rHyqDGKvxcePWiolvBrrjwPv2aeIRgdbJ8iIUZ0LeAs9u8AZVAwTdfrjfiDSF7a6h+jw0i/HeQS6RAW/USGPLmZUU+gwDSynrjDBlhrCrPySOriYCj7OLiAEGoanFGNytyZaUthFHLSKUJOpNQBeVDSox6Zv4xZJKp4GWSKoallMH49gw0tOQVSRc2QimbkkT/GyVDMu/HPS78agwATAeJJuL/vOlYCqp2IIlHibaeqB/L7Qz5kFzCXvIoM7xKdSiGMO/o4zxvSEEkaLLm3AQIOGt/Acc7gLYV7DInAArX2883mDri/2GZBCBOxElEuI/DgkJR+mR/9uR13JKDyMkdDqRxYNJeSGFxNTdObqWRhvuVfIgLvU/68lfqhZUBCbzd4fQXDFmkMFnQwl5RIJiB4eOBMaBQJyJfzWf/6u2+/QhfYd8NiBR42pbv0vadrThp4DDYCc4A9aNe+/r/KG0aD7J+0gbUH5fbdMNlLDYGdvsqoo3jzv7nE2G+GBqvLHE66956DKHgLK6XMZrSWEO4VqsVXXvcMwYKSNfxNEqEnXM1oFXC5BBRjiDi3Sin/LPBAN8SfbQ7UncFbpZhjeG7wuOc/TOwqUHdmVVPm6VLC1Wdw0Vmk7884tNDomd8r7CqKlQg63j9+Z6+7jDeKKjTU1bStLrFMABoflNDMHlAFxAZKs7sMi+H16baBBnnnLsrJ33ulLR0/GzPQKTSbQ4+pdQIN7FBt/BM8ZSzHDdYc6ZE4uemKvk8ZmRuC5oSOSFh7CkaFg6UFJ5KCcW4QiPPoSra7pqmy1gs6WZO6zQvYA55yIsWqi9zv4ENPXcH4aWZKdhlpbUfX6/bRAtulvN3Ku7xqpuHXAqNfT6971bV/4tJC1g3TYJ1ZA9kwZVflxAh3UooeEEJpHKM4Uud74nrjBCnxIGiumJv82q+dMc0A/rOHisIDQ7msWziCSElmOEmCGbXuzv2KR8Gytf3bCPItbK+z6zJ/UsSca6xy8gS5LZoT6AZnFKIn0Tu9zGb585i6pU6ECWQvK+dbo/yvIU7c6zA7f0QvbCAsBxfv0pbMqirf2ofMJlWLazldFEE56NXGov9xzlehXXqY1uXc8KsGosuCofKy3Ncm6iBtyM0I0EBI2Pb7z3vjXW/u/CweNuath62ifAZlWr8TuaEEq6YJYGz/uHvFQOPbg5/0YubN7M0aQxaQCNEjxNcPwqg6EJURWjFcfKDk00eyQTxSEO/kTAA+7JLyC7lbsw7REcEnY7nJ3WW6Pz0RG8iAi8zHIcAKR5suNwE5JHLH4W9UUzURl43nca64CH9nLzCfYCSwDOdR4AohnURbXvoKcCiO83B08jDkmN1/mvU2yEfsZ1QBXt+TELzQgJdwX6SdDrhGRw3yMNpj5YHKzaziGYKifQiUeIlhiBmAa9QhorK/4n/dL+SQgK92vCBMbCAUvWQi8uEC43I8RrosE2Jap4V+nlOgUk2JVOy+E8GQkHC/5JReqtW71ZlbNjJeHsgUfTOeUMZNPOHcq3IF2HQP+r9mwLgLlWlWxfL7sD0TEP2qedxc6Dms2NMfrZ6zGXj8izc9VHgyAPQ3JjLLpSQIn3EcthvvMN8zKjtCqhearGvYNTn9uwg6aALP0TKd6bUFQBuQSiWWMw5ckae2uv/H9yAGz5D1HUp1TtncvcwN6d36M2iVW3lKiMvo/hl4vqg58QrBRIJV2tGXd5iBQbJmG87V8KdcqbQ4AhfURPFlwHePcXqGyRCWIxTpl4OFK9hRPXsjPrjweeKQYJ3ql4vMS3rIRGkfzGPBsn2snHAzDB9CohLzIe/D1u6w1MZFcgYwODVufEgbd60AgU+PnzwwgYyMEzFui+EsPUDk/1ETUFHMSHTwC/A03L67E0/IBEFW+BSlHMVsTOFkU9HNEiPeH3i/6tdx0WX7p9/LniRc3a+1Qv7k0c9Wabh+btVibI6In1xbtFcGYf5RCgjPFDJjNYRtSBzU6qa/eEo9owlWfrtfLbPiPwYGpKCTd300nAYz3r6wgzuSRR3VIQ1lCoJWYEG8PyRnO/8IERT/rBaiit499lUZx9NgBsM7p00ewod4wdC80oTgSxQYNswOXuuypqck+FOoDzXBvdZWI3F5U0PS8I3Cl63DKfjhGZ33Onht0X2A/AONO4c+7wE9YeA9YZBLH4yOjvIQSRUNYLgxe8dYlEQXWLpAP2XnfH2HTr51OXUgiAqO3hLpkem2EfPlUnP8oMQwvN+SZgNiQytsnUxSwZhrWMAmRbp3WJfmLqtPhH3ZjYvG7NebJZ9KG82o6zcXWERUWlt7LbvHZPUnISf8/udvGr+6j26onNv9l95/VdYkjNl9L4PhCRKuYBsttQdCUAEZNtzVjaUkLzZWn7+WWlIOrU/XMaCgsKuXXZBfFFx9t0fI+2k3Gb4NqdgfxHTQL3Q9T0ptg88dIv2rV1w5R4Cmar9rvqw+ckEOBDPYv4VkbhShBQGHTb8IKA01GEOCQfxDPa1TAALGae0Ym9ndyrdeEwC+V3RLC/DUikB3yLX2i7wj1lFsJwjglD9pmt1AmpE36uCo3MlwmSUKRIjSyANA8l85z4LJ0aGzIJ1alY8YnZxKwaOguz/DliTXaeIEoJWkSepAcPpaEPunAKXdABOTJO7Io/2rx2m3PXMD1UIoa8z1ZgzWP20YQwEwdBJTmdOaLjiq+AYkrGltmcnmVGl0A7LxN1GyTeE7TNlXC8PjI3qyJEhgKKCev8GlGVe7rsIH1CNXjecXhKGMv1g/pWDwDefyymr6Hu8cxfnu/SG3sy+BkVg4EzlwyCQd9K0ORUnRE0V7XY5kLoBVBQc1xQTwm5/J9asgqVEuT3g6u9xLz34vV9hoyGWb15o9Ko6HewbBd9lwsxhRkDuNx7R62w192b4UayyizeI45H5lm34EO74AAV9VmNJ0H2lB/SF3QQWgQMbczDMPefd7pMPx1/0fgpeO2gp0IWyAirfjbAFtdllkAwZlL6Crjh5B4NcOFw7PUOeu5w3ucwAWys0LlSJ6ejzvqIlrw1jpw4fkVL6fVHRXLqRAAvJi1sdSltw0ZiIv+BzZC5FHifpNT0BeS6+PgvkXCkm24rDqsPM9QqWmIPWedZ18u8hFC5OXv3FS+n8df0m426ynBAEmIFbOAkehnt5So9yw286/f6z8ThavfOnH6pL/wXoVtlSzugKwysapVuY0KjCvuJKyI5xBX1du/QDu9KWi1WCDW1iPdScLI/uxeqvBEYQUcsZ0BwUEeSYemaklKIESOYoHtdUgYPN0qTrXfqzMRzjAajjOur/V5nqQthzX6ObAb77Fpd6Bqh9PCuDa9vZNF7tkuv13h8PT9JrmxPzJEnbyUNoGTL49OLAq2saYsDksiqk5gl7XzvUF1ibvcbkQfihto8X2JDonQPYg6ElPB6DQ3KMEWIh8ZpIiCC0etVPz7uMFgAFDX5k9zqTMIgTjqxoMGfjd7p8jdKLuYtvrJRjxH4aAiq2WdTVvXL98XQuhKDUWevCTSEte9A8KhCqQfrlww72OvVo66dAH29/PIxQfC4dJw/Q9fT7My5CR8jTCGKjjeYqlN1Ku24L20E4fjFPV7qUgTrLFXy55xNaGu/zNneS7t/sCGJkOiMRfLWGAfHR0BGg6iYVgB+EnYIzRYJ8wdpzIZHFDHnXYy7ZRmI1FOZNQLf0xEmIvZwrcN1kG5GT9cxMw0BBDWtpSb7tgQXiXYjQVYZ9c6r8Sb740XE4oeEf0Jtpes1mM9l+Z/lgjwAkMguTGC+CdHtcHJNAahqvzicMDAynfHAFIN8NaB8qRyDFuzVHMuDQjodZNHZS/OxCY1hloJTtpeqgrl3P5twNhbpV1RTnbNdTNSavauuEn8i/DIoMf70wUZI7p6m9xLXzpCi/ExcHS4OtEID/LubDfIPKnIS/QsExMnLk6gRUDiog5tK5xssG4TaMWT4o/xZ6Qr20ni0y9AcgTHkp9ML8CLSHgYr/Vy3meqdx3Tfh2cEz08yb12ByNCIGFHiMxem1k2W79rTHDstbq4u/gEbS3QTFPR1nXwd7bSXqfZIueH0HWqJfkXltcHOgOdXFYPkO10OOJxlDdeUPCVvcxEjZkjI7/knP0vLHDqJ9L6EUg9DZ0+7+M9iElOp7iFWttWMYRZg/Jb7fEPEsowBPaJgn7ttjPiNRbOrMrkVaCuIymYkkYHGh078P7blIPKzDKt/8KfM+Ouzx8lHSFOihr2QJGEWm+jqh4lcMMhdpM6zRhjEqwzPmDApWV9QXp9fPgkAgHlLGrG80NatEYFOgqwmxohAia65GViGf9xwLdO/kYPr/EbEZcFJZ9in+/qpBkWuBObvYd/9H97wp/L7z/9gTlT2qWmNmOCaqaRMviaj7IMGzxRYBgcLabKPTyORNi/KoKXB2c702sl/xdofFoD50IbbL23c3ew2jAdc0qtSiWvSYTNIBsSq5of3V2wSu61gFkH+flzaXdOHPCcf9YQb1w9WaZDawsRTr3ED7ThpbPtMcsnWG6G8Naj8crPSqJbe3afyznbT4mnMfOmV3nb9A6Ey73mY9DqYWDD4yRdcGG1vPWWNqlB21HjvCjB4vau57KSXC73eCNXA/0=,iv:st0DR/K5FXpEmQ8iLGrW6BkHn39YTwnEO0aX47ZhLfo=,tag:JuwZlALa+JV2RE3jVV3whA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T20:57:52Z"
    mac: ENC[AES256_GCM,data:Cbvffzn6HcUM1Q2kMNSQsixXA5FVkmdT41PwDN43K6dJi2THIacu3hWHALCeH23FPSjM6G2TNRCFe6nF8qivBIsNCz9nB/uUEKFz7HCYQZkbpza0H22rv9+Kun1BW3SaydRpk29L2wI3tG3qRK6M/xhekycxbXpeqaiIbHqoSks=,iv:XEHlOa9fDB+TPmHN6HJyHjmdFs1Mf+U79M5ADwD1Ym4=,tag:ReEnVfcTzjmz4B/vMEV+eg==,type:str]
    pgp:
        - created_at: "2022-03-24T20:57:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pARAAtvhO31vUnE/bWmD8usQYEe6cKNWYWNMvgSi4lX7Wk4Um
            rBB9At9Uj18mva0nRKHx4LVJB8/BXm+gkgKc16nYIzrbtxaafvcG+No0jpN9eK8k
            v+3JFB+f7dE5dhoHmItO1Y890fqcEPHq7OEUxMHOYjubHmS3llHnbBdfSb+nMK3I
            7SEcOB1KvSkl2SR6cXvNMo5pD7egIuvjd1ui8HYtoFAeg7gvP+FoInyj7v2rarUE
            RJ7qG/esvPyVTsM8aWFd3XAE7fHYh8l5f9gU+38r0RZAMRz+YyRWp/dWqRb3Lx5x
            PxL06uEQIIx2r0VnoMvEOva8Z/rpjHJ2/pYG991/jtbGDZ1RSFggyerRJIciDXn8
            GeMeEzKgdwmwSYENPx1kbXZP10Ba8aJzwReruASVEqVbeCZzW2XY2Wmbyog2zCVV
            rOy1YPuDSK9IuiVRsNMqdVsWwdLsh86tM/croIBtFvBpevy8VxeiEnVLILd7qN6f
            Zjd70qrC2nhi+JScORLAL92w/kYomksd2nT0BIV79bVni+kaD+EMhwBWd0IQGQvT
            tof9KGSy84XFAgvA41p2qvEyjUppD2bjGErPUQDiSMfnccI2nfDrlVsJpBJg9tVR
            EUBWgKNB2diTIrE6IzcmT1wAV8BoZ82FqQ5E16+brJtVK4A7X2uT9BNvR8tCwRrS
            XgGEPqnV66Bik+w9XoGe+UHsV8oH47kZenF5n+niDbzNgcUIdyH2i3rsON+wrOh3
            qeNsa6lGBubDxpvHIA4EAmmXQup7HyQKzzUxwOiPS0BZxUop69uALHByJF0kHa4=
            =uWxk
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
