domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
            data:
                count: ENC[AES256_GCM,data:QA==,iv:1/pUENFMJCz+AIMLj5ipaGdyb9dBYJGVbXdpIxaQXTU=,tag:6mk3Q2JkLlacmwhsuqRzUQ==,type:int]
                persistence:
                    size: ENC[AES256_GCM,data:VmLw,iv:RHMfMRMgXwoP00P4UP7N+eURiqJp0f2lKkxtwM6K8WU=,tag:TCzD7rLRZr1m1oTAiaOZxg==,type:str]
                resources:
                    limits: {}
                    requests:
                        cpu: ENC[AES256_GCM,data:eyM0,iv:ptK6jWOmSKK2j91LDV/9L13zPcvscE5aVPq2Q4BZT6w=,tag:H4BDPce1XnKTG9x+BWsNRQ==,type:float]
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
stringData:
    gateways:
        public:
            tls:
                key: ENC[AES256_GCM,data:XSruyvUBNWKgsp0iQCCkyOQmsMviS/B6MNkfAYQmMJv4wkq8m8vClddnzThvgVb/LNwbVOqPPWkRGFPA3cMXW8KQykkkfQ3bSyKU6xNClYKBa9ZeOjPjl/ZCCWlpPx1lES803/RGXVMfjBMqm9XoOxBgEN1/CUnnr2zIIFGGgb3nqHFwcPoM8LUa73VDyf0q780RDaXZbL6nfum3/+WU3mGXXwwCThEv3zR3XxyoZHyRVUg0FdBzpi5cnhBz5Qj5CgXz9Pworz38/3SN6BZuB9t2EjEnDjxWd9TizITYxtSlGtkz6Z6/GtXIAqFQlOCkWDmHFkcrrSnyrzXhxGBo9lFU0ya0tbzGLLDNUGWqKpzCRAfw9kdh38m3TGxFeIQLfJLqzO9dCQ7uRuNsFQUROtclEfd6gOcdl8FtImSqLqswfCyhvUy3zzKBitYzm9HW6EL/DYVvCsIRH1ysxDZEa8l3mu40dWx8jX5ljimHD45T1tND9iOEQUs6Mk9MNBgM1kZnOKoWhW9vIKVzGckUa+qgVoKIkY+KCDXlTaRpF6ZrCaMoY3k5EqS2RSDl8OPpB35mgwzEk/3ohpV77lR0C9XkFHNh9QeogpRTFPVLk75FdPGaBefBV0DqrlGVDG4cVJ/LOND7OhCy90mreOdtcoTgvJK6PN5zooOgsbV+mL14y++k8o7Ajkyvl1XbnaUBkWwuv8eoYykEa9ac0TtavTeuFNSA6OdZT5Ul/p8wDGIlDcccL8mjVzOYhNK0Bh+WBiNUzs+N21T+pJDb+wK+D1jWjYWnbvM1Vs6QkPabXkr0YPOBNVqsGFYYU9qFd3LNaqwJWR03WwLw368pFIUzenriUn8C2+YX3gm78O17J/FamW+g8i2zcC+h9awrCyQlXdX7LC1mFqs17quQjmgP8Y3J9i0UwS/50cJQpKw9/F+u5BgqV4LX2nJi2gjNYsA+mSHlw/vFiLAMp2QsrpO5CyYHhv+zZsKRKeEbtqIm9MJMqkM/U4k7X0Cph6rxsIXX9YC2Vzmh9dZWjnlB9Rw2YvFd1YTvpVtG16VijVjIPtA62ZPFutzALPKXQ2aKV3Dg3ljaii7ZaQrhJx4Ff/EwPPxKLONW8mmJL2JB8MOchtse3tj/pnHzVEaSYooc5U+7MG6bSokn73UUOXfs4rvxXlcJZLwFC5PomGrwE4XtfvFysmNhb+taVDw7De7Vp+OyqxrhFKs8gDF+Bavr+HxpVmh4YJabncbn/zdz8L6gb66RJ5VZZfKkaAqMFwI2jJpcvg56GPZsxJIylvIPZVwrBDmJ7cx3RMNiv8mon8B8v96rKPfDSmrErZLsZxW6P/qV+Ct4gN6RJeyTMLE+OvTBcz3WLda4B+K5YniNa2d1mvUYv1CespxzscLJyweKNA+eR9SX4uxwms/Wz1U9kAf8Im+s11tj7xvkFmoLI1NqPBGC0HFh1C4yAuARqIhaRQaW7KhHcrGnWR6IGh6V4vvw2TgNAb9AwBJR6g+mznncGe7THNzhN5YPIPU8qQxRANDu/qSHVT7bCvphXU/YIU+/B86oz2vX++qICbUl08cJ5RMQJtBB901rFlpAHmbznBp5lltkbtTL4P7vnOFZli0oVcbyHg6vujUGvncKvGKSwiocOac3MdYQLkZFtRGIKXkh+B2Xa/586idq/dmCg4yoouoe/yBr6E8oelifsmYh/gOYlPXlJoXOfAhy1Cupnz+wAgVWs1dfHSZqKXZwwFh84LhS5D9Zm57m4YVeKvjsdFPDhHFdlrNLsTWZH89k5OaE6kH7hWYz31t9Gb0yTPAJrJsHc5qDPb2YKifBq16qoc4NAxMX6rvamal3N1jS1jfVvH6lCJFeG8ROONhxXoKGfSEXv4+eJIRAoRwp81ZYMMg4LztcGImjtT+zaefVdHdk/sjjySovuaDZvAsvQlRqJoX/QuF1y8BGdQ1A4Fj86AElis+2MJCeWIsjjbbJbdqF62JFCK4Omz79Qghp9qvV9UGtgjSxLWY0ndYypSkYg83ryMiItW7ge4bHKYh+Rf2MWhcumKnnAiwdMMYFv6MQK5cFpeDlBdHQMD5FSULQrLczCS39eMSqQ5OIEZH8FIKGlwWoErO3311t9jdkbKgws68Z9O0jwqdGxyPRCve/+kID0c8yLfVcD8MQsVBJeia9xUhltDvk3WseasICw0OQNodC7RxBc0+vqIbmH9VCq/JWtJrTZWmXKQIpDOw63VQEp5bcz7S8YDrf/CHVmOKLPJssBrzB7LgUENtwvD59xLVsTKz7YgHrPyJuRSY33pNaMIrrpYVoktmmfJCk0WJeY8Qcy3FuO2HcIPJNbOZdPspWbx1nE96WT/thZocm3PFFycwMc6ayooN9Jt4k2KaU8afwfKPYFZtcCKLLu9EUaoBdoMv09zrbRNblLQzacXkNRn11Fn4qH9Tsd5rGnv/UF/fFJEVcR2bxApo6Ar3DfCMr4BME+WseN4WRFrDEQq2Tu+y5GZrk+TV7zc6MxY3ZT3qr5ugurZ2J4v6sWBPKRXacCv4JvbJPyYa2fLA2r3QIN7/dMIvYGL4sMXDf7DTH+M/7g9ZNYRTsoaMKQujuOMqZEnypr/qkvcoK59MuXnnC8NnJ51gEcGhTK5qFApa7jCjCAwfSFc6EUxJ6O2fbU/UKYA3q3x+J2viE75KJJEuRbAMXCVc5Tc3SZfmjC2Ih+rWM93z4gac+loaP5yw9XVkEOskZiNWYw4HrlrS8gxO4u7aMsgronql0eoRzsG2NlwswqL0POjWV/3OYh3kniUlxMK183cRrEuYupW+vNzXUkcrzRiMCcOHvMTl4HTShbEGnoamD7KK4rpnAXB7yMDCTdrhjXNaPsHXpMzESxNYeMEJFmq3yMaBulUkRaCo2uN1vST0N5AbauWpYeyJvo7/vRS7hB7Cv85W8eNy2Q1YjypRHv3M3qj5PtinftTEWbBgn+nce3RRtgxrvYrGnjaQ=,iv:CbzulcZgvN7+p1zp7cDn4B14aKgu8fp0IHmqFqIDhsA=,tag:S3N8QuxJDjuj0F6DUsvdfw==,type:str]
                cert: ENC[AES256_GCM,data:1c1hb9/dwF9cmx53dyhTJ7715FjmFjOmtNaWXvxzZlEk/ie4M+IrpIuyT+d6vcr3pRd7i+HvIa5QdfKsK+2a0p2sqpkntP5qkbxu7hQdKNdl/i/BrMGH96N9BJAiJ85N4hUHfOT7LfbPOH9jmhcPw/MLX0XKK+QAZeRN9G6QH9Emm6YtAkVFrwkdvKJcj2WVsxujud3QTrWqrnWB3TpJX+vUbNw7WeFhRKimC2bbAac57b2Jmb8mogQog+JuI6Hn6gmfyIh0baGfoFzYYUUOOqurQQN2rvCI5tvKkbn3bNtIXT/Wu0UUDF8npUwKsEmkGlOcRTDbcjHGeJrJuQXTnFnjBkSfdme5ec1JAgB8lkmdwMz8wvuZql0H4n7Y1fXuNhdR71k8KYoJ9E1J8XMDga4xzcXhYPVaWzaQv2OJm9PFzPxXlVRZxeSOUQL0TvOcvqGgQkBWhXR+jTfAoeYdocoKBQohlx4PhPuIG5/3AC5gMYcoktK27YEnRBTf89/VLSt/fHCKP2vgPoMS+sq/np7L1/cTP1fTtuwXbFumljVNcMALxJOUrdsSVfcUPPCZXgDkfSVF5VG0TxzYvhv2HjQbSQH54V1OJojds8yzL+g4msLME+O1Vm7wtjqqujTxioY+HbTwSDJiz1W6ekJycJTtIAFnoq1EY6kL0Aepml+Kl5WJlCE92GuFgafXDtKcSfV6xpE2r7oZLmRIJcE61EH9h3NNY3PF+CD8FXXefb3GZezZ6dGDPNSiZ/RZq7xldvIiJ1wLQqjkcbPM8rM5p8ZxD5Rg9pMh5PtLKZup3/0u+yrOdmVApfprbH/gGFZ9ariQZzV+lfLvlDe0ZL/alCYKLcnPh2Eon86UNoOsPzWMmauZpRcWZMGS8Ty09CeUqMpj8J01DrjkW9m8zzkMsIS3Bzra2f+XUj+6VTZpgM1wGYteajNj6aA9pghfPQ/fjDdvXOe/SDEGJEdJia492oTPCnZWIQ6XwC13zfKZpE+Rb+jwdeI848XBw3ffTJzYau1znc9tvwXgq0EkhHR3fho5l8g+71CZ4i6a/uYx4xb+TZdjBrvdQoXOYOm5ys4uWYvibPAKHQ8SYsisnH84T7pu+7I24vXlRStqrbZ7jJNziR856/j1TnKnTY7STzL4E75CxvZBR6DeiS5J0Ok4G2+2SW3ojqycz/9dNyiO7wlJ7qqQaWBF4qCDXrKIf1zu3XMxgfYPoa7APpdf0icvi7kzeupyGDTGMlMymG3XP8EMStyc9oGXOD2IzvufNjiMt+SNkOAFTqY67pzWBBoToxsGGrhtUyoMVPkAeOGKDW9YgGN0sW0B52izRVDfZwizwt22rLXoabQTcFAyOUNDwmgiVuCxVSjJkxA4uW6sNQCOhZCzYEU/cakROSCMUgtn89CGX+jVaZ8VbGX+UzQZFb+1RL/pUgIBxkxW9lkaXV8KZOjNe6mjCvul2uZWYK1YLIkceDHEbkIT9c7T79rgezjXQjdBMVg/1E6slBiqnim7Q/NfACwF6hqyYK/FQFxmOKuuYlAwTdeq9IRSgqHBIbh0WGuZ/AO9yEZdC3srAJJCOiaQpIM7ocploP73aGCRwyPJ49wu+Lamtz/ZUjMUbrvrGdxfpOTNufm/bQdbFfi1x+D+H4ZMalAG2CduO12qMwjkxJ9uk/MMYHHTcZ1Qt1miFZZqeMGl8oXbY/dThueKlcB4ZlUuv4o+nIZ/dzMfBbmgGNW9t969fQ00U4XCtFYSINuvXeXV18oCeMpJQPnM6LOsG/e+7b9zsSXICItdRhVAEby4IQQl3VFvJl2iYjKzz4o/6AD1ri5EFLmerSx6wZe0PVOhw2rvn3rDP4l5rMufRW4P0dwf/OR8lhsJzE7qAEoBgDB62dA54c1OofrLKirUaxWEXrR7D+s6HyTKmSmPUFUR2i+5XgNRtu/xkBCw0OKnSY/cnHGhuwaP3zODQ65c2F5cxkCaiv2MYV0eq9yJQXqv91GpfF0MEsud1+fvpCMN4cqJRFPJ4iBbmWFsGcoPeFzOLKw0T7ms5vXqASrNseP91mN/bm37Pdy1Sz5RVzUsYwytgnspbpsz1q81tPc9HPIg9nhdqz3hDNIztbk0moq5yHB++mbzaGunyiEpHPZExbpIxQPZwN65xURKM+XI05htdHluw17IOxtpAaco4lgDqidUbhJUOG+OFK8VbPuC/0CmKsFmAZKy0pFCSUZLPcuQ222k7v6I43ryz7FVgDw7Lte9TiOk6fM9R/YKzHFmoAO0//YIeZtoF2d/4EYi8udWOG+rXra78SoHUiXOzv9gnrbWCMuC+CjI91CB5Gw=,iv:V8AQHN/adwfCj3AcGZPhB26QMASYHQG7anhphT8GhRw=,tag:kXkZaV/PaRRMfrQUg5UmfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T18:37:13Z"
    mac: ENC[AES256_GCM,data:ovbLpyhi/yUcxo7Vmgn29PvwIfQ71TYHZ2ff2r3CtAGQrXUSAX0OXMMTe8+USzBgp7Or3fKNevEUYttpu6pqHwflLt7GCpLQ5IL2fVWO6/omZwru5t/G0KMbilEtGNcWIbwnq9nqPC2ylrjfJUfq/wRPk+QS7g2GKO/zTLxXg+I=,iv:KTeFdL2oUxyBmvhscvHsFXd+ldzVVCO25b3uYEHF9vg=,tag:7myyC50jzccDgtMN1A5QYQ==,type:str]
    pgp:
        - created_at: "2022-03-24T18:37:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ/9H5jJHC9icv4Qb0xZvRg+RC4AazPs3BQD7GDXKdfQsvt5
            iaTrBf5nWM1/NeS9nCHSoapzhPcVuizD3oeh0ZmTpF/lbi763oaYm6XAUOFnjCWm
            8uKH/HBeWVY3S5LIPIcymn6YuZDpPG4IJ8yPOqx7tTm2qbG5mI3lYpemE4Eq6mED
            MhycJzfWYGAzugRrUEw9hIUkh5R58EBnYjuqvw+Ywv1NH8XFL+aBtSgLjxQDZQGw
            tXQpsrJ2WZnR9yq4D77iwjWJHFmIDF+erp2kEH94rrckaDjqnzRsy09xftQj9XO3
            /U20x8vCbEHcJEaMzYR5d//PZhb8kU9zGNh4PijhqBCviQd4wN4Ga74jOWKKJeVe
            S9ewKBluujKwguHxxf7TLPFLOSJMUUlQ9DSzboq96oHTY8CsLUuXFcXsY/x46J4p
            ErspcvAubmsx896PnJWMY0dAz4C6GKFsqTDAFnoNOwf4YNdw4YY/08B8VvjsNrqo
            9+/Ynejz2SesOyyuckaPmEOo1KGsw9tRG4cj5UldVqPM8bNl+7CYfZPjWRQIDpsR
            kxIQdg+0FErBlE83w4jwcqAlXFMIHrzivnU2+LFTTJJdIeB/iLX4kh7j60DEdnsO
            /K3b0P9FzOpPImI+B+saCIVSRmsl1Ufw32tNd4ks3OuV+mYujYlnTV0oXEjuT9zS
            XgGJle+KcB0reD7QzPB1nFR2+4phdlfFQrsMKB419Da7dv6ow8p2ewhaXSq5J9+T
            jcdKudzPQggoepITrZBz56GY1HPHouTR8aoHCADMHExbqISXvsg2b+F3f1/mOrI=
            =b+hf
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
