domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-25T15:49:30Z"
    mac: ENC[AES256_GCM,data:kBkyNiEZbsM8fueveusEHE8VEzdTukEbamjbGO36y/pDel9nt/SEgIBzN75Inz5oYaBZZs3FUjVzHl3p0jRHeCALei8DIYPkAmurQlUKzNvmVtpd3kefBXDZXg0sYcCabMljpijUUNf9zQ5qlmaf3FvoQKIG1XvgBNKgHrvMZsQ=,iv:47H/KOvmvvVd5qYnMEgQ+XZpRZXX341A2wnyW5cjb4I=,tag:nOTs8/nWueVUXKZx+R4fmg==,type:str]
    pgp:
        - created_at: "2022-03-25T15:49:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ/9FhPnp+lZybeP+VRJQ3Qdo2oUE137qkRA3xBv2trNmFiL
            QxMRmpos3pWWZUXeBbQ+qg/7IY49GP/AmLro3CbmdWtRzkZLSEvRFCHNZEyZoJyS
            AZ/FXXZq+A4GzEJcMawDCAsK7Z9XyadBsqI5XjEGXEtR5OIxwv6dphJDNRo5jrod
            7coRVbGyuOSU8cOYoQq3vyeU8SuE/SKJErPEzQm6VWvUsBxwug5oCdUzIL8+uKPA
            LGkKUGYXMfrrp9vyHuCcWDcOf4A76/DeR+RxtuJLPxB6UBd/ESxcOpcX2aZQ4qWF
            J8Rvc3DNh05EzkRaejJSNE/HtiENphs0gq7mp69e4axQ+bvEGSt+HPX2trAwOR14
            Br2JWgGVxlwV5HVe1d8ifiqIP5+NRO0hGqN6nVTGxa861HzvD9hYlCJllMbTo4ej
            +D3E8VH+4dZm788xn4Tm2QREbN5XmG8CXGSoZM+jMSuToZqpZ63znEiY+/CW05oI
            NQRtRY/HY52+z/x+Ftp+P2JfGW6gZIdGwWVDc11mpHZqlVmqQCRsavQ0B4wlfUz7
            YQa7yUM9rcYTdDctsdX4uaELmiSs0V8ytVx5p028YrtH4aUdw1MaElVadIuMmcCf
            qcevSjn0OayfP7gvWRJcFqMBgYHkDPUFvRZz/VquCqBn6QvnT0u3JhgHtIf76TnS
            XgE2K43bn0kAhDRoRqPnR8W69dhbX49xOuYmOyuK/fK+qxIVnbPQUoVqg6qEVyZr
            1TADYH0v6HrE2oiVNbQiNiAStALcGeD2SZpa15sdAEdLhr15x7BbLWRRf+2XKFM=
            =SzYF
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
