domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
            data:
                count: ENC[AES256_GCM,data:0Q==,iv:kEoLcONLGhHNP4VEu21H4yqbboCg64L2Gc1eVnJKZAs=,tag:h6SRQXwlICSt/hJYSkwqiw==,type:int]
                persistence:
                    size: ENC[AES256_GCM,data:ceGh,iv:A2VtUeaBzU6U2uo6hJZg9OB3y88/XTQE/l7P2SJRswk=,tag:JGyCpYHQwn/qiRTxDUeZ4w==,type:str]
                resources:
                    limits: {}
                    requests:
                        cpu: ENC[AES256_GCM,data:qlO5,iv:FE1MkqUF+r4KgO72xfF1+hXtco+2nL5Hmv2Z6BNK5YQ=,tag:cgZy5IqWd9Mn7PxK+rT1PQ==,type:float]
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    gateways:
        public:
            tls: null
            type: kubernetes.io/tls
            data:
                key:
                    tls.key: ENC[AES256_GCM,data:byWqJyYmDu2KDFIHWSDpyF3yl2/wuIFJvry7a6s93q+e9wP44NSYT+VJqQKmlza95qh2gc9vIZvQpSpg+jL6E68ZzXVzDFd1drJ3G2QYuo1z8HZ0ILkC6yH2+lq8V8CdgE3sfqhgw8jKPJw0JVe5F/7c1lOtvOJEUVS+aa+LIa4T3naJRDy1eO/mToh9w9vmcymsaEQKJRdrADCCiFaqJvX+twVP0vC0Ac+q59i3xBFtPl2QYQlx/zA2u1qOEtZ7E/FQ190ZCe+szLuhfKH/Mhvo70KwW65FL+4Xf3jkrf8Ix2qHARTUN+t4oHQwtV5yhZH2JzHaOOrBsp6fIXOo4hedxZOGrgccykxHEH9CNYra1nxXriG0hXaW6QTsoJjS0P0dnz7bUTeoqPvuIpdIiWWpbiJABiC39tqLun8H6hA6b5/DVUpvW+x2Ha6Jg+zWwLfeRfpLSpZNvqwWQT4/RoQaLvsdjj0l3AzJgmfWkvTVCK4ERTyLqzFrrW+g+ToPV5FVNqcXNdRqLHTpU/1yqzETTTWqfjfk7kYL9qJhb/YFg5eo2PtUyM6J0rVlCcxsiFss7oiwD5OzvoLTCHUnlswNCsBQUmJrgxIpoGosKlzI1yctGQ1tZKwFHJeUxUWOZD97dCMn2rmzyMNp8Vx2NTdie6h3a4wEwXJ/qkWIjG83/bQT/msXClaYJxunnAVJIR+/oE8pCA2LubogM9KFevpC30s7qRaPCWknfOh8lVOiEFT2d4Avyvr+WXg/9p+SuanoO9VrPlQUQZhG/9OOGPkIGSwL+jdWVdbGFmHaghj0sH3YXO958aokt+g1Z2YZGbDKk/TAUa6VIVsMPcg3P5IPwhmwxKZPKz697AmezmVq/dmHmF8lth6htV6J3i8x5EfNQbvm7dFKJNdNoHkAV/aQOkQJk2jKBhJo1+Iq4JiW93P7zHZeLQYZu3Od8k88XDVO4kd3S329Gyigx0krNf/tQjcpINiOgcE0y0gTrhXAvm2tqjXKAbFEW09rcqmpDiOVQJT28p0MWPV61KAnqnKRvb839UBZv1ZBow+S8UwT022juLcYFmmRRPTdyArvcMwFEXFbypAVvGuY6oT8qZd2ewbUl/WjEuuXzwyepeygUsb11uKEnzpuHRWs+XsqC2AEGLaBYe/vWFOJIisYosG/OV4D98aQFlgfbm0iWmHy53NnI6zb7taBkGhXHekvZNT51qM7JL70zyw0Ko+3aImiGRAFC4ga1OMlBH7889bakck4Aovw5CxjGZRLwOcUZkzY1GIATmEr+qe3sovQeVPAor0rCzBBWDE/TRuTBYOBg1SMaC7IbRz5y0lEEBH/WBMXCg2jab4+D6rfFgMgQ2gRYpsV3lKAypnyg51dQxHHWs4Pm1IldufIx2S9lO8JDxOR/5VqNSln01F86ez33oUFHu4Ab6qmRWEMPemIZSFIJqsOV3ldj11H44NRvjMxhyxbCSjg7y7UcIkwQuNKB3gWw0VsiGtXZwQpPCi6S32PlvG5gEzmqaFuWb6DX10lzG+HKACvqVktKvX/16RlgqiNEa4Uhwzda4tgDJ4MQBv0xtO/e/GVwwXUyOL/nxCiJO7zMkh+JKc5cMmFqEefjB+MzqB4Wi3mqg8NPzDgWX+Enn9CByhc2/94TrmdvSZ7LeZcydbU6J790jocOjYRGtmg6RkyEI/bCz+RlcWrukFLC+OvuxWJ8oxir7jHHBQqxrpGZv21sxpsJ9PlQZ5ksDpdxsxyz8SC/akWUya68B5w1zMaXG7UUuv0B0VT4l15riwrWiUOln0+/uQBtnxtO/HxgMi+dqjomtlMpYTUdqYwX+0SDoQfWIZjwS6J9oZlDMOVC25xMaM4dl1dcr9aV/raWbK/T5zggUItuWsgyyQGHmMfBx/dUbi1bjI/8r5ne6VvOg61I4jq7nYzjo6mri4Nze7xP0BYHsWdl7jO1f3zzMKM1uar2UR0Big3YlKm6LYZBd2mofkuGvgHnNcRlqAg6tsSChWf1S92eJHshH4sP+D0Kv8Qa8aXb3JV4ECKBfte9NbozsTqn88pSS+1pRKw5sjYiddaE6uJiKiGanGMlzyCKIFg8nvYGqLK/prqpf+wJCP5SAU5umvsbcvjAdwFLRA9K3QZ0wjt5+1zZDWdbXpvsUnpRxDhk48KibIxjfMz/9HpgDEiHdjdaCAV531loeB0TunMpaC+T86a9ehDDP+O9rUiqGTKdOS4+A1eGvSwPSXNlF3BDbqFDMtO44PAzyzEMuaMXZHTEF9VDaxVxaV1Kaicg/qfjzGJvA8J85eJl3mCadIg6FAlaavTN1OFgFNv17J6WEXB9R/9mh/MbdgyxCv1Yq8C5UCYSEtDRIos+8GAPhq/LIoc153My0bMsk+N5BGZrHWSnLDqPCDJDpgEniw5nbzyYaIOzYJe5Vy2nH85ZaZ8CxrCm/HUYdj4JW6bZhKlapgXJbbjWiXUQiJmvhB2gsPawVNoLcuPsWF2Xy1HxEAVUuw8N+5NhkEDcWkpyhuuSrisrwc1e7JKkGCwpUOfsthMhq1MtU/iFLR6rLjZjSHrOtZ5+HzQtMeXJGIm6xPTSrEfck6Pt1nG2WBeWKHpLS4FpMZNACySTu+qZEpwW2MhOs/AMIjyDAlYhz65KUOyw2sR5P8i4NpfEj8LJfBn3d1u9I+1k2CQa/k1SgDGDjUnoxy4Fy+kgBDruTzgtXaJgaYAkVKdyjZ13IQcsBZxgTyPRWYnjwclxqPeLjQzg1905Ia+A1yN44ANCagHfNSIG+5GeItIWaBwEKFLcl8RWgS+7E3J3qEtmBvYSGD4guaawhY7pnDT79tzuRVD8I2PflyFdpRklrTmvz3hhULMCFRT8d45Ll0x9uHKJJVm4pW5MSzeirKgf//A5J5zsacA/0VapPTDcsn4LtVSnHkMaikpqosWyUJ1SK+jRzCYK9QqPrMOWmrc0a9rsFWXjs2zvDS3vkxzJ6s=,iv:Q0Nk6is3kHy8yMDjnY6iLznTBneySVG0hiADd6D0yPY=,tag:/ABt40F+yruwS6fg7khvJA==,type:str]
                cert:
                    tls.crt: ENC[AES256_GCM,data:GMDT6R6V9znjd3roPjnVHYXtvJGotCINzeUsi/4EDElb4Zx43k+JfeYPsBdpMYhFu83ThK5+TWeKE1NarxVO4nBijVXfWtrPiFeqzcO7QmHZjVBC3jicpgQwJu+isqM53uZ3TFHRylmWVj2CxvY/XrJWgZAj+7GqUbkuxbSCeC6ZdVyc7YTOz78sjCY9wAAri6ti4rZbOPdSqcmgWBBV1pKFsZrExxHRUduqGOtHtrDIr+CVSJfx/cbHBrer1pfst6OiDRocKzY9SVxX7Tv7M9wLn2XzSYQjETPOeD65XOQOXkA91VTwWmf4K+YXhMuUurNKdcAhADAy86aUIcpUQ9HXos6iD1cRsAsRkgefl9C6SDqJujTJvmoPqJwHSRABODKO2EQ/ocokxz0uV06C32gKiCVuPrVYDtwOxO0qg0C548+Xohtt0BZr+puAVaU8YCnK8PbuWuE3DSI2/oAa8knJ2X1hvi6v/gO6IoQVrUWWAtNXFbeVcxJvHMWDnQzddj0bP0J57rbGBe2PtlTkML1OIbuaOJbrGwdYMMMNfVv9c+7WUrl01UiVTAF61UsmbUzk+Vn+gwJ+YlDZLqAihuy96bBwlHvIo6p1eTIGPKKdXy42XRuBqZkdiM+KHm6g+Jk2rJfgGjQNGE/WSovCT1yihHP3JrS07V9WbuEBBOHmJgEGr43ozm6ReGb8XZYS9Bj1pA4GXvfTv4CoGBk19SpgCn8Z2QgkUzMIprZ+gnCXAK1IVihZ7+RmBXhFGnsy9hxctXwqqAwH8MPAMkAZT+aTtZtBhAg30nTE9Zuf4onm5PEvNlbplgxpSG1j89BMtBo058cIoeHN6jZ3KB6eqb8Jv2oWLDZHtXkqqjt/2Th4zjX4iiG5Doq0iR4OtNZPh7xEh3V/YQNGYKlSPUoyFDUOcQYi2oh1n7vwonptWgounib/m84UGZAn2aYwf8zZTIZOO+YUenPpj/AoppMWwSsg6amRTFgiuTq76kZ7sRFpNRRIXx964ikAbdb/hocQ7+H0eZHTvrEq+hPBZhk4P+vebj5BgiXJFXfot0sQgZugSd7NSHJglLNEvSiQtGOois7rar9+i8/4Dtr4T2vBEr2ABNmsuF2dr0n67qoXAUzWhyAoqpbDW3jtUzgBopxSvcz/S/q1wNB2o3zE3Y13JFEP87msBomask5XwFxhnBPhgyzKRaxJIqwsFCiQS69V+rZ1RQ1dcUQ/8Kr7673wFgE0eKSm/s+J7KuttAzuAOyDaey0OYbgzcFWxmt/PWoAoYI1LZSaaZ7p1ORvD2U/A2Eg36uMBkcvb7hwq8o5etWzDwVkWfG2mGqCaKFzUXeq7Cx3RmvA73y/LS1R8JkSBBr68E2dreEbeyPALWxiRNax3kq5NB9DmtH14vH+BHErv2soH84Clo3WE3sAWtyDmjEzUpOXHuNU0kVku0fIN7dRl2YJdJko0jPTvatvONr8EMs3H9Scwp9XI56HF6UBnChFLr07crX5W/maLY9b0qdNZD8yNwgmY6JiDPJ7o79LMTuA7Q/rMeQfMoEA40X2iFhl0kC2BrFXoyz2MvmzdfSRPAkLYjc3kPtSntUAFDGSIFLebAm+eInkKwyo4jA3EnR18z1fHkuMfbzboWrOZxCWWt8aInB8KzurmYEg0453YSXkziLZjzo632oXFj2cYfp07+ViMONNVG9OJspm5huQVBQmtTT4GBLNITD9sJyJ7xH48nsTninAaJ7Zuj8pxrpAk+UmgPEDAfmVFe7HzGN0crgHEnskFj3V40+xcUQOVh/NC5w1l1WQO9f2bVyiEZgOKcMTN9yjEk353wgQp9DFwDafJRT8RfiWDc5MWI+J8/yl1uv3Uf/HOZiac0WZgWmGKAs6Q6kpdTQjNNC6VjxG/1sps2vDtc4HL8rh/8GoqSpJmMyIZ8laPg+431mKN4eX2lDyTcbzEdJqv99xqBs2goUKdyXnLqK2ol4G9+qO9e/p6Qa/+XY4xaX2JP3l4hDyr7gtQfmHf4GbNEoc3mIsB9RUaIzg/GJcR6Qka8ahkc6JrmQsY0Rq1OtdTytwjZ59zRJDS4cnZKRfcakNKwr5j2TUKuupqAWKKj2DXerwoNHQe3dYGNBLV2mGRrGuF4Mo5A5T/3soWFK2DJCqAsSsybVQhHSPa5m4Q8RZcuxARus9eH8EsEf0P8Mq4k7ePsf811gWJn9eX9GArB4Cf13DbAoSHJ6+VX4wgILv8erVlIcRsIZ667fdzAAg7qOQEw+HykSu2T1TTPOgUthYzY7ti6yiad2LulfTpRfJn1oiHQgZWO16uuMzKXhioykC55ILcd0=,iv:LPfZmyXirm3QDpWlTe4Mpz+BrIRkOSBjLwTCkm/Nu+o=,tag:vef8RVr1Sq53ZhmnJA0Yjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T22:42:52Z"
    mac: ENC[AES256_GCM,data:13ps3hV2GnwMkIYB7L6V4bKPxVTGP4c1Hs4S8+VPpt/oZ69oIEI9ViNtbHFNTb0SH4J7K2SjwG0xth0/toldzKfRrnF770OxFx/bgX1rIO/Oza4onzd0wpi8Uk357EwiLp14RZNAMqf1UOzEv50JKane6av5CNpIXoNQuSuaJiI=,iv:meWZcEFJrTaFe/M8I2EXRPnmbE2eUkaFkqulxerJM0o=,tag:BgSHHHujEO+GGo2i2dMQ1g==,type:str]
    pgp:
        - created_at: "2022-03-24T22:42:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ//eOc2GM6lRiyV5g7WW73cf0FMzkA/avb1Xpa/ny5Z3EgW
            tybiVUJcRcKqbAe8ZsQZrM2ajUzfVhItBIj3nS5ULZGv+p7SRA1R8aF47yeK8nIP
            +xf29+hBJDZqzhdCw7/NkKHxtZecRPs9j+inQtp9OV4IZFmewft0uPwQ0Scc3x4k
            w1tNyrbDCF1byn5Leq67gJgfXDYM5EuEFcxhdOJ9JURofyKSRTJUCWE+3HHyv1X0
            PaWna2ARq5p4Wd4u0rHskE3/tJFeWTkW9yRUFtLjlmIQCjlHt4gFypltpqFZzxR5
            OJwo2hQ8YS3ntZGpXCtshafeca1bkQ1fWGwnVj6wCCII1fAMCKsbkxWbE5MxXcUj
            4tvPOTqQ5zK9Nmi4hxeyD+sRpp7w6+PECVo1YwNgcfxiv/R3HZ4AAddSThDzWjjY
            DgeR1k7+q/4t5447dwK+tQOflPO9d9vRSM4+BhWZa+e/YDFVs5W86DecNwpTHdKG
            FsCaNNDnX4zXQFOMEZ+y7QexQt4FFLRJ80/7fTUb1f0fVDd0IquE4Xnxc89lbYpi
            i2nVYe5RSqnu6uFjQGXAOPzjmeHBldexMFwJXG1sbehuRt6Cgr3JsB4uzJO/6Mzg
            nSi5+5Ou+rl3IC6xeyFHWIeSi+eIbEAIPP51niPcEOjI/m4aUEPwa5BOW+wMN/DS
            XAFYZ+7rRLQsgNSL1N/oG1Il50Iu0AQy8CmdH/zem8RvFEVLnZYFGW9jjEHQGhoD
            IKkVTKwjT3wLwl3xnJnTFn9KIs0QunO/x0IUox2CGqJ/LfkOYjj21IslXVMQ
            =ZZv+
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
