domain: bigbang.dev
flux:
    interval: 1m
    rollback:
        cleanupOnFail: false
addons:
    sonarqube:
        enabled: false
    anchore:
        enabled: false
    gitlab:
        enabled: false
    argocd:
        enabled: false
    minioOperator:
        enabled: false
    minio:
        enabled: false
        values:
            zones:
                servers: 1
            volumesPerServer: 1
    mattermostoperator:
        enabled: false
    mattermost:
        enabled: false
    nexus:
        enabled: false
        # bug in bigbang 1.18.0, remove this in 1.19.0
        git:
            tag: 34.1.0-bb.2
    keycloak:
        enabled: false
        ingress:
            gateway: public
        values:
            replicas: 1
            resources:
                requests:
                    cpu: 10m
                    memory: 16Mi
                limits: {}
istiooperator:
    enabled: true
jaeger:
    enabled: true
kiali:
    enabled: true
clusterAuditor:
    enabled: true
    values:
        resources:
            requests:
                cpu: 100m
                memory: .5Gi
gatekeeper:
    enabled: true
    values:
        replicas: 1
        resources:
            requests:
                cpu: 100m
                memory: 256Mi
logging:
    enabled: true
    values:
        elasticsearch:
            master:
                count: 1
                persistence:
                    size: 5Gi
                resources:
                    requests:
                        cpu: 0.5
                    limits: {}
eckoperator:
    enabled: true
fluentbit:
    values:
        securityContext:
            privileged: true
monitoring:
    enabled: true
    values:
        alertmanager:
            alertmanagerSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        prometheusOperator:
            resources:
                requests:
                    cpu: 100m
                    memory: 200Mi
                limits: {}
        prometheus:
            prometheusSpec:
                resources:
                    requests:
                        cpu: 100m
                        memory: 200Mi
                    limits: {}
        grafana:
            resources:
                requests:
                    cpu: 100m
                    memory: 128Mi
                limits: {}
        kubeStateMetrics:
            resources:
                requests:
                    cpu: 10m
                    memory: 32Mi
                limits: {}
        nodeExporter:
            resources:
                requests:
                    cpu: 100m
                    memory: 30Mi
                limits: {}
twistlock:
    enabled: true
    values:
        console:
            persistence:
                size: 5Gi
istio:
    enabled: true
    gateways:
        public:
            tls: null
            type: kubernetes.io/tls
            data:
                key:
                    tls.key: ENC[AES256_GCM,data:eHLI6hg/sBLaY1DfAa1j/eD5ERgDH3FrgB4Rdw6AhsERTJZBfe+b7JGf3mBAVyAzU1cmwOq7OXTZfGNq4Q4MK4uygvg5vJkRWOK9m7EvO2U4YbPSlAE+tdOo+T1wHPMN4ZhkS08q7LImW2qWJDvRVzUZ1ls+tp/D4LSUxvNrVIakMA2Ed6FofgutG3O8rtArjRyrlP9ptECw/6Xf3rjLUzj+3hb7DnyyYIEDjD8Ya0cqcmrwf8rXG8JcheipKM92XF+meZlghzqMCXhMAwN59SvRSBUpf0UZdT8osdqhn/XgLdzuNBzE8d83YYWlIbShg7JZa1kU1l7+stc6g0rqFfumPK0pxKHxqQZulNImmBUTuDcOV1PsnBrPPKAz6AStym2D1K3NlN3LNU2f0VjcCAyn83USO6dX2rZvYAzne8qb4bTopAIU/qYG0cFPGsotf6Ec5atrJGH+6Oqu8Vy//v1jrSZxVgKPuwMcmNtIMYkZq6DGwXDWfCJ+HvqM6fQDLHURk/Ghrb2nKhNJlYx0Bhi8VvEqizCJYAF+RRawgtINM2mcaimqHSkuUw4HkGnV/KqLXHFTKqGcmqdUtD27yN1eMB8fzRsm+1wRovzLnjA1ogFW7BBTvl7Vk06aTJ60gEWI/24eNEe8dKA/vdVwEFQ8sdOZhwbOUDEpqCgrY5UjLTsWL2y6oIUS0KOciWh19+NJ21LfImdYbMNbKW+ZfN6n3EIOG/R0e76DUZa6d1TJnvudz6YPcVROq+X1Zyk1Oxh2lto7yKzPKi4tbPpL5KF1xAFrJpF+zAeXgHIj3uMfRL5ETq/sBdkCcSmq84BGAjesVkzUYb5jpXxrqeIrGOFuFdpzqpC2VI6tJw5DbjZ/hOl53phEssmToSa+eH5+8i/Ul3hvLO675iPiBHvTg/6VwALn2TqkWeamRDkJbjaXvq0WZpssgdfBjrhsgWbeYYcCJRHKfMlVk4Xb6GPbDv5R88/PQEmIoPfz3H5ieZrjMSbOONCP/cmgJVfj65TF+6BAEMmoxBlZEABLWdm0O/l1XVsxhQY+ZC0kgUTzpJNYpWPZp+TQdPAiVQx/PakyJlzaYraVCNQcbvNgqWXl54WoSd8F/fyxd/qvgPn0BNUlfmN6HxXtF7aVlJSwd8Nc3o8tXEL/AQ7nzCczAvHslNhiAekv7JOzFCG2nRzKWp0T8iK/rr0nSaETlbvPoXfXrGheYqESLZPRm9kdocvV0EMXG46TsoGjLadux3O5gcrs7JefhaMjIyL7jYT3rbFX8+xbRPHsULcc93rk6VPxi+k2DUDY7bKNBS2lgwyTCNpTbjGu+sz7VmYqlTgULr4HwKpjuFDUePUkc+Uweq5i48DDDma1sqb+RPcGiId4OSRALYzeM+ndrJqsbiqzQ0RKTWHufgdeTn/dXNO0Q10xK5HGfMhjhd56LpQbrT3K9G4UMXf/iRPZp8WGXtqklHA+4jwS+VNhCbUDIx3CEXPSUOEvJqzjeE76zfbTVkWmPXnqG51rXTMkIMMcMV89ueTBNvn1NZWAUwLhh1wm59Nd5zOHLLf2mHlnMrSSvAa9ggaFExhgmSyfiriQE+A3MZ79zB+f04cF1e8AdPjJPT5svUimUbuXmfLYVl/Q9a8JqBWGQb2t5V2p8jBBCD6mvvJugznklGnf6LI4qglzuzvNlATn7dECpw0PSHYd9NPgUDjniHhZRegCMf8lL7BjdDpGW9Ve67ckCxxH35RCrY6NcEQZ2NcK+KDe4F9AdyRr5Tz1Bsi+seP3KD/pO0/kXG385x8Ca2cuT8DdPVQ14fb8SASng7cVdOS7L8XOfr2mGwKRVubJ3IXEEGb7QtdrIyqdgDr11T7gkdw9siUnN7mpiTkv1TUkmQICFHlW0tiX3ceXzehHh7fHgXeZu6rQAqu9vkEqhUBOpymSl2ufjFImFEP7JwSAtx8zkLv/4WGNW7EuXkGs/kgeEitoV7825CKv+sRMCXgyUv7D0lSX85yxJuR04sibRqGU4873qVBgi+DeQMXV9AuY8GveNTg3vUkBwvrOe83k7hBAgSjzW13HvrNw8c5SWDdj5OXqK9Zt9f7GHhphGtEimhhwITV8Xp+yV3y9ik5anGWM1jEkD4h5o0nBSMOfi+MyrN5M4BDS7jjIISsBcpYuakJOTfkumP8GwkGJQFBEo/FWYtw8d3iDNPAf2/D9DLh8Vq7cvIxofrY6/klmeMSkNilVtiYNNtdFdTnnF2BV+A22vTVvohYkrisxI4St0Hbnec4oyth1hGu/zEhzpG7l5nX7O8eN5QY+D9z6kEewSf2KLH147cJ0El2JIPp9EhZ8LOzj/qrCBCCw1Tzq8LBW63tM6V4cuy97g9rNrURiwk+OOYVUNBqz/95QyZOVIdihdq+8R2+RlBrB+fgGiAhKqXlE4OMGFQkI7MxCyr2EH2koMaekcoIf6DnKMtF24DdMZsV1d57Xan8bOsJ0QlxfkIGc1iI0AwGnM1HxbffzGOK6J7CGWJCGkNBrz4HFkVAX8UbisEBhw9t+vNFHOarYSnKeGt/mNhXtkP9nAV09cSMRvkcLU7NHqzlxU2sr7GlXcih8jB1uQws9KFYCMr4sPtX82zgFnapqVGGHDZHvAb6AS+jvQv2fBZBbrkcHP3DA6UtqPWSthvetvHNUUZbGLm52cMzBAAfZ7G7P8OW+pNUb0xwwycyQsZJT5vyAgMg/3n0EoQ4gNsNO9CjFXfXmR/e7yQ55RU6pIdIy+WGfh+LO5qungh0FRAoGAb1Sb2sOma81MSgqArt2IbnRPxwiUGhU9/T+C6JtKtlc3tkNdpZ/pUUJJ7SjLKeZIIi5QKEEltfp0pKtqw4lNle0pNLrH/ZmQRFLo2roa/BAhKgKw0MBevtMbgDyx+vVn8MdQr5bjfbi6an8ceEVG0TrliqeluRIY9wP0gXu/IukjTD1RVMReVraVdGMhcZUBmSjJoMNmVONZJ72G0k=,iv:1A80Y7M+ZGzNTWkjjJGlq/AFMUuSzWx1bmhk/kWI3pg=,tag:R8fzImdrb0/bbHDPM01alg==,type:str]
                cert:
                    tls.crt: ENC[AES256_GCM,data:FPHUWQL5UiGGKzfE/dPiFPFoym0aYe86U2myPlG99g5K40SF3JhIuoyLI9gD+9dainyoi7BH4zYHvjouheIAcnaUbf7+KXDtMuXLuO4M8r7XMmH4CQTnVxTFwp2X/pp+DbB1avwB/HIti21tfQ4in0bWp50lAa0hU5VC0UE9/5dIYyX3RlflWWlFqzXx0jJzktQqE7/OsGLep3z0D592D1FsLxERDYdEp5zrpKnDwL0304ti2YKW2Yy2B1mMJH6vS6yoOh0XGQJfqN6iEJWkFEOUr0r/RZNHykR+rOv0vsnDilq/a+t940pT3Xr2BigDLR12/NLMsWBOgqhsCS80HdW/Ugw/b2Mh2vlJbNrYrbYgYnd9v/2kTn5YEwnHwcEYm9Pa6/A8wE/ReLfPcp58rhLItM41g6NhX70LrqEi2D06qnHAG10x8LkPTUimaY+jcZ4qJJYm6cAwTCOPkDYIKvYVY3BEySZfid7P/lUnuzRZM2ZsY58OEWnhkXQLodZYkVruQQHxQgW6TFjUfetY7ZR+wmBonV/QmCkB/xns6eLtwc/PNrrtTEfjXXRSfLQEo26//El4ebDfscHA47jTEyk/UeT3/Ac4HeOkbswXSk8RZtXBdIHFWWgyKTSHvpwN2b/p3dwkV9t5w+IsCQNEiVTVWyZAdYK3v9e0QfAVBJpSb9qNouBX+RDXZpcAH6xpoueZze2vUJyr++W1+YtIxd96lbiLo6fopDMwVGNkMwVzhS0r0MuM5TXQRlEGbv3fJ4cIjWl3y+3NekarOTl4R0eH+z64U4IA8rZmXcfOeKZgO4/NmcyX9VaPLAZIQRhRVa7E8l+oc29q2gMX595RKnc4UTiH896n8jZ7HunXxnKnki6v/hrWTfHJyKXjqxB+25KxmeTxuAa64gZMQZ6o27/H+wlOmsu++FM8AW9bl/MkvuJUup27jAcI05xH2Dno5mg/oViXIrzb9kOVy9+Jr7LMYnzDtJnwMAMJNsO3iI+WAbXhUpklzo6/YWjQnnmFKVkoMHQugm73fHVE/L5VdcMfJs1IADonKj9cX0JFjfPj6ImxhUryWDJEBoLvMhcLY3NGQ/KuZ0tsdViiuHBoDz73Ak3Q+iWKs0tc/5FUV/Tu/r+slbdVBMEQ7P1sMQmFGWU15820b2Xi10/AnnwVaDkJ6Vw5Dgw3je9qLIVfjsRBOxpY6zvOflU+5QGnjfTzep95GfzCocey8LMhNUWHBqJOSRGbrkVxH9IG3rWglOvkECrGSLqNvsOS1U9qJfZyd13ILySDX1zWLFY5f/bmw+6Hsq6cPszTu6wJqRx+MniKSOiQb9BK0DA1eN8UYp4VZltSqueMhw//LCPwsRB6aASsTglk8QfgP6+VgOg/EIYcuJq4dyBU2zmSg4qSh+yAa/TeqtrIiPm4hEansLbhzdqEsehDPaO3Sq/QtyKOYKRRBP4yMiYR+D4/d2CIskEQa2RL332hur972Ani901jjvHGAAbIIz/OwYOdmrYrfJxZRTsNY4Tda7GlSnpWo3pLSOvkYbKu+N2TPFMOjIuaACl8yrPIxRTg3A2o4/dP3SaZ61fFpSAO5Zulsu3mqLtRPBjdnAnOgSQuR+0Hsrl660fQPaZDUYuSjBdsStLv5vFeGkmfvfjvU1A9KEir1D5rqs2kOIHAj0C9MnNZyK2Sc8xqxNb+WqY8cuuMeuRiLFkSV3D0iX2mpzcsZ8eQ1WxFMlwh6y/UboslTW2iG0f9OZr/Vz3VGl+OB/DjP9dbwfCdS4R4f8aJlQpLQuDhZj2nZGUnd/6SormyIM7Z1BgRmTo9mAStb6qX2tU+rKz7+fEIzanpxSnHcSrtsDBmW6/+l8eGT1DOK8h1Kmrjt9LdLgkmXC8ZrWc87T81usySrGt/7StN8ixfCNSIfNHFedrLZ8mqzxz7mknEHLT0xkF8fs/bRLwQbNvoMSMgZj6n6UBHWS4+QYs0ap73DofY7cwRXijgghDJ8hyGSFOrDSGR/U5cdUCHYEsjRuge/wRyA48fKVOfN02qj3n8bz8j9Z9sqQAW62Yq4Thd1m+7FPTMg3c1T1ESL7V1KB8CvpbQi69SQhroKA3JNRntNXYt+2iokDgzbSMCITF91p6SqOnqVPLFUTltk/MAfTTwTdKYWMDvcVweO0VRTsdMcE7NLsxA7GUZPKczh11q5roBbN8JQLirdIZZo6SdALyvTnlztRTxqzkST8c4yGCMm0k09fjU/3XNFb5tmvn4VOLiNQPNo10lPlIj8UDMucutN6Kq2ZTrIq/lbu+SLeCTrnh8MDeV3X641hvb7Mpm/nFMbvQc73qs6go=,iv:NjnTsYpdQYlaXkaBjqGgjg1MUGa7vccQWQrMq5evgGs=,tag:nX4FCQ01i6V4jAW6O5RodQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T22:46:32Z"
    mac: ENC[AES256_GCM,data:cZpLb3QdXXOII0k0C4kg3CJc01aX9vpUJ7dz6dGRzdQH7/j3bm1xyC4P9rW3qfRbimC6Ny803mIEyVTlYKfjls8nkcn7j1sBk8g8cNKSW7tUpXtk0CckLOxBz70XiphwF/qWH+ppGmLDYmNN+EmPoA4JYFyamBVw19gPSQwDZ1A=,iv:9uQXMXtE/TwnJVWtktWwmyVU6Q9wzdJ1yqlSwbje6MM=,tag:UP0j0+F5n7dfJm/LKTXjUA==,type:str]
    pgp:
        - created_at: "2022-03-24T22:46:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ/7B1Ai5cQuQoupL5ubi4FPxNaUOxuJd/vdTp5tM+F19jNX
            hXW8pXdGvvW0eURFV+YjUbAlP4sYiEWtGe0LEdt6OtZr2/kmtmdQP7tVc6MdqR7V
            841dF4n5/StJd+LzskyTbYXsOf+BcVRR344z6QYMf+2RCWZW59r+48vIw60gcr1O
            K1CaXp2BvRHQhQLAFtFRGFMti5qYu8m12nduTGvudz6XwP7TMgnGB2VWLOBn6ZLg
            aR7iJOjqv6q4lBmpE7ezhdgm+kR+2ZA8RIGyXC5fqnoNUSPXlYSSFx99VBDzphXC
            X8FySni7us0RJOEExQOL8a9f7fmFLYiouaWuaVzPCYiI7h6bhI1UlZvD8WaMwpPq
            S+wkeau2m6wypYqCfuZmG+SqPxR/t4K//7VHnE4+5c+KdHVsDpg5Z8/TuP4tgzBv
            +/ZLLniGG4TPn2UwsicEFT59gwYJO2UA0Oo4maTae84EpO16Savra3rqEkkcll12
            bR/stTjC3/VlNVOtThforINWjJRS+1LKgm8yOKBRGlwZeAQH82bO+bCdlZW6tBU8
            yMiJFzLVXTUDaPls87FFZiYmpw0gPu386T8H6mwblK7EmAH6fSMgrEMzlZOCcLGK
            F5DbL8JgcBGCY5t0phVl4q1GOUTmLpIjHK639OkLheFrFHeDp4FV+KwV+GDn2hvS
            XgHavhPoBCZbG2KWgTqs+Qp+g6/G1xVBb4xZK7w0mdqZBXZo3XeM7AXDzO9NmBpW
            TWuU6XAaVv7t9PHzWwa7TcXdroySy1mkD0Llx4/isrHFj4Ky8TLIxEq+h+FmFwk=
            =Ii2K
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
