apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:li99YGE7fB5J1S4ZqKuSOdtytIRrWb9L1cLD7IT3sdpfsh0HwuHAYKUEMWMvUTPjD8Q8fn02owDeYWDQjMH+36bFeT6vWNrbLY15+QCvJ4ie0/PY6zWQoCfUue+05WkRQB9qkUXPGU2uo+heJAj4kB+VnLS1346IegOc2zpW,iv:FcXNu6iYN0EtG0/FTdcHpyldJnPHALGNo4TKDxEZOuY=,tag:p6oPO0IvrgkxN3+z2lp2cQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-23T20:35:41Z"
    mac: ENC[AES256_GCM,data:vJNfEzIn5GyvPAitgAJoUXw4KOuel6j8z8JH6oT2beZ1jNhLtnCEwN3klOQ69LlwM6/9091duitN2woduM5+Mv1IVW81LawSxzlD7XiYDEJcr3Qjs7bIBrWH3JO6mMNpg/H/eLPyWfdIKhX3quxelimV+J5QnlJ3qXzf+/p1aSA=,iv:GiEqaV9HDAAY48Y2i9irb95gWqaMOkGsZ0TQXfBFiR8=,tag:Dl3kxew34phZ9acWcaO55g==,type:str]
    pgp:
        - created_at: "2022-03-23T20:35:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pARAAhdrqDIYvbfQBj23Rm2xgaKwXWoZ3tLfDD62AeDfkPxb9
            WhWMltTtGRazIcbDptNdT4avSjworqWASrZ/HvJo0J/JoAiCc/uCuXzru7elYBSh
            SB7ARbcfaliJ1pPugcOqMBrMkRyP7vR+ZNuzZ2yFjxicdgEgAfsruMvhaDyQiT5W
            KWBZQ7JgcopkSPyh5v2jUqr9zODEqb//rXPRhp9JwIqG0shb4vyLn/DZ79iZPIoE
            fOxPCzHPB4WYlsfXbqDgJvXCB8lTykyYjtmPuBRWn1PsnqUvRF6M0PKQNkErmzVT
            25qCZGQpYM3+tWO5txE053/YG4D51qUWrfv9y+baggyZyWuxp3BykL/Hn466+ZDT
            ekZoKPZ7redVgsnNCLv730+f4TFTwalcYBCg+/SDDLDc5bBywe6A1iRhGUKzetyt
            6selsgVjyjUXNTMkYFiRJF75WGWuYDXYLcfsFFaktAcDt1hFrMJaz14mNDGtT/ZE
            gLzWGiPGxrlJr32M2Gu5co4NoWiQwUTPfhjPRundeSnp+lraiUpuZmY3LxYUzaRy
            a4C8Z+y6/m7bBGdVWB6R7W8MJHMYtGFf/zVvqd92FjYhYk4t1xb7syJ3Cw/32BZN
            X903uHRCCFNXWzWAa0W4uldG+f+jByQTs1i45ilM1GQPOXBeUO7QmlXY00egbQrS
            XAG1IqokirFdo98fco5YuUXJ6VFAzCvARWO8LNXLcEPXQR+UH55tZui0euzHT2M0
            U7pBHL91+rbmaszsYMqvhnhVzYCP0rvPUNmWvTZHYmf11ft1AVZQR8Gk+Pwq
            =ePJT
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
