apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:rdtgPwibOWle+8eoYHFZM5Uj6yfALpRKJ+FaTLPmb1sdzWqmhlMTDkiZXZWU3nUU27vQRb9sS82Q5mSUu4EKDP5YXRz+nmKM8IfxWpGy+hrFxW9AZ8qaKyUcm106Z8d5S8A4PkyT2lbuXsBnEB9NQBK8cExzInzH+AVHf4Sg,iv:fTPZemWxdEVp6zFbTz435Ludc65msQDzQWMu+rQ49p8=,tag:3TSUPWbe0JS3vM352xcHUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-21T21:22:59Z"
    mac: ENC[AES256_GCM,data:GnNxzik8YrF6EOhk2sUeCir4gOvX2bepCCuAQvpnWYVxYZbkMRrTOMS/y/gkaOdbI8E+oqHgQVSWo53AcFnnDbapr+xhLDgPS3mMtDwdyiA1mprpX9Tmn23bO4rkVV78pNN8vkN/wXIDQdBjLk2pKeV7vnLKTpJxLeuZDQLNEIA=,iv:Y3UPa+CyDFAuDi9HnJGl3+q4W/gH76IE+HrRQCetw8s=,tag:pGg6paj9pwLAa1Vb2BHb0w==,type:str]
    pgp:
        - created_at: "2022-03-21T21:22:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4ktVzGHssWaAQ//c/g7J/f1T6evW9F3QsvpsbrMB4mFToERh1G7HbTjK/U3
            asSmRP2t0/iMl7ZfS2D2oE3Dt1PFw5SlJ6MBL/2kGFF1WSHzGpxHJv27hx1zjGBY
            H+8Mi4yIuTq8b+Q/Y+1CrZu/z5N9zt998xoIx3TEEmM1hk5ySXQM2pecIYfyDCmp
            xKwDMVC6vNppftP8onHhbn/LnW41ERM2G5L+chM/77N3ehGjCpkmrIStHMBWFm/1
            xu3m+OyjuVKE5gg5iWWrWZ/SoZnJ1do8Zd0sLKjtSgevMtOUsV2yHNW3Zpmas615
            fBHY1dZ4spRyHN815yxdi8v9UruYzcKcGhgR6gtnabNvtxXirhFelRF+O/mGXPjH
            D11/u7hLscGcaxOUqkts0kFsNXRoGldhLdviRKKvjDylLmb9qwS1S88aU2eZCSK6
            ahUWz4EVHDVIcwLqSTg5FatnpaPXRg/41pfiiJLVtlRfEivIqrSv8wa8cgUuYwzn
            4baS35BBJfTIWNd0m0bMLmAX6rqIlcPCvEGzdBAwXkIBEQP39gwyHBRW6zVeqvKZ
            MfIYkVB5/Ojrfw6l+brh6Q9TGHEwsysc6A2+mCn6Zwg3n8wkCEawWppwoSR9ImEi
            xubHrta1aGrxVVYHFp34RMxbK7acktFPhszB3pcgvJBtnMTHsxDhGyZHWSBBfcLS
            XgHFFQK4jMExdo9ZPmkfjKOWAbDjgTuVVfQysX/i78SwcZfXqfuxK8KujKFW+49E
            k2p+4obctap9B3JnvH9VOOccaAXHBqbZtuGiOWKD3c0+LYe3cQBOfEk56NEZsz0=
            =/goj
            -----END PGP MESSAGE-----
          fp: 3E2981D0AE0551ED5D1A0F062FA0F56372049B47
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
