apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:oq+Gkvt4TP5ZrXslVSLgg2xUTsdtXdT8N0mpv9TGOgeiFX2bYSm4RUv2/gozdNorTdO15PjOOYXqqG1cGGxoAJ03bY/clmwI5QTASyd271gS2PQuSkTQHKmMUsJtfdh4kRkadYZKrg8LovcZxSxc9AIseu1of/Qy0rzUnQnB,iv:Sc0bT2Kre94OkaCusgfj/mTRpsuVJq/wJQm8QbDTXRM=,tag:YAMzHNUdVtx3MTIyqJvCHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-25T15:54:28Z"
    mac: ENC[AES256_GCM,data:zjWcGSFLnI7W9PWb8gtOQdCvNhix6EgpOo+9Yd5rWShE4ohcgKa8EN4WHdaKd0ywyYyS2TFcSUNIN9RkXtMhL3dMCxW1TuyWwC2cMZkU4+RLgIJoQ1Wr9DgN/05iz5V0uuUEVc7iVSp4r/ZDELimYmF7ooeBXetF7aXMV3/KPNg=,iv:ucZFDHq9wIYDsrs3KAgVIb+EE+OB5pWXtyUZVMaxze8=,tag:xMNHbmaGDHFwRjxTPCIz1w==,type:str]
    pgp:
        - created_at: "2022-03-25T15:54:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ//YXGgVYAkjxroyK+/BkpbgeNy438E3wOfjRH62YPtb46g
            hN7twss7PKNsU5bmuJVk+GYdBaL+7OmTnwE3QCFJr+FuOO+AlnqE0FfdDjptiKHL
            u7ZgXOapQMMB59bLq9ON+dhaSPrciLVRH6Z/qYzbF9zF9VWxmvV0fd+lRTWAl7Kv
            IdDP6zuH+mwi6zYzWGk9IrU5SPuwt1Nvie9gPTwLjdgD4kAW3pyisq1ur+bdla36
            9wZPjBt6yD5poF1+hI8FFqAuP5o0Lg2qVqrkEEFgr1K7rwuHXIOS4nDNPqAjAHvj
            CvxufowUPcgaqGm2IFGXEficMQao7F+J2PFD15uid5KpMMtVmJWHCbjnbEgUvxHK
            udxYx2QXaK5IUCoNQsS9Ie7KJrd8hI6F4894t1+UZq+DtFlycGjQgXvO0IYNrEha
            wcoXmyMbtXJpOtW1CIFjx2NtKlAcYsGbJTE9SvtIyAr/K6byP44So5m6+ioaQ2TE
            1zLKNA2P8zsrgw3uEGJLF1S4wSHEJgBvrqN/9DWrb/yafSp1IqiXFGcxRCilJazI
            UUzBLjPd8paz4lecn7ZTOEAUkmsb/RT6RkoC9DoExi2U9X3b1W3B8kJ6SrNcC8If
            b5f1Md0gVT1LCshEXgEPL/xzTW3aYPbCTn3E218dieYqumZBflbPiq9p9f7Dg3XS
            XgGCUqGPVrbB4BkO9dxIHAYpyiuzOMixy9KThg5Z9/qfrgu1MWVAAYJD9NxOmcUP
            a/ifSCBkCoE3SO6rvxq+FDoYs7EWFC7DkMiQTMJFn4AYjaq1o71h9OfHduhRlHg=
            =WaAc
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
