apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:Fr1/lRklBpdx9qdwOuuQMlAC2eQ0jSa5ophov9i3DE7hD3IVKiUQqA3ZYU4qci+8q51osRzSTIBW8HdwjC69f50vuPWJJyTjY4UgcPh4sgZEK5TnPOgThHHanFuBGmuIyslPpsHkJBINyXusXdUNUF4YQ/qLLnnmzowUL3jc,iv:zMb9qN8Ytl7T4ZcUWs94kV9kNMNeedgUqGgnyF7roJ8=,tag:DNnRe+MS0NjKLyJb4hD25g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-16T18:27:35Z"
    mac: ENC[AES256_GCM,data:MeTS+gFiyxyPvf/1nXQOCAOK0oNQg0FrHdba9ZsmIdatvpOUe6KK+IqbbEWhT+jo+hY2fBbj3uuJepC1PokXlmByYjPgx1CvMFi9dPCOt9oDdMmsuOncowNIT+vGEp62U+rus3LSiiwC77H6rMAK4cz3L2DYXjwfkVss3TAwrRY=,iv:V7tczaR+rbWhuEtzSJiKMl6XNQM7acViBnNPLCYCT8o=,tag:0ToHxTBtazcIhd0A+HDoqw==,type:str]
    pgp:
        - created_at: "2022-03-16T18:27:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7IJ945YqAKOAQ/+LoV9hV+UcEEkUbO58abMAPi6Y0HYV2ZaXM6ZzRejrbHM
            CaH7LkTBbHgHfSG3LVRyVcQfYjrcQf+f0InYHSFho6GE7BL9OplgwX7Pp8maDzgr
            XukDtGPtrG53wREsHfP0Jsz2Nm0lfPDAdLMv3k7PV1kCzOmm1z3caWaRPxzG2mAT
            WheX34QFRE2eb8T66vyhlaBS8G73fyTLU9rJjz+XRdLC6np2hm7MzCXbrBfFOZYM
            caqj+1lpEHKYWVzwx7w9M9azCplCWgCY5iuGXC/aDh6j1Rj+z+abQs6JMbDPQOND
            eKH0u97A6t8dvKxKqG6qv+zL1pn4saqenH921r8hTq4mkt8cQj5/XiiIxs1upCS9
            r8rfR83YbHMf3fPBYiLSl8JEYzZrAIhgnYMI7Nw9GF0/Y4P783TRizUdKQfSAj8q
            vR0bAR02Zr6TV2zx+s3nIIqunMAoHEcLW/imFiUvxCokoBZUadvgL3eQVCXsP22P
            AtbeyNUQvJYfDy4htefk63NKDsZjx6ppxv2Az9e3PPBf+PnDsVlMr05Evu6V8arq
            +IztpQtzLgF4XnFtC3bTE5A5VRXu9sot5aO6K487i6joTbKsfq9zCqn1ofyJDTX4
            fBHA2UiwaijdbPbtDygsuwLNZZD7spt9uBn4SPgwJ11wUwcrxKz9/iddg8J45CDS
            XgEt6MIvzRWexs6zxE8lfS40S33+obQdnjF++AdAkTc1pAF0mjB6vWHHOr5uT7mf
            RpbaYEsSnNhFQY5vG440Zpvc8kPExTvE4NkDwbas0Na/AGGcvwcPRKYJxvS4hX8=
            =Fd5N
            -----END PGP MESSAGE-----
          fp: 3F3BB5C2B4E450537753ED9AFDE885B4E09B35A9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
