apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:MSybQysBDUPIiHL/f54RVVG7XDd4R9BZCjFHDrovGxEFrBHYLpaWpNUovBMd6b6NUCUiIcL0eTj+FU39IS7aDVH5Oe3AsWmsUrfaIFlaBY6M75J6u6ZdDaZrdBzfjwd9YvXvBjxWXVKz4S7XT/wdyrsHrw95+YG4USSaAKpt,iv:PjYIJlE4+Fdgqwyhtohk6nCV/ZLaYaFzSR9Yu+9P0vI=,tag:U9rWjfd6s6OXOrCX6C3Pyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T04:44:16Z"
    mac: ENC[AES256_GCM,data:Y4IjeKAzsGLcZ1DouIKUYDQyrOjYi4/wL+LwGdAJWvjJbe56yP/oVtuVpd4l9xjFK5JS9YGPpdNrWYlOqe1E68vwyBlaZ2BZR3skz/I1ImdUlYNOvQgtHNXJUMdssa75xIfCjtFN1TwHEytQTAbUd6i/N3B8GURk/wEObUo7UWY=,iv:WOvdUXA2rqlrz+rkvsrbIRZt8q3rI65L2qyJrwfdav4=,tag:5+xr84Ds5CK7pd5Fc8TWAA==,type:str]
    pgp:
        - created_at: "2022-03-24T04:44:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ//YlZahLogrnHNA4+nIFnxdLEjYONE3sbnd+Q1htBO0Fix
            JHxLyXryRYibZ64PtyA2RMevyWH9eqL+n3BYJ6MhLCImCqDpQ6ms26DQlhqRUnoO
            Zm+zydP3j7WZ4O7PsRDPrzahocpk+ZcwTAw3dK03m+A+U8/QmUTKqBmJZyLCFKAr
            hJf04nQSLLk2IguM7JRGD8vy3jOEjf8vwZDXs/pogllxeOTP3qiWcIAkNqb1TDyW
            Qf1KGq1/l86ONo41gu+E3fH/O6art05MVCUB74tI5iUBBJHpqbK7Suz6gZKadoKr
            bcYTihLJzmhqbgh6ZkXiOj8SzJix/khdD30s/Dxry+WsBg/MJG118p8/Y4cxk8fv
            hf6jg8zm8yCXTMZcHtHRZi1yD3wLFiLPflCeEzK0Pk46riizRNWBNqlr86Gmoa48
            Pe5W6MIn5fVECPHsiw4P+6C0ovah2+VV8CmXn4Zz2JZmxYxAXGlBT6INZjDYmgGJ
            Opgwlt+r5/6r6SuOF96DXzB3wkjmN51DpwCtbPyUSfMuu+GBClAxQkaGJnC+2b/o
            0x8pQyRZGOZ6+5HlcSV11v2Cr93w3NzZOeA19RMvbj7ueO8xCpYEkmC3ZlaXD9PU
            Tg4wNQ6ya2+RuazHNHDwJnRMf3tY2TKLpFQuNidMLZ2opO/zDh6MkJ1TeuDTYaLS
            XAE7uLZ9kwHuIN1+5M5yfoaSDqofhbZzh5Jm+u5nimPKsZTt5ISYT34jHoqMmmzP
            om+FRkzqkzIsrJ4JoCnf5ydxzZpgwilw/mhWEWeF+AnuXDURE9dBM6UMKI5m
            =Qupt
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
