apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:R+c5HCU3TBLnzOWGPCc7kn/crPW561+UET02MPQQzTVNxS31D6GGyDrXORPl8Xk36fYx2udoFUySdl119e3sFlioezn6ZvcYL8aWO8WbaS74BRW6EN1E76NUeRwWU7cagKRMDBnaqpdayNx5v0j2KJmzhOC67rmp6vqPTRdL,iv:5zWU8oG8iPFuCnCty5ZSh8KBUNCZobj/srTezOlJRqk=,tag:BdHDklDHMMunNuKECc7crA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-25T15:49:29Z"
    mac: ENC[AES256_GCM,data:4hRixIn+fnpcI4VIBWjTOUISxt/X/kETaJKYjl/ikGJRovErcqu74wahnB2oTK4/lRBZAyUzSvQekrK1NF+fqeXgfmb3i9jG4k6UC9ImFmeG28M9cNrhfl6nBNAwSeYiBLthsCmNJ7uG66WAs1tTw/1ZsKa1+x8afnwPXUpORYw=,iv:wYqUoUscCsmdpCJ2otk7nlFM7rCDmz7UU3g4qY6jL48=,tag:RN8JAHKXb5A36KZcBon0TQ==,type:str]
    pgp:
        - created_at: "2022-03-25T15:49:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ//fezx1OnVQZJyhbJc2TCXphYlvITyYF7/LbvnL+zj1OwG
            IzA6SiistXjG2+8E9k3HXQkOhI/8F69Jgr1kec5Lfpc5A3iC4ovpGBYVzQtsD4S3
            TO4/RGEZOUH0YQfn0jgn5gjl/pfM8RJGftFgZlWl/jCkqZYFpNxszusGKt2V90dx
            Za8Ew7mJCYz5FDOo7zhuZnm/tAdDDSTRWY4yP01sL34y1LGCu3u0ZVPVxOH4HObB
            Mk/hKEY2tlN+buDYO+RqbUFWcsVw8rgenpYympOX6UnSaUdApXIT8moad98McDbo
            M6hvWh7ycrHmx2xJLVPzpH9zE38Q4IF3Lr6RmHvplIr5sootqJ8Rz19QxhpZLJJP
            GIzvrRge9ri7ig9qKHvMYU6ZuqBAMgvt/2z75NcX7AwaW+ZniEFWxAyXaVaHXScj
            abTo2D2jFnfpFwHTToqIbGc4KpZaHW9W6x5uT2Zi10kYNEbc8Lp/nt4wrKbNkhtB
            U9/ghs95cHC+qftzjB0JMCCPZNU85QmGV0+2yuEO4tJLYGoPsiK1WMEtwXW0cRzU
            74LfklWoMWpZj3cK248TmfkCpx+3vARNPf0pI6eS8pE7ykfkuXF7xkoF7V4WUzBM
            /k3Gmz14Kc+IodhJxPbud/S/0ROQLvOLpwP8ES2T/v8TmaKMhsJAowP5aHttq6LS
            XgFBwuu7Q55jAIEYSQUE+Spp1DbAdOy6JagYT9jzTG0cJYEYRJwZkPQwmbLP5wtR
            b6B3hz8+tf2HzqMPtWjXXtP/uHhlhRuikgvemmACOCzDR6IOENg0BSEOrqK5jXc=
            =teMD
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
