apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:+1D3C79TZ0LLcjKpUS/RNMdqHv1oTYLLRrWYgnYZGefaK5cSTPM/pDFTw+Xo0fE9PLO7pFPEAPnTfKvvZWzqNaC3M5cup8Et4d0bxnBUxJsKTV8QPoWOFqnDRCazZw3+uTffadjkcuSbZE1pXfdS47oCEvgDOvi08gAHymK1,iv:jGu4lqgFKXKH5FH2s6b93j++ozIF8tRbHS8gOGD1U78=,tag:H4l+VF8bLShvp4pCnpmSqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T18:54:55Z"
    mac: ENC[AES256_GCM,data:8+6UGBxnO+cjcZcxa/DbwotIKZ43pVWnsMDH8RnjcryTpc75068UEyWeeu0HHpo+/NqEX05aJDuYPPFcEHSgyUxvPwcyVDTlV31/IYHuxkWliIvXlCMG0h/pI4I/a5QN1935xhYdzZ4gTWfHb2l9493SR2cXIvAWqEpP0LQU1qI=,iv:D92CicdJ22UB9q/+WogqtLDwG9mvSyE52WfsAZIjODw=,tag:ldOjgHcAsTUHQNwmLJq9Qw==,type:str]
    pgp:
        - created_at: "2022-03-24T18:54:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ//VWP6rUZ4kjqFYqRyyue2DX0SfofH7Mc9d5qC1yN56Fnx
            ZMcIGyY1+Sh+oEKhodcC2JgacFaT29mo+VM7vDOVb2wsQGTV8+jFiFhlyaVUsluj
            BqQUbAF8Y/z+y6xVlOygiSTjgazWT8E81Rvn+vNxg/qOdL8u2SKlTIsynPadZDqt
            hrLeUwxIjM3rg7DEvA0nQLi5iVgPEcXTlRcB+cKS+h98zFkcppzSJ32O1IZtHycz
            H6kUxvIlmKqkPf28y60ziDJgIECAvg/yvuF4SKy7Au9yW+K6M/U0Pwa20E+sWs2d
            E9uhl675qSTvRVpYny9eJgOKP6uiiS1d+9EZkJZuy+8FphiWW86R9QphNT5GH6lY
            Hs7/9tjEISYvbsWNI1DYPUvbAatZcNr4Y82dPItwQVFnOfSSpYVRbHpxtldSHpGP
            gESA5CmpyafH+6FyKGmqyrDavNmAlmd7qNUxetA1x4sqptmpqWzIdDKx6jH9ajcw
            i1fhNaNkrN3VEqUfgtPRIeTpd49VAd1aU3jyvmVTKJ2IaM7QsuEOplw9zCsY7QDf
            BixSBQrmew/O8OkbQdWX2H4J/gq4StEELVUA6rGNDRT2SI5W6Dvc6ta+HS+yT2Xr
            p7NkJL/zGw6qXMFbDnPdDs/m7982vxdqiCetrX4RDZORN56dRIZbDZTOCVDJcWvS
            XgE+P6to3vYpVgNGGHPReKc5Bz7GB60wlFC+oUyB4j38B4AMDj9BR1BWSiI7qd4t
            SorU/Xvd4KlWmjOiz4BFLM3tMRiFogRsfuhh7Nh+cKnVEwigJNr5BntR3JmoHac=
            =Eg8i
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
