apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:XDkGTSLhbDu6IK0YlVLPEiJg/RRfxZwHBmhSN5lYfIiSigLKvjmP1ZmMxj48E78W5TGVlt4akxVFfsO6sSXpmNoabulFUJD9rBbgcqg++dllWFdzcvTnKIg8DipoUkq4S1U/PFM82uo3JGFWY1PWkmNNRRJ1WVof2Hh3eLh7,iv:mrAe5iRjnEy4W7EJV+w0EZThyrF7to3cJEZkceYbkl0=,tag:H5cJEHHcrISpKLdCyzdHUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-25T15:59:32Z"
    mac: ENC[AES256_GCM,data:1NWI+AXxgPlDgMLrrl6EGPCYbBWf4HyQ/l81yBuVNM3LSepgegl1m/VbQTpw2VgY3o7gaY1Wjtj3U7g93aptJYmQomxhX4eymEe9fsNN8eiwUwSEL1FVBCBaaHlLu3DFMPeQuhRm37oM/AwV1AAR6U8xOUUwrdWk0zpyFeeJAIM=,iv:BOuq1YXVPZ2IKuVb0nJfRH/yrcv7l7oi/tavvHCRt4o=,tag:/IMYJrU47h0eg4onMLnbFQ==,type:str]
    pgp:
        - created_at: "2022-03-25T15:59:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pARAApetIR7J5P3tQuJKCW62gvXoBKnwIcbbB1dfGSd7FDp5w
            xUVA6XPBLNkNEkZz7hqUD9axHtif1Dh2OTct5KjPTpSxEuwMdfYxCBGUCU3uUkwD
            vWejweY9dHDO7G2vIUIgtgwTyaXoIwmujzDFTNNX4hyNFpjBKid2Ck1WKsJwcQMt
            sfJIAdS8c5CAQbzuQ3FasXf3ugP1BOGVGvAi3vQMVPAm5414KOD65kYU+6dtX5yt
            NHmOAIjSqxrGBOZizaB3zX5V2/DMivgFDTo6kiplkS8vaq42/M6lhZLbpo2cY9FK
            nG5SNLUyNkqPSp8iogHT1t3MPCxqdLtxM5J4LSikBSHBoRRJZGum+1xvrH8q8TY9
            DwrpI1IAogP2DER2a5aL/ZpCAhMFtlrmmYFljegSGffasiSuJnKMxzBfTKOixIwu
            2OGoiSbBtvpg+nZpPZPfo4TuDiTS8LVasSbTtY8a/9RXO29XzwC4rgiUAyNF3mh8
            QNUgEOP43dCd5+kafCHBsQtrWLZo8CUOAQjcKQ2/i/MR7SvOBjj8k1kzJRWxMF5X
            VPjzJlN9MmxVyIBGHeNrfvKCKH/ZGb0R3S8vf6Z/BJ5DTuNMIet0+egLzI1Rbiow
            ZU7ujdlc2KA5mmiEgPKfXhJK28zHzEgIJet0yN8RsIVrKlOHSe6Vw2302gSPMvjS
            XgGbw/kziZX/an/2kwo674iEbZQ9AOuQMnz4zJnqvMobig6Go5ksIiVrGnTtSA/A
            8/rIckeIQuOxNUYHWhovmw2KRlwopaLKra5Ip5CjZZn19337cZPDjwfRqsEJIm4=
            =Vclb
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
