apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:6DTAPeV1AYP/M5hNpzYos7e3G7lskeCpDwgaqYHJw+gQF3lZjMwqQY8Weoo7dEQw/PLx5PvSzNuEwzz1K9o3D57KagdXA46AUgKkJf5TNy/S1an73ig5u8OFt7/1s6pwwRYQ5SU+/SK7WoSkXLRbfTfLXOOcSzUrCKAjvyIu,iv:B1COH23pxQH1Gmh0BZ8lmhlAi3CgAHAMlUJrbzOXPz8=,tag:UJ4G5zghNkDN3bEv+zg1Ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-22T01:45:17Z"
    mac: ENC[AES256_GCM,data:hhXUkoeKdTfGk9BJSukJA7htyuy95GR71Xz5XJqXfA553RGcAJKZKmKxnJ/Or0BQU527vmHBaF2uA/B1NBEpMHxRsouKnpdEALFTaPWgC9uWpl2kRUUGzi25OLMN1rkYXezd+QRmwU7HlbvLrpBs4+Olyy2Ch9woYZZpC0G9OrY=,iv:v9/G2Ml4iHqkkeDjmEXYAXe5Ha6fYinwc5Z82uzwaUg=,tag:bYBGYHJ5HrLO2nyCXJBibw==,type:str]
    pgp:
        - created_at: "2022-03-22T01:45:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4ktVzGHssWaARAAns/Mer2oMHvud6X+7I1HC7rh7AizrANuYFOqKOUD5qFd
            KRQswi8tpLYhwsDb7LKFOujPL9XBK+eayKvNnpCcFCU+7ZrLB4mBZdsVHwN4i/YW
            duQ2q6ctBcE+OQQX31jeOyXN2XDZfAvy8D5WZ4XFdT7hlsWSe9CRO4xV73o+EqD9
            hfb7vV5wLKnaBxz32aqIHg43EG9DKRTeqWDJSS01b0ELgemmO6U8QEB5xlTGb/4t
            JjSggonwpXpvwocbqYdwu/7AxfWvzVWqFUjysvEgi3koZJfxe9gtlZeacWj6iugx
            1yZUeVJng/UhAfFd/uf6mm86zY2Khy+8MRaNDVm4hPm74kjwZa/kdmO7HG9xwzUA
            0g2npOEBm8nEsK55HJBC5Q4ehp3fPKyUSTUZC3MPrDipvUX7haNnLdLeR1pHz6wx
            wBBXKEyXPs8/UXXeq9+p1GkLkyXNRXgg1GirMWKvOn0GV9R422+iexAA1at1n0wc
            giCsanQl8aQkoAM4NsiX85P2xs3PtoPsK7t7x65ZuyI3GaOmCr0YzOb/UUsD7iAy
            mvnWv24JFJjsN5MSBRyZtx6JsPSaVl4SXnCjeq2hWcOobsPJYXFIMexzj1MbaOYx
            Q6a8s2eB2FYaPJOtLJLfccNUuKr382C+Itg3Aa7b0+vupckHAtHq7cbIOX47oxDS
            XAHRzDlM4GFCgTicEUXlk1osgJeSz1cII96pFuG1QBnUKm3sL634j+wwhsA9HoKE
            WSX1bH+MQjVWpg+q3rYbL6jo0+fHtXLQU9wP3HODTBd6XvNuxRTOzmttJOm7
            =P5cD
            -----END PGP MESSAGE-----
          fp: 3E2981D0AE0551ED5D1A0F062FA0F56372049B47
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
