apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:4iOHWiQ1E9LuRQZyjZx7IUDETN94NO+d4oxGJzVOLr1un1Ml2todj/kVCi3ZX6JkU9bSSijvRrIKWQ7GzRlodCc2yugoEMmYM6405AxpgJaGdw+8hBzJYsgLbGsnW2PqDl2woREBziFnkEJbkvwlJSTxtgx3r7Km60dxsYSP,iv:Lfurfg+scJlCmlONUdwxCXK126g67P/peJvxX9HX3uk=,tag:+O/9uA/32dXaLZr3KooRjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T18:44:10Z"
    mac: ENC[AES256_GCM,data:cYKiDk73BVHlyY3M8piyXsaD36C7gwn8Fg8SnOAZMOR7klqWJR7yJF8vK3EbOIUw4I8bZ56wveCE8ArwzvheKUEQJC6a2OLR03KqKIpOQi02YexYa6Zh+OqiGdYMv5bNNGQh6KhhHD4DgBTaA4dkzABDg41i6hPXoEXVFhG/Fvc=,iv:OKlzI6zQrgOuv9whLksQYggYlkz0ykC+TLoUcK/rfmM=,tag:m2oprxSeVe4D2FK3LDCefw==,type:str]
    pgp:
        - created_at: "2022-03-24T18:44:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pARAAhdBevN3QuEp94yi5sKvDQftvJGINS8wVMqEfzkSwx4Op
            yAMBhB/YAqYznh/5X9YBIaN6Ql2QgBuQdhIDCuQRmSw+AoqgHInfGmuxJhE6E2MN
            UXw97rBmXewrDInwdFnrwDlMdhszAkrbC3BjdgAzUGrvpXakYiWBa1LiL7GgQlQV
            rmsw21R5T8Ua/eZm0Xr2Uf6k8KdVdLW0kfiHGFmim+9pJjYOaTp50GIgbctIn+PP
            a+JQACLWm/9J+tW7sy0aGUUzVXu9LD+7uRCJ5iKENyqgh1trxMqJ6a2MZIYM+XxN
            UT6JW9syCcLMs9WvlwC2PPhcJ3Q0+pwytHjmBAq7rFCy8Gx1EtFMh9CdM3Fstjy4
            EgqT4CAYJUKjzPhVPSvcOvcM2jUvj+mKFKchRwllw8QrNJjWyMFxYr+tyByWbng4
            LDn8f1jVdxz7I/+bjbobP1Hh/f96yvACUkvNBuQsz79W2zZiRLtXajLVYWd8oMe8
            wgK8bNU2nYZFAtm+ZmA8NjCDih2bD3VXsRxqa+4QLCIpZ9ATFLdczwMxKlsi46SS
            1d/yWcT2/Ant1rAfkgEF7N8DcTjcVHwfnUfrYT6MgkopYXuKykbrmRwrYqsSObUs
            cqxs/m/cCqHMlRZO+IuYkKMKwFQB6xWEiNMlThbF9ZTaaw9FyRsDTI1UmY8zOpjS
            XgGVYEtqRtQP5q0XNYPGE770qFIuA2V42BeqcZ//d7VQj4m7goSeQyYhw0+1fwXW
            9Fu670XirNmEXA6LW0sZHGLp0F9uA5MKN19UdIbCIKpKLY6zAuuK250eJeiFmq8=
            =j1io
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
