apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:iUVJfsmBSM9fx8nd1+q1c6LuhXPe1S5zmyTTO1wUYAZwhjCCTGMEXAdLgXLIV8iUAhHt3n6TFy6bNSLc+Svv/4E88FOL+cHgvbkuXyKrAknt2arKJvFG+ifReak/m/fON6Q5NPFxWyuu6JIDY9dGzwph1+Mq0WNYKTrCyyHx,iv:ppA5J5Zz+FHkt+ux5TXDRYT0RtPsUXhprpJM0BYbyOk=,tag:RzSfrK0qQRHZIwcCrE6Xjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T23:14:34Z"
    mac: ENC[AES256_GCM,data:0umP6Qu0E1xRTT1QoBMVQXuJGbJd7q3YkQhvWA4YWJ5ilSg0ykDcayKKJHWStncC7aSbfPWW2vTgZ1obIig+E4iISTQVschFw4TFik1FiFfzJMbf/HA4lh0NGNcN52OEFcxkfE52Nha3dYQWE0wIOu83KtYfR5xa0KS50cEmX8c=,iv:JdDdrn5X25UR8vpwsAPQa8aUGA/3NHpjzM7RaqQcJCk=,tag:Jx9K+sz3BByZFfIFyD172Q==,type:str]
    pgp:
        - created_at: "2022-03-24T23:14:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ//ZeQURR/erAyz9kzn9pFJruD4Upk7xWKKxsjIUirMWh/e
            Q4Ee9C0lftEHQGM24UH54vZu/0GXBy9ubQ2tsH98+K9TYNJCicsnkfcEp1YebB5m
            gaHShMTG3ol7Ddbvh5nrirdF63aV2lM9po5qwTSsXAG0gDDCcJX+tsyluEJ0yyFy
            por2JsIVDhI98aUlvHE77D8FYtwKRIdx+K1rDf/TruQalVJ81ArvxESAZsYxqjEd
            XANwR8TnB6j6NKl7U5PvEv0b796jlBEAHCFPJF346svFPfjuTvaUe4+/1Pgp4dwh
            WqA59rCh17n2rHfVXkvH/K0xl42t9Pr3F6zDuDARWMqQQlGozbV1EUXWndCU3eAH
            /Sk27s+N9kAXGHL6NmTiDPadk5QPStOBosc3rNp98qCuNnzEdsMwtYqh5XyEzn5S
            U+vx2vlip5i6dkjUVqwH+rrpyWyxEzrmpscA308ZFfvZkKeY+gTCnWr6slWHtSe0
            +ltHn3suOgGP1TaIJERfAZfMhgOMipQNsimWfUU74btbW2WifqGtLqZ8t+33Ci8O
            xprS/oA7pRDo3KHg42C6frsZp3pEag28HQYraaRfO2WEjC19z9Yx5gnMo4ANbTqF
            1aU1MT/VcqsGY5gneE2aEZFZobK5V8rXMHiWe2c1S+qSZajFuyRWmYFNNMKkzvDS
            XgFb453OEvbNUJQXrkuiqW5GUHyytegiaaQ5QU7jM35qfwZZ6pBwnHuMrxHSKTIB
            MGjUzcUXrrPrNb73wcVAOeAryK0W0ZgacELrlZnLlQne9g2TrXUeUTSI27FffgE=
            =zv5W
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
