apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:HCNmIGVUSODv+pZELJJxUGjhRTXPGJ4VlMerXHzvVDbfdCJmlduA5E9F0ERKX2lRvNXuKuaYPPhBjL8v7zsnlH3Nq6Z4uzdZArl7Vi8vW2tkqEvJWqk8+y7WUlOJo4BYpHVUy7DCofuf+lNgYhYV5e2PGH1oB/gH4NHFnGYO,iv:GTrg2JGpdLMoP5xpEgbYk/OOzMokN0EjNZLMeH08Ad8=,tag:o2XuXjbcINALoqI4AY4kaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-22T01:27:29Z"
    mac: ENC[AES256_GCM,data:xgV7QdQ7219EQ9B7IqqdQw4OYLFI6OPgYoI3fvYoJ2blR+Pdwjd0+OJnopckKPCfWtSF8KNfPjuFw7dh9SnEYjGmDns8wkc48vAuoIs/mPgGrE0/AkEbl+TThKDjj6OJ1eAUiYam/KbId5SLWxOpMUq0AtGfKgyOzwCxiXRKKXk=,iv:6g+0a5SnN00HI/ZuQozxIiHR9yJvW0/wYRmenQiIyL8=,tag:JghTTTu1FsCqjrd7PEBdLA==,type:str]
    pgp:
        - created_at: "2022-03-22T01:27:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4ktVzGHssWaAQ//UsrKKqoi6kLr+LP/4XSImvv2HCqgZdlq+Iu6CP8tnN9b
            sVm0bFvVcYDg0KKY2uU85slc/MYXlCR/ifl2uBJoZJ5s+FL+Ka7mLvSfqa4FBvmi
            6swZ1nNg8ddKxcLYlMrcK5K1BysOYZTNeCwLykgf7tKrAHHX9P4Vz1RDHAWw4tH7
            1SSfoaFpGjZ3n5iOeihYveNdkdDTyXhfVkrlTJvr9khq63e76STPtN3n9rGAjD0e
            Y8sC1cUXlRo96Cvu++7NRaBIq3MdxPyc9LxQMUZpf6FJM8k0HY2xloloFP2ItNK5
            Wt2ml7qacOERsUIhjxWhhTUs/kxNL3AclnWmmkVBkB1qZi9XAyBSzneMcDoinzix
            KoY8sYDVfzkQBOrhIyEy3BQ6xuUG5gp09dsgZoE8IHdB/YaenwVnz9Dt+VpIbXxY
            fUd4zQgUgou5rq00GDxX5ySj2gi18KxDq3xXkgY+mkGq3j1lyuyIEaYDc5FncDi5
            DQxKcK+eeoGILq2mXCl1X1rpm1rUyQtVCzNEpNFHr3Yv57lAry52h5DiyAQMDG4Y
            sCxc5XknAvNCVLLqC2O2PRZ2cbZ0lLC3ApRW1xbwJzgxnE8VCW57XICVkUm9vCaU
            t9p7c9S28ciEWxO+r1cu39EWWnhReGW1PEKe8RgdFIamAd6huX58B+Q3Faw01i3S
            XgGN3ZliG2cOSahRY0zvhfl+vPIwACV4w0Ios2MKfr7ZHeXE9/HfDlQNPzlhG+gx
            H6mZG6Kp8rdcVOKIIi83ilz4A4hXCHKMk8hhGF8qlVVm02212JdG7NdBhkjDA6Y=
            =kqKC
            -----END PGP MESSAGE-----
          fp: 3E2981D0AE0551ED5D1A0F062FA0F56372049B47
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
