apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:aGoZeNhLtq58S7YXMfgXaD9vqcNY7f72KoqeGYv0GS0uBa+cQhm7U9pvyZD6/YlhpZ5GWO0PbqcmcdPjaZHsDr1ThNlm6H9TweIwChf0OhWBkJa28275s5tT7huUq0t5bX90l562z4cgR0txGJSzBBsnECfcud2UjfEJyxpf,iv:flkLPwCytaaWnn+dDTG/AdGgsVhHwmZ/DpGyALmJiuI=,tag:+R66xEvyvAg7DmEPhxtH7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-16T18:18:46Z"
    mac: ENC[AES256_GCM,data:W3TCJ55Q9ptv4/nPR8et9v8RQThTkOIf8MJBGjYix/Rc2Qi/KHLkfxBb2Tu+7ME6b4ZMlj5QmFOUpfnX9fAOy5Me68HPye98++DLmYCJbYaKNnR6Pj1gBgInWkABI32UKYN/ePVV2C9A9942Yibdz8KiyuP09v7KFvztmBYOuws=,iv:1ydoW2KxdxufFn08Ar7O3jl+BdNeQ6Nfrd4S2xM2Tmk=,tag:ulIgnYsl/mrfBIqgFazsCw==,type:str]
    pgp:
        - created_at: "2022-03-16T18:18:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7IJ945YqAKOAQ//dd9adupWTAvufMaLXiaUy8rWkFz0wocyDx4buz4k2Hr+
            c6TdoQLlUBolDDUO5GvpD6YA0McPi7iHKk2MtVfUy3t+OwscHE3kya+FyYv/Gl2M
            TZ2CYbbA4i68HuObmkuWjsPMfmVPgGoiuaaSnZFFe37pnXQwMbmqVOKknjn1/5ax
            dkHtyVAZplNXwkgcVed0ja5ffcXYgz8cr0jQQwP2VSl6L1lbN50+5MQkXb6OoNeP
            DGIybvXsBjw3y4wlWDTzICIkGIpbVwTXwCNlFLpY7qZEKbCbYuVNuqQg3dgEmza7
            xjdGDewCoKzYdMkEQeqbIzABvMwn92SHJBEk+uTxybhKfGZX5QaiPSP1afka/ffH
            oprZJhJRc0sy+Tb/Lgy+ymQbxDWsu2HHmNBIJjeoZZWensi3j9fGleZWFEVDBxnR
            XKkb29SA16rPPD2SJshuPzoxB9sxWKupVw9baOohFJuPQpD6ik8akwCajrzj+C2D
            Mt94nKQig8qGMU1TJc/RUPc7AMU00pMnDMo8CuA8XZvDLthA7+BgNxQB2WHb6kv/
            wqaSbE+WipQWTKktioslgYa5ylBzRUVYNvfjmULcnNSc3gRHwrjEk85ogdBpKPMI
            93pNE+mewvj/d4KCUZ1uGx2oQiHMfEPHZjEUjgWTAa0jS/D1ijoWD8SR2HpZxWLS
            XgG86r8/MDynu+l8TrbCLeYydi7cLjQBa4XBX1m8a4iO/ENKHqtcA7cSiT5GZFdv
            YPmPO7XjvdREDrY/kWoZoWSW6K1P8sOzmZuGdpPxbJjj0Qc9XwgdrAwSeXZMUAo=
            =Q6Ve
            -----END PGP MESSAGE-----
          fp: 3F3BB5C2B4E450537753ED9AFDE885B4E09B35A9
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
