apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:MLsxQomU10jcEQDXqc4MJaeoBdBg2YCmeoQSGWENUkmLLMyOLPWrcUsOBo7balLIhRm+8Fv/92e9KZN+pfEKc6LsP00tilAevw7U9RQf5tYP7gT+FMcfj5AKSFNje5NoiQ+m5D6cMOLNlahyCmbJbQdHN0gB8r6TF+hXHFjg,iv:csKo+YkVr82fbCx1I4mZUv7s19E4c2u8v/cM8rrcKF8=,tag:SwlZNYilzjVltJfBaNuzbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-21T16:12:12Z"
    mac: ENC[AES256_GCM,data:9G0UjfhEylhZ5AbczrrG41pPg/JzAgu5aJfKYCB9lEGA4czXltEQIekGolIYwFKkLIG/AgUctEc/ZIB5TWwt6JDEayyRfF4MdrsSu7mhH6QSca9xeyCLfYLkiIqq5vc1NH55CYhbMqxzBMl/yk3evGZ70dUvhYclaflPP3wbef0=,iv:V4EcwSGeRtddpERLRAUwgm9m3LhdaEI1vo/0n04UDVg=,tag:JfLa8eZ9v1dt3uUt6/GGNQ==,type:str]
    pgp:
        - created_at: "2022-03-21T16:12:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7zLMTwjsAh5ARAAizxIjMYpWGw76YogSMHBY/AbhXn9EU+s9LlpQjMSeYVR
            yBbQhLuWpG27bFBP8fY/p1gckW+erJjqokyJDR1pPx0/N4ZohmXRaJgM+Bgx1IC6
            0if1t2+fIkkBIMkZ/GtUO6COs93Ho1TvvUGfZ8CMBm7A1L5FakPpFyDM6hc5xQGS
            vV0c1HncOfmvtfUQgnZN/grdvd89JkBZOfazTBk4kyxCxtvuGK85kDQ4WkNjNyZh
            4QrI6kiZAYjnF/2m3ouJJOIC2APWHnAX7L0N/FXJoKZa11jPkdH3wyaCSeZcwnku
            3mevLFtBHRTEJilWhUgwU+OM8HjGgLe3LV7ULOx79LzvMvrc7Wic4qPcf+Z4lgAS
            d4wvuXtD7m4AY69OgWNCqfB58ka9Piqgaup3bEptzdGq1RkvjNKsCgoTu/7wfuGF
            1XUpB8E/k2SPkQEDWvF8qrlFcEYqOjMuMw2p0sd/O1M6nr7Mm462ToJGwiGtW7bJ
            cpfcfbdXiDSEpWBiJWaiYK3sMCABYJlfiBm5/VqplRMHqkM916oB8YXJUVHJRvbe
            76LrF+A0OeUVV5/Agx7MF7K1UqSGPlK2AXkDkcy4KU00fwhCIgfl5XETlKTryu8a
            i/mOUMcns756VPctS/2qbm6F/09FvXYksul9B7fEDtiFmlxKSb5OmG6QE9WlwLXS
            XgGtu5yII+Y7eFAu8GVdSVRgw/jtCnQRFqGCVDur8tW5Kdz1cDkccycecSWro4SG
            E3b8bD+bq683YjWKplTYAKcyJh15cUHMSb+ugkaFsYvr0XPIAjDmUuod22OqMPY=
            =7OHK
            -----END PGP MESSAGE-----
          fp: 8D22F9F380FA134B6C678E0F4E013C6F682DDE73
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
