apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:yS8kCxIcwndzfHpiFyyoTsRFOt2oPLNjG/0njxYEiJZ/EeFwnoZ8OhVn9uZMpvyijhK9wXWz2brarljc3VKw3TxXXS3cRyyh+GZ0RGVKcxc43QQZLWA/4qDUVoURGerrzTuR9zOQ15EAy5C+EXrCN2ScdsCpEGFtBiAHSF8t,iv:yoAK2cL5I1QfwAnRgDdZg39GzvUiynrQMboZ3uTY7iY=,tag:uxKfSTqNlIUwkeDnTvTDWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T15:47:00Z"
    mac: ENC[AES256_GCM,data:JcOHgmXZHu4XrgKTO6hb6b/bZHX6d3e4aR2qSujsz4bf+EM7hBphqTZ/gEPGTNIQ+ejPltm4BM2S1eKyEbqmwjA0oCPBo8uWb4FSBAuT5jvY9ewMeSJwios6H06eUpFBCK/aE4Hfey3Z9v0UwTM05v6BxJUub06A0ifk4ZrORgQ=,iv:rRlcf8EDWZ4mnUenEe3R4jNTNYQdBW3BiPSDIrAvpuo=,tag:5KSVxTsWTSzoJTyfAvAlEg==,type:str]
    pgp:
        - created_at: "2022-03-24T15:47:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pARAAkNq12uKVa+0htCUm6mmPgi40XMXi5JWtly7azAa6iWTK
            8Ih/0HLyaksJu/0ineVKg+iEAITYDNgTsyP18Ond2oRP1Lbl6K0Y7+yZqIED07vn
            3XpH8aw2zj4XX7JQtyTXaa1X5052GVh4xLh0JGWFpzr9v8PPvGL75zdNev+tjK+k
            mCRlLo8Iqi9KTdU8dUvK6rVGUAmzq+JYBYjR2ZaoeU++CjMy1/7aTgAkcQUrKeaB
            j2YIoGHmOsArGlX4zn52OSonNqaLPIlfst1ug5z0o5p/t0wmg/9BsIQxgLzhMYz7
            IT+d1L9aC3BdPfAdaXa2lqasybBfF6b3jqwJzSB1aWEpJj5adyWIEppAWa47TorP
            ja7EE+BDjge9kOImPmmAgBtKuYnWSPU220on0LV7STy78tCM9nF/DnXA1eJxJpkr
            yxcmzAGMpjRuv8nNefTuORJ2XzwGU6Xlo32S3eKtecE3mguyK4rmRBtbGv0S7mao
            djkAdh2YpVhHQZut6ZkYM6z/KVypvODcCoW8118aqE/1Jv9TBAD93AEUeo9EL97G
            MXgkzbAwZVHhvgVF9tnUqkNGHVHnxkIVIM+lYNX4PvnEMs1aCh0dQN54UR+3bx6J
            rfApEfNDz2SzLDsuyRvlEP8KQctAWbirb3qVxYpuSyfOgTN6ZradUDry257Ugy7S
            XAGSBRTZCJCr8mHxzv1RCvuL214T4BmZhjGS07lt79ahvGACrJZVzKrrgdAZG1un
            WxZuuXgPDP3J1RvTsFH+JO9rcI80HS9GqFy36dqYKQKYiopPvwoIIScujxPM
            =Cvq2
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
