apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:7jTnA/5WQof1v7Mn2v2wR/5zgBjtMD2X22jG+/t9RAjAmYgS6FajlsRR2KbvviU99GmDFW5hn0lJUkAKEI5L2ra1Pb/GVV6s5uXSrddUZ5bBcjGMGII1oiv0/+AMXi5GxSddyj7yF2lL1VCJstp0m3y26DxbCuPU7nLq7yFx,iv:6eGcsYe5tY9nvaVaKRj+NZGU0UekY9YcLzy56yv/Rv8=,tag:dTBbwc3bS3Kv5/sMJSpPDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-23T16:51:22Z"
    mac: ENC[AES256_GCM,data:TcSP1L0E05aUpIoATnI+Qd6wSvI0dkY3zjA0fy5RHAgUUZJ0n3s3GXWuwsSM6JWsgMEAfo43nY1US2IzK3K0sjLduFdB/doOuMx4faIm/v5csxKcVBlyVGy5NIU744MMnsHTjD1TVY/EsI3HGpCpoAppo2+U8kwb2CDmdS5FMTo=,iv:liMqt6EtTwP/bsYwmqRb+tyvS23j8YOlX3+W9tF8bBQ=,tag:gmGJ9dFYb+NAMe1xOzkPHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
