apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:rlR+Hbf922rENPg/FT+cWVx/Y2hdnvJiI5/eEoxNhNacqwV2Q3/LNL5ypzBrg33LcKIFKYkGT/Wjj5DAyn2ZCNjseVsYZOOzozzV8a1Mj6tVyEKEjMdli2hICXlEk8sARPrciIgwbmupCIDLR8OXfUGlWNOc6h6ucyyOtsk+,iv:isCytfJ+VemMSS/aXTi9gG3tbo3kw2yBSNs9q/oL7Sw=,tag:H5SWCG5MFXIUprVIrHsbVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-25T13:08:47Z"
    mac: ENC[AES256_GCM,data:yAR4Yi69ptxx3gnzaRW/SKeneUZ/aCy89Ryiutzs0oya3JSUXNkTM/HkB+4cG0p5LpRlHSfupSnWmacakKinmAFveRQmKWACkXmG5my9ORqYLTxw+u7gY+x9F8a2vfPNI0voBbGK3WI1j7WuETk1xKxEUvpCn3dE5f2vXTcvwmQ=,iv:ZIM4AssC4Lv8VGaROmZ4PBONPdIsmFaTCPVfKqYfL/w=,tag:7af6cHDUj91bMp5rl1wQGQ==,type:str]
    pgp:
        - created_at: "2022-03-25T13:08:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ//SVRA1HxbIZlvVMV3SKeZEIkrVgvzALcBDSkbsjfLMdFG
            qcMuaULxjpD/9uaKSOzDqM5z7IP+n3SzOi9b7rTlPgX/2kZw0ti0BDHos4C3QOOp
            Ev3Ypd77hWdrb4e6DUmsR2+vlSEqeO/Kzi8RFax/GnCdh3xe3e3aVBdusgOkFRwT
            oFLGDmdC4ahBFsoZFZQiB8lf9m1Nf1B9BeaRIDOR/Y0sJ6Q0tI+I383xH0CymRR5
            NI5JLrAsF48sy4PFf/n7rlEZOspYMtI2C34brBEotukxg+SbCX1Vg1YfOOlDS6T/
            /s4aB4qovu3RPVr2FAI9NcXkYrcpPtbXD4fdMXmoEmvjbPbfioSR/KqOZgsUtK4v
            Xn1Xyha7Q/UO+4QLdHIlAT3OsfX/fYoLY8tMlxwWmZTKX0IbohQ/7Id2Sd26HrtV
            gk0zhiotxMidgJlekeoGTRhLkZCtx+hD3oamHYlD8eKEPtViKGmg9nuiSLMBEWjA
            Ixdl8NHV9IYR2wyk6636nGgQvlSXgwwh4wlcXyJeK2wFhrxozqBu0dEY3X1nE8PX
            9cMJ5cJGjh9y0a+aqOjK01ylrqZJAz+tzpQdi4hmlUgPpOohYBNCo8n+Wf3+r8t1
            U7n02YM7KAJyiLw53As81PkZQK6SaVF6TZxpp1kt+2lVtrADhVqHCvdaT0AOzC7S
            XAGKS6NnFMwXOoWmghJtSaEI4MP7DnBYqkFr6CuEb/URn7k8qLmYhDY93jcXaMwz
            AL1U5TxygG0VagC1Wfu8i0KUOxIX9bQX62rNpI2ucmtkLz1x5RlA418uRVrE
            =BYEU
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
