apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:89BoYKnmmxHPO3Film4TXBwe3T+zpFWhbZRFsjlLrI461NYBbyvKaXcDBF7IAGWp28fg8A6mGGfCcbHlo1kz6RHi/KnaL5WAt7jrLeUWrje7XR80T/AO1HmD+qKgdRP3TvQGXS3FVM0cM3e1BRYhyRrxG316LRZgnATOetKW,iv:Hx02ABpk8k6eX2JwdbdqFi3Ln/tbm5sabt0+YtsGLK0=,tag:gONyr2W5kEoimm+6Kcid8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T18:50:22Z"
    mac: ENC[AES256_GCM,data:bRIn9B6/4fqi8ekFw0Z78tSAym824D11/XYbXs4AfK1GlA92OQR22OI/AWyptCK1QSnquw5Iv10fx6HAdiGqXYzKFmrq3M5y6cN6CE5TN8hZX6TrCtkF0W/8MMNzYlhIcE2b4kfWzNIuCNBkqs390H1TLMKsAb56Kh4viNWRvxg=,iv:gEs/Va2PEMMjnrh9eR3qdtW/E+7u8wYu6QsMNBLeD8Y=,tag:xQ/frjuBdzqf2tOdOnKTSw==,type:str]
    pgp:
        - created_at: "2022-03-24T18:50:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/UHow+A74pAQ//XKzfGuNNd4pmqPArdg/blqi28M3rZx+qNouMPfqWkKP/
            KpiTfLtrMoZOPTE/YqwApdUNm8/3XqW6h7J07dWLxTeX6ZH07wsfkpEU5FVDibZD
            /9GNNn5259cY2N8Q1N+ulUlQg18mqA6dEunqWDJtWsAoiM7+Fu61W7SMF29Hqw6s
            uSYLl7QkJDXhMOeaL4SnRogd9I/AL3MBkXVbmhmRIzVrjK0fsoq+yRNfwLA1Me5q
            eERNP0Fdfp5e34ssj0/HJYOts4aUffc6OQjt/J5YkhN8P2uT/BJkYKG9PEyQZkmU
            BvenGi6IWZqbaNkpZBXJck+8o4wve7q5I63rt6bzwEAHJr+snrT40c1Pj4WF299m
            sFsg9VoCfbolRdEIYNcqMk1KxHESaPNflh+wGlpqRqecKosIM4XI6ZQ1y4XPJKql
            cXXV1JiwSQQdT/zGbmkRFZvlQi40onRftFzAtwQnCSxVhEDgFMVzIAtM8+4vKe65
            9ui6ED5G1pOHX2fp6Dcfv2c9cD6sSfYPvOknOUEgtxeOyhKdsFRMklH2cafRJoSx
            T0IJSf4SbbmdH6yO2E0RSY0oxbuSm/CqJPdd53UESr28cNJ5A5MRMixnMS6EWaW1
            Luaz6tbNXNq7SSFYNz3GGQKkIq7R6al9HvCIHSkmg6N66Dtnj8Oen2zhdlukAznS
            XgFMJdh3D5txve8s/zmQYTWOBuup1dxq00aeDHL1NehIeMAU0jGaXLLlwnStH+BB
            odNE5/6rhCACdfB89i5UZONQO7TGAg4bhIMeSz1AmdInWC1y2w6ZzPJp78uyDGs=
            =41JP
            -----END PGP MESSAGE-----
          fp: 674C9C1A0FEBB62E889B2FE9740865FB44BD95D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
